// Generated by `roslyndump gen-kinds` (tools/csharp-psi/roslyndump/GenKinds.cs) from Microsoft.CodeAnalysis.CSharp 5.9.0,
// roslynCommit 35d9211b841e7613c1d2f8f5af6d628ace696c4c: Roslyn's SyntaxKind (src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs) and
// SyntaxFacts (src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs). Do not edit: rerun gen-kinds.
// Roslyn: Copyright (c) .NET Foundation and Contributors, MIT License (NOTICE.md).
package io.github.dotnetsupport.csharp.lang

import com.intellij.psi.tree.IElementType

/**
 * Roslyn's `SyntaxKind`, one element type per kind, named exactly as in Roslyn so that ported parser code reads as
 * Roslyn's (`SyntaxKind.PlusToken`). Tokens and trivia are [CSharpTokenType], nodes [CSharpElementType]; the two
 * doc comment trivia kinds are [CSharpDocCommentElementType] (lazily parsed tokens).
 * Skipped pseudo kinds: `None` (null on this side) and `List` (Roslyn's internal list node).
 */
@Suppress("unused")
object SyntaxKind {
    /** 8193 */ @JvmField val TildeToken: IElementType = CSharpTokenType("TildeToken")
    /** 8194 */ @JvmField val ExclamationToken: IElementType = CSharpTokenType("ExclamationToken")
    /** 8195 */ @JvmField val DollarToken: IElementType = CSharpTokenType("DollarToken")
    /** 8196 */ @JvmField val PercentToken: IElementType = CSharpTokenType("PercentToken")
    /** 8197 */ @JvmField val CaretToken: IElementType = CSharpTokenType("CaretToken")
    /** 8198 */ @JvmField val AmpersandToken: IElementType = CSharpTokenType("AmpersandToken")
    /** 8199 */ @JvmField val AsteriskToken: IElementType = CSharpTokenType("AsteriskToken")
    /** 8200 */ @JvmField val OpenParenToken: IElementType = CSharpTokenType("OpenParenToken")
    /** 8201 */ @JvmField val CloseParenToken: IElementType = CSharpTokenType("CloseParenToken")
    /** 8202 */ @JvmField val MinusToken: IElementType = CSharpTokenType("MinusToken")
    /** 8203 */ @JvmField val PlusToken: IElementType = CSharpTokenType("PlusToken")
    /** 8204 */ @JvmField val EqualsToken: IElementType = CSharpTokenType("EqualsToken")
    /** 8205 */ @JvmField val OpenBraceToken: IElementType = CSharpTokenType("OpenBraceToken")
    /** 8206 */ @JvmField val CloseBraceToken: IElementType = CSharpTokenType("CloseBraceToken")
    /** 8207 */ @JvmField val OpenBracketToken: IElementType = CSharpTokenType("OpenBracketToken")
    /** 8208 */ @JvmField val CloseBracketToken: IElementType = CSharpTokenType("CloseBracketToken")
    /** 8209 */ @JvmField val BarToken: IElementType = CSharpTokenType("BarToken")
    /** 8210 */ @JvmField val BackslashToken: IElementType = CSharpTokenType("BackslashToken")
    /** 8211 */ @JvmField val ColonToken: IElementType = CSharpTokenType("ColonToken")
    /** 8212 */ @JvmField val SemicolonToken: IElementType = CSharpTokenType("SemicolonToken")
    /** 8213 */ @JvmField val DoubleQuoteToken: IElementType = CSharpTokenType("DoubleQuoteToken")
    /** 8214 */ @JvmField val SingleQuoteToken: IElementType = CSharpTokenType("SingleQuoteToken")
    /** 8215 */ @JvmField val LessThanToken: IElementType = CSharpTokenType("LessThanToken")
    /** 8216 */ @JvmField val CommaToken: IElementType = CSharpTokenType("CommaToken")
    /** 8217 */ @JvmField val GreaterThanToken: IElementType = CSharpTokenType("GreaterThanToken")
    /** 8218 */ @JvmField val DotToken: IElementType = CSharpTokenType("DotToken")
    /** 8219 */ @JvmField val QuestionToken: IElementType = CSharpTokenType("QuestionToken")
    /** 8220 */ @JvmField val HashToken: IElementType = CSharpTokenType("HashToken")
    /** 8221 */ @JvmField val SlashToken: IElementType = CSharpTokenType("SlashToken")
    /** 8222 */ @JvmField val DotDotToken: IElementType = CSharpTokenType("DotDotToken")
    /** 8232 */ @JvmField val SlashGreaterThanToken: IElementType = CSharpTokenType("SlashGreaterThanToken")
    /** 8233 */ @JvmField val LessThanSlashToken: IElementType = CSharpTokenType("LessThanSlashToken")
    /** 8234 */ @JvmField val XmlCommentStartToken: IElementType = CSharpTokenType("XmlCommentStartToken")
    /** 8235 */ @JvmField val XmlCommentEndToken: IElementType = CSharpTokenType("XmlCommentEndToken")
    /** 8236 */ @JvmField val XmlCDataStartToken: IElementType = CSharpTokenType("XmlCDataStartToken")
    /** 8237 */ @JvmField val XmlCDataEndToken: IElementType = CSharpTokenType("XmlCDataEndToken")
    /** 8238 */ @JvmField val XmlProcessingInstructionStartToken: IElementType = CSharpTokenType("XmlProcessingInstructionStartToken")
    /** 8239 */ @JvmField val XmlProcessingInstructionEndToken: IElementType = CSharpTokenType("XmlProcessingInstructionEndToken")
    /** 8260 */ @JvmField val BarBarToken: IElementType = CSharpTokenType("BarBarToken")
    /** 8261 */ @JvmField val AmpersandAmpersandToken: IElementType = CSharpTokenType("AmpersandAmpersandToken")
    /** 8262 */ @JvmField val MinusMinusToken: IElementType = CSharpTokenType("MinusMinusToken")
    /** 8263 */ @JvmField val PlusPlusToken: IElementType = CSharpTokenType("PlusPlusToken")
    /** 8264 */ @JvmField val ColonColonToken: IElementType = CSharpTokenType("ColonColonToken")
    /** 8265 */ @JvmField val QuestionQuestionToken: IElementType = CSharpTokenType("QuestionQuestionToken")
    /** 8266 */ @JvmField val MinusGreaterThanToken: IElementType = CSharpTokenType("MinusGreaterThanToken")
    /** 8267 */ @JvmField val ExclamationEqualsToken: IElementType = CSharpTokenType("ExclamationEqualsToken")
    /** 8268 */ @JvmField val EqualsEqualsToken: IElementType = CSharpTokenType("EqualsEqualsToken")
    /** 8269 */ @JvmField val EqualsGreaterThanToken: IElementType = CSharpTokenType("EqualsGreaterThanToken")
    /** 8270 */ @JvmField val LessThanEqualsToken: IElementType = CSharpTokenType("LessThanEqualsToken")
    /** 8271 */ @JvmField val LessThanLessThanToken: IElementType = CSharpTokenType("LessThanLessThanToken")
    /** 8272 */ @JvmField val LessThanLessThanEqualsToken: IElementType = CSharpTokenType("LessThanLessThanEqualsToken")
    /** 8273 */ @JvmField val GreaterThanEqualsToken: IElementType = CSharpTokenType("GreaterThanEqualsToken")
    /** 8274 */ @JvmField val GreaterThanGreaterThanToken: IElementType = CSharpTokenType("GreaterThanGreaterThanToken")
    /** 8275 */ @JvmField val GreaterThanGreaterThanEqualsToken: IElementType = CSharpTokenType("GreaterThanGreaterThanEqualsToken")
    /** 8276 */ @JvmField val SlashEqualsToken: IElementType = CSharpTokenType("SlashEqualsToken")
    /** 8277 */ @JvmField val AsteriskEqualsToken: IElementType = CSharpTokenType("AsteriskEqualsToken")
    /** 8278 */ @JvmField val BarEqualsToken: IElementType = CSharpTokenType("BarEqualsToken")
    /** 8279 */ @JvmField val AmpersandEqualsToken: IElementType = CSharpTokenType("AmpersandEqualsToken")
    /** 8280 */ @JvmField val PlusEqualsToken: IElementType = CSharpTokenType("PlusEqualsToken")
    /** 8281 */ @JvmField val MinusEqualsToken: IElementType = CSharpTokenType("MinusEqualsToken")
    /** 8282 */ @JvmField val CaretEqualsToken: IElementType = CSharpTokenType("CaretEqualsToken")
    /** 8283 */ @JvmField val PercentEqualsToken: IElementType = CSharpTokenType("PercentEqualsToken")
    /** 8284 */ @JvmField val QuestionQuestionEqualsToken: IElementType = CSharpTokenType("QuestionQuestionEqualsToken")
    /** 8286 */ @JvmField val GreaterThanGreaterThanGreaterThanToken: IElementType = CSharpTokenType("GreaterThanGreaterThanGreaterThanToken")
    /** 8287 */ @JvmField val GreaterThanGreaterThanGreaterThanEqualsToken: IElementType = CSharpTokenType("GreaterThanGreaterThanGreaterThanEqualsToken")
    /** 8304 */ @JvmField val BoolKeyword: IElementType = CSharpTokenType("BoolKeyword")
    /** 8305 */ @JvmField val ByteKeyword: IElementType = CSharpTokenType("ByteKeyword")
    /** 8306 */ @JvmField val SByteKeyword: IElementType = CSharpTokenType("SByteKeyword")
    /** 8307 */ @JvmField val ShortKeyword: IElementType = CSharpTokenType("ShortKeyword")
    /** 8308 */ @JvmField val UShortKeyword: IElementType = CSharpTokenType("UShortKeyword")
    /** 8309 */ @JvmField val IntKeyword: IElementType = CSharpTokenType("IntKeyword")
    /** 8310 */ @JvmField val UIntKeyword: IElementType = CSharpTokenType("UIntKeyword")
    /** 8311 */ @JvmField val LongKeyword: IElementType = CSharpTokenType("LongKeyword")
    /** 8312 */ @JvmField val ULongKeyword: IElementType = CSharpTokenType("ULongKeyword")
    /** 8313 */ @JvmField val DoubleKeyword: IElementType = CSharpTokenType("DoubleKeyword")
    /** 8314 */ @JvmField val FloatKeyword: IElementType = CSharpTokenType("FloatKeyword")
    /** 8315 */ @JvmField val DecimalKeyword: IElementType = CSharpTokenType("DecimalKeyword")
    /** 8316 */ @JvmField val StringKeyword: IElementType = CSharpTokenType("StringKeyword")
    /** 8317 */ @JvmField val CharKeyword: IElementType = CSharpTokenType("CharKeyword")
    /** 8318 */ @JvmField val VoidKeyword: IElementType = CSharpTokenType("VoidKeyword")
    /** 8319 */ @JvmField val ObjectKeyword: IElementType = CSharpTokenType("ObjectKeyword")
    /** 8320 */ @JvmField val TypeOfKeyword: IElementType = CSharpTokenType("TypeOfKeyword")
    /** 8321 */ @JvmField val SizeOfKeyword: IElementType = CSharpTokenType("SizeOfKeyword")
    /** 8322 */ @JvmField val NullKeyword: IElementType = CSharpTokenType("NullKeyword")
    /** 8323 */ @JvmField val TrueKeyword: IElementType = CSharpTokenType("TrueKeyword")
    /** 8324 */ @JvmField val FalseKeyword: IElementType = CSharpTokenType("FalseKeyword")
    /** 8325 */ @JvmField val IfKeyword: IElementType = CSharpTokenType("IfKeyword")
    /** 8326 */ @JvmField val ElseKeyword: IElementType = CSharpTokenType("ElseKeyword")
    /** 8327 */ @JvmField val WhileKeyword: IElementType = CSharpTokenType("WhileKeyword")
    /** 8328 */ @JvmField val ForKeyword: IElementType = CSharpTokenType("ForKeyword")
    /** 8329 */ @JvmField val ForEachKeyword: IElementType = CSharpTokenType("ForEachKeyword")
    /** 8330 */ @JvmField val DoKeyword: IElementType = CSharpTokenType("DoKeyword")
    /** 8331 */ @JvmField val SwitchKeyword: IElementType = CSharpTokenType("SwitchKeyword")
    /** 8332 */ @JvmField val CaseKeyword: IElementType = CSharpTokenType("CaseKeyword")
    /** 8333 */ @JvmField val DefaultKeyword: IElementType = CSharpTokenType("DefaultKeyword")
    /** 8334 */ @JvmField val TryKeyword: IElementType = CSharpTokenType("TryKeyword")
    /** 8335 */ @JvmField val CatchKeyword: IElementType = CSharpTokenType("CatchKeyword")
    /** 8336 */ @JvmField val FinallyKeyword: IElementType = CSharpTokenType("FinallyKeyword")
    /** 8337 */ @JvmField val LockKeyword: IElementType = CSharpTokenType("LockKeyword")
    /** 8338 */ @JvmField val GotoKeyword: IElementType = CSharpTokenType("GotoKeyword")
    /** 8339 */ @JvmField val BreakKeyword: IElementType = CSharpTokenType("BreakKeyword")
    /** 8340 */ @JvmField val ContinueKeyword: IElementType = CSharpTokenType("ContinueKeyword")
    /** 8341 */ @JvmField val ReturnKeyword: IElementType = CSharpTokenType("ReturnKeyword")
    /** 8342 */ @JvmField val ThrowKeyword: IElementType = CSharpTokenType("ThrowKeyword")
    /** 8343 */ @JvmField val PublicKeyword: IElementType = CSharpTokenType("PublicKeyword")
    /** 8344 */ @JvmField val PrivateKeyword: IElementType = CSharpTokenType("PrivateKeyword")
    /** 8345 */ @JvmField val InternalKeyword: IElementType = CSharpTokenType("InternalKeyword")
    /** 8346 */ @JvmField val ProtectedKeyword: IElementType = CSharpTokenType("ProtectedKeyword")
    /** 8347 */ @JvmField val StaticKeyword: IElementType = CSharpTokenType("StaticKeyword")
    /** 8348 */ @JvmField val ReadOnlyKeyword: IElementType = CSharpTokenType("ReadOnlyKeyword")
    /** 8349 */ @JvmField val SealedKeyword: IElementType = CSharpTokenType("SealedKeyword")
    /** 8350 */ @JvmField val ConstKeyword: IElementType = CSharpTokenType("ConstKeyword")
    /** 8351 */ @JvmField val FixedKeyword: IElementType = CSharpTokenType("FixedKeyword")
    /** 8352 */ @JvmField val StackAllocKeyword: IElementType = CSharpTokenType("StackAllocKeyword")
    /** 8353 */ @JvmField val VolatileKeyword: IElementType = CSharpTokenType("VolatileKeyword")
    /** 8354 */ @JvmField val NewKeyword: IElementType = CSharpTokenType("NewKeyword")
    /** 8355 */ @JvmField val OverrideKeyword: IElementType = CSharpTokenType("OverrideKeyword")
    /** 8356 */ @JvmField val AbstractKeyword: IElementType = CSharpTokenType("AbstractKeyword")
    /** 8357 */ @JvmField val VirtualKeyword: IElementType = CSharpTokenType("VirtualKeyword")
    /** 8358 */ @JvmField val EventKeyword: IElementType = CSharpTokenType("EventKeyword")
    /** 8359 */ @JvmField val ExternKeyword: IElementType = CSharpTokenType("ExternKeyword")
    /** 8360 */ @JvmField val RefKeyword: IElementType = CSharpTokenType("RefKeyword")
    /** 8361 */ @JvmField val OutKeyword: IElementType = CSharpTokenType("OutKeyword")
    /** 8362 */ @JvmField val InKeyword: IElementType = CSharpTokenType("InKeyword")
    /** 8363 */ @JvmField val IsKeyword: IElementType = CSharpTokenType("IsKeyword")
    /** 8364 */ @JvmField val AsKeyword: IElementType = CSharpTokenType("AsKeyword")
    /** 8365 */ @JvmField val ParamsKeyword: IElementType = CSharpTokenType("ParamsKeyword")
    /** 8366 */ @JvmField val ArgListKeyword: IElementType = CSharpTokenType("ArgListKeyword")
    /** 8367 */ @JvmField val MakeRefKeyword: IElementType = CSharpTokenType("MakeRefKeyword")
    /** 8368 */ @JvmField val RefTypeKeyword: IElementType = CSharpTokenType("RefTypeKeyword")
    /** 8369 */ @JvmField val RefValueKeyword: IElementType = CSharpTokenType("RefValueKeyword")
    /** 8370 */ @JvmField val ThisKeyword: IElementType = CSharpTokenType("ThisKeyword")
    /** 8371 */ @JvmField val BaseKeyword: IElementType = CSharpTokenType("BaseKeyword")
    /** 8372 */ @JvmField val NamespaceKeyword: IElementType = CSharpTokenType("NamespaceKeyword")
    /** 8373 */ @JvmField val UsingKeyword: IElementType = CSharpTokenType("UsingKeyword")
    /** 8374 */ @JvmField val ClassKeyword: IElementType = CSharpTokenType("ClassKeyword")
    /** 8375 */ @JvmField val StructKeyword: IElementType = CSharpTokenType("StructKeyword")
    /** 8376 */ @JvmField val InterfaceKeyword: IElementType = CSharpTokenType("InterfaceKeyword")
    /** 8377 */ @JvmField val EnumKeyword: IElementType = CSharpTokenType("EnumKeyword")
    /** 8378 */ @JvmField val DelegateKeyword: IElementType = CSharpTokenType("DelegateKeyword")
    /** 8379 */ @JvmField val CheckedKeyword: IElementType = CSharpTokenType("CheckedKeyword")
    /** 8380 */ @JvmField val UncheckedKeyword: IElementType = CSharpTokenType("UncheckedKeyword")
    /** 8381 */ @JvmField val UnsafeKeyword: IElementType = CSharpTokenType("UnsafeKeyword")
    /** 8382 */ @JvmField val OperatorKeyword: IElementType = CSharpTokenType("OperatorKeyword")
    /** 8383 */ @JvmField val ExplicitKeyword: IElementType = CSharpTokenType("ExplicitKeyword")
    /** 8384 */ @JvmField val ImplicitKeyword: IElementType = CSharpTokenType("ImplicitKeyword")
    /** 8405 */ @JvmField val YieldKeyword: IElementType = CSharpTokenType("YieldKeyword")
    /** 8406 */ @JvmField val PartialKeyword: IElementType = CSharpTokenType("PartialKeyword")
    /** 8407 */ @JvmField val AliasKeyword: IElementType = CSharpTokenType("AliasKeyword")
    /** 8408 */ @JvmField val GlobalKeyword: IElementType = CSharpTokenType("GlobalKeyword")
    /** 8409 */ @JvmField val AssemblyKeyword: IElementType = CSharpTokenType("AssemblyKeyword")
    /** 8410 */ @JvmField val ModuleKeyword: IElementType = CSharpTokenType("ModuleKeyword")
    /** 8411 */ @JvmField val TypeKeyword: IElementType = CSharpTokenType("TypeKeyword")
    /** 8412 */ @JvmField val FieldKeyword: IElementType = CSharpTokenType("FieldKeyword")
    /** 8413 */ @JvmField val MethodKeyword: IElementType = CSharpTokenType("MethodKeyword")
    /** 8414 */ @JvmField val ParamKeyword: IElementType = CSharpTokenType("ParamKeyword")
    /** 8415 */ @JvmField val PropertyKeyword: IElementType = CSharpTokenType("PropertyKeyword")
    /** 8416 */ @JvmField val TypeVarKeyword: IElementType = CSharpTokenType("TypeVarKeyword")
    /** 8417 */ @JvmField val GetKeyword: IElementType = CSharpTokenType("GetKeyword")
    /** 8418 */ @JvmField val SetKeyword: IElementType = CSharpTokenType("SetKeyword")
    /** 8419 */ @JvmField val AddKeyword: IElementType = CSharpTokenType("AddKeyword")
    /** 8420 */ @JvmField val RemoveKeyword: IElementType = CSharpTokenType("RemoveKeyword")
    /** 8421 */ @JvmField val WhereKeyword: IElementType = CSharpTokenType("WhereKeyword")
    /** 8422 */ @JvmField val FromKeyword: IElementType = CSharpTokenType("FromKeyword")
    /** 8423 */ @JvmField val GroupKeyword: IElementType = CSharpTokenType("GroupKeyword")
    /** 8424 */ @JvmField val JoinKeyword: IElementType = CSharpTokenType("JoinKeyword")
    /** 8425 */ @JvmField val IntoKeyword: IElementType = CSharpTokenType("IntoKeyword")
    /** 8426 */ @JvmField val LetKeyword: IElementType = CSharpTokenType("LetKeyword")
    /** 8427 */ @JvmField val ByKeyword: IElementType = CSharpTokenType("ByKeyword")
    /** 8428 */ @JvmField val SelectKeyword: IElementType = CSharpTokenType("SelectKeyword")
    /** 8429 */ @JvmField val OrderByKeyword: IElementType = CSharpTokenType("OrderByKeyword")
    /** 8430 */ @JvmField val OnKeyword: IElementType = CSharpTokenType("OnKeyword")
    /** 8431 */ @JvmField val EqualsKeyword: IElementType = CSharpTokenType("EqualsKeyword")
    /** 8432 */ @JvmField val AscendingKeyword: IElementType = CSharpTokenType("AscendingKeyword")
    /** 8433 */ @JvmField val DescendingKeyword: IElementType = CSharpTokenType("DescendingKeyword")
    /** 8434 */ @JvmField val NameOfKeyword: IElementType = CSharpTokenType("NameOfKeyword")
    /** 8435 */ @JvmField val AsyncKeyword: IElementType = CSharpTokenType("AsyncKeyword")
    /** 8436 */ @JvmField val AwaitKeyword: IElementType = CSharpTokenType("AwaitKeyword")
    /** 8437 */ @JvmField val WhenKeyword: IElementType = CSharpTokenType("WhenKeyword")
    /** 8438 */ @JvmField val OrKeyword: IElementType = CSharpTokenType("OrKeyword")
    /** 8439 */ @JvmField val AndKeyword: IElementType = CSharpTokenType("AndKeyword")
    /** 8440 */ @JvmField val NotKeyword: IElementType = CSharpTokenType("NotKeyword")
    /** 8442 */ @JvmField val WithKeyword: IElementType = CSharpTokenType("WithKeyword")
    /** 8443 */ @JvmField val InitKeyword: IElementType = CSharpTokenType("InitKeyword")
    /** 8444 */ @JvmField val RecordKeyword: IElementType = CSharpTokenType("RecordKeyword")
    /** 8445 */ @JvmField val ManagedKeyword: IElementType = CSharpTokenType("ManagedKeyword")
    /** 8446 */ @JvmField val UnmanagedKeyword: IElementType = CSharpTokenType("UnmanagedKeyword")
    /** 8447 */ @JvmField val RequiredKeyword: IElementType = CSharpTokenType("RequiredKeyword")
    /** 8448 */ @JvmField val ScopedKeyword: IElementType = CSharpTokenType("ScopedKeyword")
    /** 8449 */ @JvmField val FileKeyword: IElementType = CSharpTokenType("FileKeyword")
    /** 8450 */ @JvmField val AllowsKeyword: IElementType = CSharpTokenType("AllowsKeyword")
    /** 8451 */ @JvmField val ExtensionKeyword: IElementType = CSharpTokenType("ExtensionKeyword")
    /** 8452 */ @JvmField val UnionKeyword: IElementType = CSharpTokenType("UnionKeyword")
    /** 8453 */ @JvmField val ClosedKeyword: IElementType = CSharpTokenType("ClosedKeyword")
    /** 8454 */ @JvmField val SafeKeyword: IElementType = CSharpTokenType("SafeKeyword")
    /** 8467 */ @JvmField val ElifKeyword: IElementType = CSharpTokenType("ElifKeyword")
    /** 8468 */ @JvmField val EndIfKeyword: IElementType = CSharpTokenType("EndIfKeyword")
    /** 8469 */ @JvmField val RegionKeyword: IElementType = CSharpTokenType("RegionKeyword")
    /** 8470 */ @JvmField val EndRegionKeyword: IElementType = CSharpTokenType("EndRegionKeyword")
    /** 8471 */ @JvmField val DefineKeyword: IElementType = CSharpTokenType("DefineKeyword")
    /** 8472 */ @JvmField val UndefKeyword: IElementType = CSharpTokenType("UndefKeyword")
    /** 8473 */ @JvmField val WarningKeyword: IElementType = CSharpTokenType("WarningKeyword")
    /** 8474 */ @JvmField val ErrorKeyword: IElementType = CSharpTokenType("ErrorKeyword")
    /** 8475 */ @JvmField val LineKeyword: IElementType = CSharpTokenType("LineKeyword")
    /** 8476 */ @JvmField val PragmaKeyword: IElementType = CSharpTokenType("PragmaKeyword")
    /** 8477 */ @JvmField val HiddenKeyword: IElementType = CSharpTokenType("HiddenKeyword")
    /** 8478 */ @JvmField val ChecksumKeyword: IElementType = CSharpTokenType("ChecksumKeyword")
    /** 8479 */ @JvmField val DisableKeyword: IElementType = CSharpTokenType("DisableKeyword")
    /** 8480 */ @JvmField val RestoreKeyword: IElementType = CSharpTokenType("RestoreKeyword")
    /** 8481 */ @JvmField val ReferenceKeyword: IElementType = CSharpTokenType("ReferenceKeyword")
    /** 8482 */ @JvmField val InterpolatedStringStartToken: IElementType = CSharpTokenType("InterpolatedStringStartToken")
    /** 8483 */ @JvmField val InterpolatedStringEndToken: IElementType = CSharpTokenType("InterpolatedStringEndToken")
    /** 8484 */ @JvmField val InterpolatedVerbatimStringStartToken: IElementType = CSharpTokenType("InterpolatedVerbatimStringStartToken")
    /** 8485 */ @JvmField val LoadKeyword: IElementType = CSharpTokenType("LoadKeyword")
    /** 8486 */ @JvmField val NullableKeyword: IElementType = CSharpTokenType("NullableKeyword")
    /** 8487 */ @JvmField val EnableKeyword: IElementType = CSharpTokenType("EnableKeyword")
    /** 8488 */ @JvmField val WarningsKeyword: IElementType = CSharpTokenType("WarningsKeyword")
    /** 8489 */ @JvmField val AnnotationsKeyword: IElementType = CSharpTokenType("AnnotationsKeyword")
    /** 8490 */ @JvmField val VarKeyword: IElementType = CSharpTokenType("VarKeyword")
    /** 8491 */ @JvmField val UnderscoreToken: IElementType = CSharpTokenType("UnderscoreToken")
    /** 8492 */ @JvmField val OmittedTypeArgumentToken: IElementType = CSharpTokenType("OmittedTypeArgumentToken")
    /** 8493 */ @JvmField val OmittedArraySizeExpressionToken: IElementType = CSharpTokenType("OmittedArraySizeExpressionToken")
    /** 8494 */ @JvmField val EndOfDirectiveToken: IElementType = CSharpTokenType("EndOfDirectiveToken")
    /** 8495 */ @JvmField val EndOfDocumentationCommentToken: IElementType = CSharpTokenType("EndOfDocumentationCommentToken")
    /** 8496 */ @JvmField val EndOfFileToken: IElementType = CSharpTokenType("EndOfFileToken")
    /** 8507 */ @JvmField val BadToken: IElementType = CSharpTokenType("BadToken")
    /** 8508 */ @JvmField val IdentifierToken: IElementType = CSharpTokenType("IdentifierToken")
    /** 8509 */ @JvmField val NumericLiteralToken: IElementType = CSharpTokenType("NumericLiteralToken")
    /** 8510 */ @JvmField val CharacterLiteralToken: IElementType = CSharpTokenType("CharacterLiteralToken")
    /** 8511 */ @JvmField val StringLiteralToken: IElementType = CSharpTokenType("StringLiteralToken")
    /** 8512 */ @JvmField val XmlEntityLiteralToken: IElementType = CSharpTokenType("XmlEntityLiteralToken")
    /** 8513 */ @JvmField val XmlTextLiteralToken: IElementType = CSharpTokenType("XmlTextLiteralToken")
    /** 8514 */ @JvmField val XmlTextLiteralNewLineToken: IElementType = CSharpTokenType("XmlTextLiteralNewLineToken")
    /** 8515 */ @JvmField val InterpolatedStringToken: IElementType = CSharpTokenType("InterpolatedStringToken")
    /** 8517 */ @JvmField val InterpolatedStringTextToken: IElementType = CSharpTokenType("InterpolatedStringTextToken")
    /** 8518 */ @JvmField val SingleLineRawStringLiteralToken: IElementType = CSharpTokenType("SingleLineRawStringLiteralToken")
    /** 8519 */ @JvmField val MultiLineRawStringLiteralToken: IElementType = CSharpTokenType("MultiLineRawStringLiteralToken")
    /** 8520 */ @JvmField val Utf8StringLiteralToken: IElementType = CSharpTokenType("Utf8StringLiteralToken")
    /** 8521 */ @JvmField val Utf8SingleLineRawStringLiteralToken: IElementType = CSharpTokenType("Utf8SingleLineRawStringLiteralToken")
    /** 8522 */ @JvmField val Utf8MultiLineRawStringLiteralToken: IElementType = CSharpTokenType("Utf8MultiLineRawStringLiteralToken")
    /** 8523 */ @JvmField val RazorContentToken: IElementType = CSharpTokenType("RazorContentToken")
    /** 8539 */ @JvmField val EndOfLineTrivia: IElementType = CSharpTokenType("EndOfLineTrivia")
    /** 8540 */ @JvmField val WhitespaceTrivia: IElementType = CSharpTokenType("WhitespaceTrivia")
    /** 8541 */ @JvmField val SingleLineCommentTrivia: IElementType = CSharpTokenType("SingleLineCommentTrivia")
    /** 8542 */ @JvmField val MultiLineCommentTrivia: IElementType = CSharpTokenType("MultiLineCommentTrivia")
    /** 8543 */ @JvmField val DocumentationCommentExteriorTrivia: IElementType = CSharpTokenType("DocumentationCommentExteriorTrivia")
    /** 8544 */ @JvmField val SingleLineDocumentationCommentTrivia: IElementType = CSharpDocCommentElementType("SingleLineDocumentationCommentTrivia")
    /** 8545 */ @JvmField val MultiLineDocumentationCommentTrivia: IElementType = CSharpDocCommentElementType("MultiLineDocumentationCommentTrivia")
    /** 8546 */ @JvmField val DisabledTextTrivia: IElementType = CSharpTokenType("DisabledTextTrivia")
    /** 8547 */ @JvmField val PreprocessingMessageTrivia: IElementType = CSharpTokenType("PreprocessingMessageTrivia")
    /** 8548 */ @JvmField val IfDirectiveTrivia: IElementType = CSharpTokenType("IfDirectiveTrivia")
    /** 8549 */ @JvmField val ElifDirectiveTrivia: IElementType = CSharpTokenType("ElifDirectiveTrivia")
    /** 8550 */ @JvmField val ElseDirectiveTrivia: IElementType = CSharpTokenType("ElseDirectiveTrivia")
    /** 8551 */ @JvmField val EndIfDirectiveTrivia: IElementType = CSharpTokenType("EndIfDirectiveTrivia")
    /** 8552 */ @JvmField val RegionDirectiveTrivia: IElementType = CSharpTokenType("RegionDirectiveTrivia")
    /** 8553 */ @JvmField val EndRegionDirectiveTrivia: IElementType = CSharpTokenType("EndRegionDirectiveTrivia")
    /** 8554 */ @JvmField val DefineDirectiveTrivia: IElementType = CSharpTokenType("DefineDirectiveTrivia")
    /** 8555 */ @JvmField val UndefDirectiveTrivia: IElementType = CSharpTokenType("UndefDirectiveTrivia")
    /** 8556 */ @JvmField val ErrorDirectiveTrivia: IElementType = CSharpTokenType("ErrorDirectiveTrivia")
    /** 8557 */ @JvmField val WarningDirectiveTrivia: IElementType = CSharpTokenType("WarningDirectiveTrivia")
    /** 8558 */ @JvmField val LineDirectiveTrivia: IElementType = CSharpTokenType("LineDirectiveTrivia")
    /** 8559 */ @JvmField val PragmaWarningDirectiveTrivia: IElementType = CSharpTokenType("PragmaWarningDirectiveTrivia")
    /** 8560 */ @JvmField val PragmaChecksumDirectiveTrivia: IElementType = CSharpTokenType("PragmaChecksumDirectiveTrivia")
    /** 8561 */ @JvmField val ReferenceDirectiveTrivia: IElementType = CSharpTokenType("ReferenceDirectiveTrivia")
    /** 8562 */ @JvmField val BadDirectiveTrivia: IElementType = CSharpTokenType("BadDirectiveTrivia")
    /** 8563 */ @JvmField val SkippedTokensTrivia: IElementType = CSharpTokenType("SkippedTokensTrivia")
    /** 8564 */ @JvmField val ConflictMarkerTrivia: IElementType = CSharpTokenType("ConflictMarkerTrivia")
    /** 8574 */ @JvmField val XmlElement: IElementType = CSharpElementType("XmlElement")
    /** 8575 */ @JvmField val XmlElementStartTag: IElementType = CSharpElementType("XmlElementStartTag")
    /** 8576 */ @JvmField val XmlElementEndTag: IElementType = CSharpElementType("XmlElementEndTag")
    /** 8577 */ @JvmField val XmlEmptyElement: IElementType = CSharpElementType("XmlEmptyElement")
    /** 8578 */ @JvmField val XmlTextAttribute: IElementType = CSharpElementType("XmlTextAttribute")
    /** 8579 */ @JvmField val XmlCrefAttribute: IElementType = CSharpElementType("XmlCrefAttribute")
    /** 8580 */ @JvmField val XmlNameAttribute: IElementType = CSharpElementType("XmlNameAttribute")
    /** 8581 */ @JvmField val XmlName: IElementType = CSharpElementType("XmlName")
    /** 8582 */ @JvmField val XmlPrefix: IElementType = CSharpElementType("XmlPrefix")
    /** 8583 */ @JvmField val XmlText: IElementType = CSharpElementType("XmlText")
    /** 8584 */ @JvmField val XmlCDataSection: IElementType = CSharpElementType("XmlCDataSection")
    /** 8585 */ @JvmField val XmlComment: IElementType = CSharpElementType("XmlComment")
    /** 8586 */ @JvmField val XmlProcessingInstruction: IElementType = CSharpElementType("XmlProcessingInstruction")
    /** 8597 */ @JvmField val TypeCref: IElementType = CSharpElementType("TypeCref")
    /** 8598 */ @JvmField val QualifiedCref: IElementType = CSharpElementType("QualifiedCref")
    /** 8599 */ @JvmField val NameMemberCref: IElementType = CSharpElementType("NameMemberCref")
    /** 8600 */ @JvmField val IndexerMemberCref: IElementType = CSharpElementType("IndexerMemberCref")
    /** 8601 */ @JvmField val OperatorMemberCref: IElementType = CSharpElementType("OperatorMemberCref")
    /** 8602 */ @JvmField val ConversionOperatorMemberCref: IElementType = CSharpElementType("ConversionOperatorMemberCref")
    /** 8603 */ @JvmField val CrefParameterList: IElementType = CSharpElementType("CrefParameterList")
    /** 8604 */ @JvmField val CrefBracketedParameterList: IElementType = CSharpElementType("CrefBracketedParameterList")
    /** 8605 */ @JvmField val CrefParameter: IElementType = CSharpElementType("CrefParameter")
    /** 8607 */ @JvmField val ExtensionMemberCref: IElementType = CSharpElementType("ExtensionMemberCref")
    /** 8616 */ @JvmField val IdentifierName: IElementType = CSharpElementType("IdentifierName")
    /** 8617 */ @JvmField val QualifiedName: IElementType = CSharpElementType("QualifiedName")
    /** 8618 */ @JvmField val GenericName: IElementType = CSharpElementType("GenericName")
    /** 8619 */ @JvmField val TypeArgumentList: IElementType = CSharpElementType("TypeArgumentList")
    /** 8620 */ @JvmField val AliasQualifiedName: IElementType = CSharpElementType("AliasQualifiedName")
    /** 8621 */ @JvmField val PredefinedType: IElementType = CSharpElementType("PredefinedType")
    /** 8622 */ @JvmField val ArrayType: IElementType = CSharpElementType("ArrayType")
    /** 8623 */ @JvmField val ArrayRankSpecifier: IElementType = CSharpElementType("ArrayRankSpecifier")
    /** 8624 */ @JvmField val PointerType: IElementType = CSharpElementType("PointerType")
    /** 8625 */ @JvmField val NullableType: IElementType = CSharpElementType("NullableType")
    /** 8626 */ @JvmField val OmittedTypeArgument: IElementType = CSharpElementType("OmittedTypeArgument")
    /** 8632 */ @JvmField val ParenthesizedExpression: IElementType = CSharpElementType("ParenthesizedExpression")
    /** 8633 */ @JvmField val ConditionalExpression: IElementType = CSharpElementType("ConditionalExpression")
    /** 8634 */ @JvmField val InvocationExpression: IElementType = CSharpElementType("InvocationExpression")
    /** 8635 */ @JvmField val ElementAccessExpression: IElementType = CSharpElementType("ElementAccessExpression")
    /** 8636 */ @JvmField val ArgumentList: IElementType = CSharpElementType("ArgumentList")
    /** 8637 */ @JvmField val BracketedArgumentList: IElementType = CSharpElementType("BracketedArgumentList")
    /** 8638 */ @JvmField val Argument: IElementType = CSharpElementType("Argument")
    /** 8639 */ @JvmField val NameColon: IElementType = CSharpElementType("NameColon")
    /** 8640 */ @JvmField val CastExpression: IElementType = CSharpElementType("CastExpression")
    /** 8641 */ @JvmField val AnonymousMethodExpression: IElementType = CSharpElementType("AnonymousMethodExpression")
    /** 8642 */ @JvmField val SimpleLambdaExpression: IElementType = CSharpElementType("SimpleLambdaExpression")
    /** 8643 */ @JvmField val ParenthesizedLambdaExpression: IElementType = CSharpElementType("ParenthesizedLambdaExpression")
    /** 8644 */ @JvmField val ObjectInitializerExpression: IElementType = CSharpElementType("ObjectInitializerExpression")
    /** 8645 */ @JvmField val CollectionInitializerExpression: IElementType = CSharpElementType("CollectionInitializerExpression")
    /** 8646 */ @JvmField val ArrayInitializerExpression: IElementType = CSharpElementType("ArrayInitializerExpression")
    /** 8647 */ @JvmField val AnonymousObjectMemberDeclarator: IElementType = CSharpElementType("AnonymousObjectMemberDeclarator")
    /** 8648 */ @JvmField val ComplexElementInitializerExpression: IElementType = CSharpElementType("ComplexElementInitializerExpression")
    /** 8649 */ @JvmField val ObjectCreationExpression: IElementType = CSharpElementType("ObjectCreationExpression")
    /** 8650 */ @JvmField val AnonymousObjectCreationExpression: IElementType = CSharpElementType("AnonymousObjectCreationExpression")
    /** 8651 */ @JvmField val ArrayCreationExpression: IElementType = CSharpElementType("ArrayCreationExpression")
    /** 8652 */ @JvmField val ImplicitArrayCreationExpression: IElementType = CSharpElementType("ImplicitArrayCreationExpression")
    /** 8653 */ @JvmField val StackAllocArrayCreationExpression: IElementType = CSharpElementType("StackAllocArrayCreationExpression")
    /** 8654 */ @JvmField val OmittedArraySizeExpression: IElementType = CSharpElementType("OmittedArraySizeExpression")
    /** 8655 */ @JvmField val InterpolatedStringExpression: IElementType = CSharpElementType("InterpolatedStringExpression")
    /** 8656 */ @JvmField val ImplicitElementAccess: IElementType = CSharpElementType("ImplicitElementAccess")
    /** 8657 */ @JvmField val IsPatternExpression: IElementType = CSharpElementType("IsPatternExpression")
    /** 8658 */ @JvmField val RangeExpression: IElementType = CSharpElementType("RangeExpression")
    /** 8659 */ @JvmField val ImplicitObjectCreationExpression: IElementType = CSharpElementType("ImplicitObjectCreationExpression")
    /** 8668 */ @JvmField val AddExpression: IElementType = CSharpElementType("AddExpression")
    /** 8669 */ @JvmField val SubtractExpression: IElementType = CSharpElementType("SubtractExpression")
    /** 8670 */ @JvmField val MultiplyExpression: IElementType = CSharpElementType("MultiplyExpression")
    /** 8671 */ @JvmField val DivideExpression: IElementType = CSharpElementType("DivideExpression")
    /** 8672 */ @JvmField val ModuloExpression: IElementType = CSharpElementType("ModuloExpression")
    /** 8673 */ @JvmField val LeftShiftExpression: IElementType = CSharpElementType("LeftShiftExpression")
    /** 8674 */ @JvmField val RightShiftExpression: IElementType = CSharpElementType("RightShiftExpression")
    /** 8675 */ @JvmField val LogicalOrExpression: IElementType = CSharpElementType("LogicalOrExpression")
    /** 8676 */ @JvmField val LogicalAndExpression: IElementType = CSharpElementType("LogicalAndExpression")
    /** 8677 */ @JvmField val BitwiseOrExpression: IElementType = CSharpElementType("BitwiseOrExpression")
    /** 8678 */ @JvmField val BitwiseAndExpression: IElementType = CSharpElementType("BitwiseAndExpression")
    /** 8679 */ @JvmField val ExclusiveOrExpression: IElementType = CSharpElementType("ExclusiveOrExpression")
    /** 8680 */ @JvmField val EqualsExpression: IElementType = CSharpElementType("EqualsExpression")
    /** 8681 */ @JvmField val NotEqualsExpression: IElementType = CSharpElementType("NotEqualsExpression")
    /** 8682 */ @JvmField val LessThanExpression: IElementType = CSharpElementType("LessThanExpression")
    /** 8683 */ @JvmField val LessThanOrEqualExpression: IElementType = CSharpElementType("LessThanOrEqualExpression")
    /** 8684 */ @JvmField val GreaterThanExpression: IElementType = CSharpElementType("GreaterThanExpression")
    /** 8685 */ @JvmField val GreaterThanOrEqualExpression: IElementType = CSharpElementType("GreaterThanOrEqualExpression")
    /** 8686 */ @JvmField val IsExpression: IElementType = CSharpElementType("IsExpression")
    /** 8687 */ @JvmField val AsExpression: IElementType = CSharpElementType("AsExpression")
    /** 8688 */ @JvmField val CoalesceExpression: IElementType = CSharpElementType("CoalesceExpression")
    /** 8689 */ @JvmField val SimpleMemberAccessExpression: IElementType = CSharpElementType("SimpleMemberAccessExpression")
    /** 8690 */ @JvmField val PointerMemberAccessExpression: IElementType = CSharpElementType("PointerMemberAccessExpression")
    /** 8691 */ @JvmField val ConditionalAccessExpression: IElementType = CSharpElementType("ConditionalAccessExpression")
    /** 8692 */ @JvmField val UnsignedRightShiftExpression: IElementType = CSharpElementType("UnsignedRightShiftExpression")
    /** 8707 */ @JvmField val MemberBindingExpression: IElementType = CSharpElementType("MemberBindingExpression")
    /** 8708 */ @JvmField val ElementBindingExpression: IElementType = CSharpElementType("ElementBindingExpression")
    /** 8714 */ @JvmField val SimpleAssignmentExpression: IElementType = CSharpElementType("SimpleAssignmentExpression")
    /** 8715 */ @JvmField val AddAssignmentExpression: IElementType = CSharpElementType("AddAssignmentExpression")
    /** 8716 */ @JvmField val SubtractAssignmentExpression: IElementType = CSharpElementType("SubtractAssignmentExpression")
    /** 8717 */ @JvmField val MultiplyAssignmentExpression: IElementType = CSharpElementType("MultiplyAssignmentExpression")
    /** 8718 */ @JvmField val DivideAssignmentExpression: IElementType = CSharpElementType("DivideAssignmentExpression")
    /** 8719 */ @JvmField val ModuloAssignmentExpression: IElementType = CSharpElementType("ModuloAssignmentExpression")
    /** 8720 */ @JvmField val AndAssignmentExpression: IElementType = CSharpElementType("AndAssignmentExpression")
    /** 8721 */ @JvmField val ExclusiveOrAssignmentExpression: IElementType = CSharpElementType("ExclusiveOrAssignmentExpression")
    /** 8722 */ @JvmField val OrAssignmentExpression: IElementType = CSharpElementType("OrAssignmentExpression")
    /** 8723 */ @JvmField val LeftShiftAssignmentExpression: IElementType = CSharpElementType("LeftShiftAssignmentExpression")
    /** 8724 */ @JvmField val RightShiftAssignmentExpression: IElementType = CSharpElementType("RightShiftAssignmentExpression")
    /** 8725 */ @JvmField val CoalesceAssignmentExpression: IElementType = CSharpElementType("CoalesceAssignmentExpression")
    /** 8726 */ @JvmField val UnsignedRightShiftAssignmentExpression: IElementType = CSharpElementType("UnsignedRightShiftAssignmentExpression")
    /** 8730 */ @JvmField val UnaryPlusExpression: IElementType = CSharpElementType("UnaryPlusExpression")
    /** 8731 */ @JvmField val UnaryMinusExpression: IElementType = CSharpElementType("UnaryMinusExpression")
    /** 8732 */ @JvmField val BitwiseNotExpression: IElementType = CSharpElementType("BitwiseNotExpression")
    /** 8733 */ @JvmField val LogicalNotExpression: IElementType = CSharpElementType("LogicalNotExpression")
    /** 8734 */ @JvmField val PreIncrementExpression: IElementType = CSharpElementType("PreIncrementExpression")
    /** 8735 */ @JvmField val PreDecrementExpression: IElementType = CSharpElementType("PreDecrementExpression")
    /** 8736 */ @JvmField val PointerIndirectionExpression: IElementType = CSharpElementType("PointerIndirectionExpression")
    /** 8737 */ @JvmField val AddressOfExpression: IElementType = CSharpElementType("AddressOfExpression")
    /** 8738 */ @JvmField val PostIncrementExpression: IElementType = CSharpElementType("PostIncrementExpression")
    /** 8739 */ @JvmField val PostDecrementExpression: IElementType = CSharpElementType("PostDecrementExpression")
    /** 8740 */ @JvmField val AwaitExpression: IElementType = CSharpElementType("AwaitExpression")
    /** 8741 */ @JvmField val IndexExpression: IElementType = CSharpElementType("IndexExpression")
    /** 8746 */ @JvmField val ThisExpression: IElementType = CSharpElementType("ThisExpression")
    /** 8747 */ @JvmField val BaseExpression: IElementType = CSharpElementType("BaseExpression")
    /** 8748 */ @JvmField val ArgListExpression: IElementType = CSharpElementType("ArgListExpression")
    /** 8749 */ @JvmField val NumericLiteralExpression: IElementType = CSharpElementType("NumericLiteralExpression")
    /** 8750 */ @JvmField val StringLiteralExpression: IElementType = CSharpElementType("StringLiteralExpression")
    /** 8751 */ @JvmField val CharacterLiteralExpression: IElementType = CSharpElementType("CharacterLiteralExpression")
    /** 8752 */ @JvmField val TrueLiteralExpression: IElementType = CSharpElementType("TrueLiteralExpression")
    /** 8753 */ @JvmField val FalseLiteralExpression: IElementType = CSharpElementType("FalseLiteralExpression")
    /** 8754 */ @JvmField val NullLiteralExpression: IElementType = CSharpElementType("NullLiteralExpression")
    /** 8755 */ @JvmField val DefaultLiteralExpression: IElementType = CSharpElementType("DefaultLiteralExpression")
    /** 8756 */ @JvmField val Utf8StringLiteralExpression: IElementType = CSharpElementType("Utf8StringLiteralExpression")
    /** 8757 */ @JvmField val FieldExpression: IElementType = CSharpElementType("FieldExpression")
    /** 8760 */ @JvmField val TypeOfExpression: IElementType = CSharpElementType("TypeOfExpression")
    /** 8761 */ @JvmField val SizeOfExpression: IElementType = CSharpElementType("SizeOfExpression")
    /** 8762 */ @JvmField val CheckedExpression: IElementType = CSharpElementType("CheckedExpression")
    /** 8763 */ @JvmField val UncheckedExpression: IElementType = CSharpElementType("UncheckedExpression")
    /** 8764 */ @JvmField val DefaultExpression: IElementType = CSharpElementType("DefaultExpression")
    /** 8765 */ @JvmField val MakeRefExpression: IElementType = CSharpElementType("MakeRefExpression")
    /** 8766 */ @JvmField val RefValueExpression: IElementType = CSharpElementType("RefValueExpression")
    /** 8767 */ @JvmField val RefTypeExpression: IElementType = CSharpElementType("RefTypeExpression")
    /** 8769 */ @JvmField val UnsafeExpression: IElementType = CSharpElementType("UnsafeExpression")
    /** 8774 */ @JvmField val QueryExpression: IElementType = CSharpElementType("QueryExpression")
    /** 8775 */ @JvmField val QueryBody: IElementType = CSharpElementType("QueryBody")
    /** 8776 */ @JvmField val FromClause: IElementType = CSharpElementType("FromClause")
    /** 8777 */ @JvmField val LetClause: IElementType = CSharpElementType("LetClause")
    /** 8778 */ @JvmField val JoinClause: IElementType = CSharpElementType("JoinClause")
    /** 8779 */ @JvmField val JoinIntoClause: IElementType = CSharpElementType("JoinIntoClause")
    /** 8780 */ @JvmField val WhereClause: IElementType = CSharpElementType("WhereClause")
    /** 8781 */ @JvmField val OrderByClause: IElementType = CSharpElementType("OrderByClause")
    /** 8782 */ @JvmField val AscendingOrdering: IElementType = CSharpElementType("AscendingOrdering")
    /** 8783 */ @JvmField val DescendingOrdering: IElementType = CSharpElementType("DescendingOrdering")
    /** 8784 */ @JvmField val SelectClause: IElementType = CSharpElementType("SelectClause")
    /** 8785 */ @JvmField val GroupClause: IElementType = CSharpElementType("GroupClause")
    /** 8786 */ @JvmField val QueryContinuation: IElementType = CSharpElementType("QueryContinuation")
    /** 8792 */ @JvmField val Block: IElementType = CSharpElementType("Block")
    /** 8793 */ @JvmField val LocalDeclarationStatement: IElementType = CSharpElementType("LocalDeclarationStatement")
    /** 8794 */ @JvmField val VariableDeclaration: IElementType = CSharpElementType("VariableDeclaration")
    /** 8795 */ @JvmField val VariableDeclarator: IElementType = CSharpElementType("VariableDeclarator")
    /** 8796 */ @JvmField val EqualsValueClause: IElementType = CSharpElementType("EqualsValueClause")
    /** 8797 */ @JvmField val ExpressionStatement: IElementType = CSharpElementType("ExpressionStatement")
    /** 8798 */ @JvmField val EmptyStatement: IElementType = CSharpElementType("EmptyStatement")
    /** 8799 */ @JvmField val LabeledStatement: IElementType = CSharpElementType("LabeledStatement")
    /** 8800 */ @JvmField val GotoStatement: IElementType = CSharpElementType("GotoStatement")
    /** 8801 */ @JvmField val GotoCaseStatement: IElementType = CSharpElementType("GotoCaseStatement")
    /** 8802 */ @JvmField val GotoDefaultStatement: IElementType = CSharpElementType("GotoDefaultStatement")
    /** 8803 */ @JvmField val BreakStatement: IElementType = CSharpElementType("BreakStatement")
    /** 8804 */ @JvmField val ContinueStatement: IElementType = CSharpElementType("ContinueStatement")
    /** 8805 */ @JvmField val ReturnStatement: IElementType = CSharpElementType("ReturnStatement")
    /** 8806 */ @JvmField val YieldReturnStatement: IElementType = CSharpElementType("YieldReturnStatement")
    /** 8807 */ @JvmField val YieldBreakStatement: IElementType = CSharpElementType("YieldBreakStatement")
    /** 8808 */ @JvmField val ThrowStatement: IElementType = CSharpElementType("ThrowStatement")
    /** 8809 */ @JvmField val WhileStatement: IElementType = CSharpElementType("WhileStatement")
    /** 8810 */ @JvmField val DoStatement: IElementType = CSharpElementType("DoStatement")
    /** 8811 */ @JvmField val ForStatement: IElementType = CSharpElementType("ForStatement")
    /** 8812 */ @JvmField val ForEachStatement: IElementType = CSharpElementType("ForEachStatement")
    /** 8813 */ @JvmField val UsingStatement: IElementType = CSharpElementType("UsingStatement")
    /** 8814 */ @JvmField val FixedStatement: IElementType = CSharpElementType("FixedStatement")
    /** 8815 */ @JvmField val CheckedStatement: IElementType = CSharpElementType("CheckedStatement")
    /** 8816 */ @JvmField val UncheckedStatement: IElementType = CSharpElementType("UncheckedStatement")
    /** 8817 */ @JvmField val UnsafeStatement: IElementType = CSharpElementType("UnsafeStatement")
    /** 8818 */ @JvmField val LockStatement: IElementType = CSharpElementType("LockStatement")
    /** 8819 */ @JvmField val IfStatement: IElementType = CSharpElementType("IfStatement")
    /** 8820 */ @JvmField val ElseClause: IElementType = CSharpElementType("ElseClause")
    /** 8821 */ @JvmField val SwitchStatement: IElementType = CSharpElementType("SwitchStatement")
    /** 8822 */ @JvmField val SwitchSection: IElementType = CSharpElementType("SwitchSection")
    /** 8823 */ @JvmField val CaseSwitchLabel: IElementType = CSharpElementType("CaseSwitchLabel")
    /** 8824 */ @JvmField val DefaultSwitchLabel: IElementType = CSharpElementType("DefaultSwitchLabel")
    /** 8825 */ @JvmField val TryStatement: IElementType = CSharpElementType("TryStatement")
    /** 8826 */ @JvmField val CatchClause: IElementType = CSharpElementType("CatchClause")
    /** 8827 */ @JvmField val CatchDeclaration: IElementType = CSharpElementType("CatchDeclaration")
    /** 8828 */ @JvmField val CatchFilterClause: IElementType = CSharpElementType("CatchFilterClause")
    /** 8829 */ @JvmField val FinallyClause: IElementType = CSharpElementType("FinallyClause")
    /** 8830 */ @JvmField val LocalFunctionStatement: IElementType = CSharpElementType("LocalFunctionStatement")
    /** 8840 */ @JvmField val CompilationUnit: IElementType = CSharpElementType("CompilationUnit")
    /** 8841 */ @JvmField val GlobalStatement: IElementType = CSharpElementType("GlobalStatement")
    /** 8842 */ @JvmField val NamespaceDeclaration: IElementType = CSharpElementType("NamespaceDeclaration")
    /** 8843 */ @JvmField val UsingDirective: IElementType = CSharpElementType("UsingDirective")
    /** 8844 */ @JvmField val ExternAliasDirective: IElementType = CSharpElementType("ExternAliasDirective")
    /** 8845 */ @JvmField val FileScopedNamespaceDeclaration: IElementType = CSharpElementType("FileScopedNamespaceDeclaration")
    /** 8847 */ @JvmField val AttributeList: IElementType = CSharpElementType("AttributeList")
    /** 8848 */ @JvmField val AttributeTargetSpecifier: IElementType = CSharpElementType("AttributeTargetSpecifier")
    /** 8849 */ @JvmField val Attribute: IElementType = CSharpElementType("Attribute")
    /** 8850 */ @JvmField val AttributeArgumentList: IElementType = CSharpElementType("AttributeArgumentList")
    /** 8851 */ @JvmField val AttributeArgument: IElementType = CSharpElementType("AttributeArgument")
    /** 8852 */ @JvmField val NameEquals: IElementType = CSharpElementType("NameEquals")
    /** 8855 */ @JvmField val ClassDeclaration: IElementType = CSharpElementType("ClassDeclaration")
    /** 8856 */ @JvmField val StructDeclaration: IElementType = CSharpElementType("StructDeclaration")
    /** 8857 */ @JvmField val InterfaceDeclaration: IElementType = CSharpElementType("InterfaceDeclaration")
    /** 8858 */ @JvmField val EnumDeclaration: IElementType = CSharpElementType("EnumDeclaration")
    /** 8859 */ @JvmField val DelegateDeclaration: IElementType = CSharpElementType("DelegateDeclaration")
    /** 8864 */ @JvmField val BaseList: IElementType = CSharpElementType("BaseList")
    /** 8865 */ @JvmField val SimpleBaseType: IElementType = CSharpElementType("SimpleBaseType")
    /** 8866 */ @JvmField val TypeParameterConstraintClause: IElementType = CSharpElementType("TypeParameterConstraintClause")
    /** 8867 */ @JvmField val ConstructorConstraint: IElementType = CSharpElementType("ConstructorConstraint")
    /** 8868 */ @JvmField val ClassConstraint: IElementType = CSharpElementType("ClassConstraint")
    /** 8869 */ @JvmField val StructConstraint: IElementType = CSharpElementType("StructConstraint")
    /** 8870 */ @JvmField val TypeConstraint: IElementType = CSharpElementType("TypeConstraint")
    /** 8871 */ @JvmField val ExplicitInterfaceSpecifier: IElementType = CSharpElementType("ExplicitInterfaceSpecifier")
    /** 8872 */ @JvmField val EnumMemberDeclaration: IElementType = CSharpElementType("EnumMemberDeclaration")
    /** 8873 */ @JvmField val FieldDeclaration: IElementType = CSharpElementType("FieldDeclaration")
    /** 8874 */ @JvmField val EventFieldDeclaration: IElementType = CSharpElementType("EventFieldDeclaration")
    /** 8875 */ @JvmField val MethodDeclaration: IElementType = CSharpElementType("MethodDeclaration")
    /** 8876 */ @JvmField val OperatorDeclaration: IElementType = CSharpElementType("OperatorDeclaration")
    /** 8877 */ @JvmField val ConversionOperatorDeclaration: IElementType = CSharpElementType("ConversionOperatorDeclaration")
    /** 8878 */ @JvmField val ConstructorDeclaration: IElementType = CSharpElementType("ConstructorDeclaration")
    /** 8879 */ @JvmField val AllowsConstraintClause: IElementType = CSharpElementType("AllowsConstraintClause")
    /** 8880 */ @JvmField val RefStructConstraint: IElementType = CSharpElementType("RefStructConstraint")
    /** 8889 */ @JvmField val BaseConstructorInitializer: IElementType = CSharpElementType("BaseConstructorInitializer")
    /** 8890 */ @JvmField val ThisConstructorInitializer: IElementType = CSharpElementType("ThisConstructorInitializer")
    /** 8891 */ @JvmField val DestructorDeclaration: IElementType = CSharpElementType("DestructorDeclaration")
    /** 8892 */ @JvmField val PropertyDeclaration: IElementType = CSharpElementType("PropertyDeclaration")
    /** 8893 */ @JvmField val EventDeclaration: IElementType = CSharpElementType("EventDeclaration")
    /** 8894 */ @JvmField val IndexerDeclaration: IElementType = CSharpElementType("IndexerDeclaration")
    /** 8895 */ @JvmField val AccessorList: IElementType = CSharpElementType("AccessorList")
    /** 8896 */ @JvmField val GetAccessorDeclaration: IElementType = CSharpElementType("GetAccessorDeclaration")
    /** 8897 */ @JvmField val SetAccessorDeclaration: IElementType = CSharpElementType("SetAccessorDeclaration")
    /** 8898 */ @JvmField val AddAccessorDeclaration: IElementType = CSharpElementType("AddAccessorDeclaration")
    /** 8899 */ @JvmField val RemoveAccessorDeclaration: IElementType = CSharpElementType("RemoveAccessorDeclaration")
    /** 8900 */ @JvmField val UnknownAccessorDeclaration: IElementType = CSharpElementType("UnknownAccessorDeclaration")
    /** 8906 */ @JvmField val ParameterList: IElementType = CSharpElementType("ParameterList")
    /** 8907 */ @JvmField val BracketedParameterList: IElementType = CSharpElementType("BracketedParameterList")
    /** 8908 */ @JvmField val Parameter: IElementType = CSharpElementType("Parameter")
    /** 8909 */ @JvmField val TypeParameterList: IElementType = CSharpElementType("TypeParameterList")
    /** 8910 */ @JvmField val TypeParameter: IElementType = CSharpElementType("TypeParameter")
    /** 8916 */ @JvmField val IncompleteMember: IElementType = CSharpElementType("IncompleteMember")
    /** 8917 */ @JvmField val ArrowExpressionClause: IElementType = CSharpElementType("ArrowExpressionClause")
    /** 8918 */ @JvmField val Interpolation: IElementType = CSharpElementType("Interpolation")
    /** 8919 */ @JvmField val InterpolatedStringText: IElementType = CSharpElementType("InterpolatedStringText")
    /** 8920 */ @JvmField val InterpolationAlignmentClause: IElementType = CSharpElementType("InterpolationAlignmentClause")
    /** 8921 */ @JvmField val InterpolationFormatClause: IElementType = CSharpElementType("InterpolationFormatClause")
    /** 8922 */ @JvmField val ShebangDirectiveTrivia: IElementType = CSharpTokenType("ShebangDirectiveTrivia")
    /** 8923 */ @JvmField val LoadDirectiveTrivia: IElementType = CSharpTokenType("LoadDirectiveTrivia")
    /** 8924 */ @JvmField val TupleType: IElementType = CSharpElementType("TupleType")
    /** 8925 */ @JvmField val TupleElement: IElementType = CSharpElementType("TupleElement")
    /** 8926 */ @JvmField val TupleExpression: IElementType = CSharpElementType("TupleExpression")
    /** 8927 */ @JvmField val SingleVariableDesignation: IElementType = CSharpElementType("SingleVariableDesignation")
    /** 8928 */ @JvmField val ParenthesizedVariableDesignation: IElementType = CSharpElementType("ParenthesizedVariableDesignation")
    /** 8929 */ @JvmField val ForEachVariableStatement: IElementType = CSharpElementType("ForEachVariableStatement")
    /** 9000 */ @JvmField val DeclarationPattern: IElementType = CSharpElementType("DeclarationPattern")
    /** 9002 */ @JvmField val ConstantPattern: IElementType = CSharpElementType("ConstantPattern")
    /** 9009 */ @JvmField val CasePatternSwitchLabel: IElementType = CSharpElementType("CasePatternSwitchLabel")
    /** 9013 */ @JvmField val WhenClause: IElementType = CSharpElementType("WhenClause")
    /** 9014 */ @JvmField val DiscardDesignation: IElementType = CSharpElementType("DiscardDesignation")
    /** 9020 */ @JvmField val RecursivePattern: IElementType = CSharpElementType("RecursivePattern")
    /** 9021 */ @JvmField val PropertyPatternClause: IElementType = CSharpElementType("PropertyPatternClause")
    /** 9022 */ @JvmField val Subpattern: IElementType = CSharpElementType("Subpattern")
    /** 9023 */ @JvmField val PositionalPatternClause: IElementType = CSharpElementType("PositionalPatternClause")
    /** 9024 */ @JvmField val DiscardPattern: IElementType = CSharpElementType("DiscardPattern")
    /** 9025 */ @JvmField val SwitchExpression: IElementType = CSharpElementType("SwitchExpression")
    /** 9026 */ @JvmField val SwitchExpressionArm: IElementType = CSharpElementType("SwitchExpressionArm")
    /** 9027 */ @JvmField val VarPattern: IElementType = CSharpElementType("VarPattern")
    /** 9028 */ @JvmField val ParenthesizedPattern: IElementType = CSharpElementType("ParenthesizedPattern")
    /** 9029 */ @JvmField val RelationalPattern: IElementType = CSharpElementType("RelationalPattern")
    /** 9030 */ @JvmField val TypePattern: IElementType = CSharpElementType("TypePattern")
    /** 9031 */ @JvmField val OrPattern: IElementType = CSharpElementType("OrPattern")
    /** 9032 */ @JvmField val AndPattern: IElementType = CSharpElementType("AndPattern")
    /** 9033 */ @JvmField val NotPattern: IElementType = CSharpElementType("NotPattern")
    /** 9034 */ @JvmField val SlicePattern: IElementType = CSharpElementType("SlicePattern")
    /** 9035 */ @JvmField val ListPattern: IElementType = CSharpElementType("ListPattern")
    /** 9040 */ @JvmField val DeclarationExpression: IElementType = CSharpElementType("DeclarationExpression")
    /** 9050 */ @JvmField val RefExpression: IElementType = CSharpElementType("RefExpression")
    /** 9051 */ @JvmField val RefType: IElementType = CSharpElementType("RefType")
    /** 9052 */ @JvmField val ThrowExpression: IElementType = CSharpElementType("ThrowExpression")
    /** 9053 */ @JvmField val ImplicitStackAllocArrayCreationExpression: IElementType = CSharpElementType("ImplicitStackAllocArrayCreationExpression")
    /** 9054 */ @JvmField val SuppressNullableWarningExpression: IElementType = CSharpElementType("SuppressNullableWarningExpression")
    /** 9055 */ @JvmField val NullableDirectiveTrivia: IElementType = CSharpTokenType("NullableDirectiveTrivia")
    /** 9056 */ @JvmField val FunctionPointerType: IElementType = CSharpElementType("FunctionPointerType")
    /** 9057 */ @JvmField val FunctionPointerParameter: IElementType = CSharpElementType("FunctionPointerParameter")
    /** 9058 */ @JvmField val FunctionPointerParameterList: IElementType = CSharpElementType("FunctionPointerParameterList")
    /** 9059 */ @JvmField val FunctionPointerCallingConvention: IElementType = CSharpElementType("FunctionPointerCallingConvention")
    /** 9060 */ @JvmField val InitAccessorDeclaration: IElementType = CSharpElementType("InitAccessorDeclaration")
    /** 9061 */ @JvmField val WithExpression: IElementType = CSharpElementType("WithExpression")
    /** 9062 */ @JvmField val WithInitializerExpression: IElementType = CSharpElementType("WithInitializerExpression")
    /** 9063 */ @JvmField val RecordDeclaration: IElementType = CSharpElementType("RecordDeclaration")
    /** 9064 */ @JvmField val DefaultConstraint: IElementType = CSharpElementType("DefaultConstraint")
    /** 9065 */ @JvmField val PrimaryConstructorBaseType: IElementType = CSharpElementType("PrimaryConstructorBaseType")
    /** 9066 */ @JvmField val FunctionPointerUnmanagedCallingConventionList: IElementType = CSharpElementType("FunctionPointerUnmanagedCallingConventionList")
    /** 9067 */ @JvmField val FunctionPointerUnmanagedCallingConvention: IElementType = CSharpElementType("FunctionPointerUnmanagedCallingConvention")
    /** 9068 */ @JvmField val RecordStructDeclaration: IElementType = CSharpElementType("RecordStructDeclaration")
    /** 9069 */ @JvmField val ExpressionColon: IElementType = CSharpElementType("ExpressionColon")
    /** 9070 */ @JvmField val LineDirectivePosition: IElementType = CSharpElementType("LineDirectivePosition")
    /** 9071 */ @JvmField val LineSpanDirectiveTrivia: IElementType = CSharpTokenType("LineSpanDirectiveTrivia")
    /** 9072 */ @JvmField val InterpolatedSingleLineRawStringStartToken: IElementType = CSharpTokenType("InterpolatedSingleLineRawStringStartToken")
    /** 9073 */ @JvmField val InterpolatedMultiLineRawStringStartToken: IElementType = CSharpTokenType("InterpolatedMultiLineRawStringStartToken")
    /** 9074 */ @JvmField val InterpolatedRawStringEndToken: IElementType = CSharpTokenType("InterpolatedRawStringEndToken")
    /** 9075 */ @JvmField val ScopedType: IElementType = CSharpElementType("ScopedType")
    /** 9076 */ @JvmField val CollectionExpression: IElementType = CSharpElementType("CollectionExpression")
    /** 9077 */ @JvmField val ExpressionElement: IElementType = CSharpElementType("ExpressionElement")
    /** 9078 */ @JvmField val SpreadElement: IElementType = CSharpElementType("SpreadElement")
    /** 9079 */ @JvmField val ExtensionBlockDeclaration: IElementType = CSharpElementType("ExtensionBlockDeclaration")
    /** 9080 */ @JvmField val IgnoredDirectiveTrivia: IElementType = CSharpTokenType("IgnoredDirectiveTrivia")
    /** 9081 */ @JvmField val WithElement: IElementType = CSharpElementType("WithElement")
    /** 9082 */ @JvmField val UnionDeclaration: IElementType = CSharpElementType("UnionDeclaration")

    /** Every kind by its Roslyn name (aliases included). */
    val byName: Map<String, IElementType> by lazy {
        hashMapOf(
            "TildeToken" to TildeToken,
            "ExclamationToken" to ExclamationToken,
            "DollarToken" to DollarToken,
            "PercentToken" to PercentToken,
            "CaretToken" to CaretToken,
            "AmpersandToken" to AmpersandToken,
            "AsteriskToken" to AsteriskToken,
            "OpenParenToken" to OpenParenToken,
            "CloseParenToken" to CloseParenToken,
            "MinusToken" to MinusToken,
            "PlusToken" to PlusToken,
            "EqualsToken" to EqualsToken,
            "OpenBraceToken" to OpenBraceToken,
            "CloseBraceToken" to CloseBraceToken,
            "OpenBracketToken" to OpenBracketToken,
            "CloseBracketToken" to CloseBracketToken,
            "BarToken" to BarToken,
            "BackslashToken" to BackslashToken,
            "ColonToken" to ColonToken,
            "SemicolonToken" to SemicolonToken,
            "DoubleQuoteToken" to DoubleQuoteToken,
            "SingleQuoteToken" to SingleQuoteToken,
            "LessThanToken" to LessThanToken,
            "CommaToken" to CommaToken,
            "GreaterThanToken" to GreaterThanToken,
            "DotToken" to DotToken,
            "QuestionToken" to QuestionToken,
            "HashToken" to HashToken,
            "SlashToken" to SlashToken,
            "DotDotToken" to DotDotToken,
            "SlashGreaterThanToken" to SlashGreaterThanToken,
            "LessThanSlashToken" to LessThanSlashToken,
            "XmlCommentStartToken" to XmlCommentStartToken,
            "XmlCommentEndToken" to XmlCommentEndToken,
            "XmlCDataStartToken" to XmlCDataStartToken,
            "XmlCDataEndToken" to XmlCDataEndToken,
            "XmlProcessingInstructionStartToken" to XmlProcessingInstructionStartToken,
            "XmlProcessingInstructionEndToken" to XmlProcessingInstructionEndToken,
            "BarBarToken" to BarBarToken,
            "AmpersandAmpersandToken" to AmpersandAmpersandToken,
            "MinusMinusToken" to MinusMinusToken,
            "PlusPlusToken" to PlusPlusToken,
            "ColonColonToken" to ColonColonToken,
            "QuestionQuestionToken" to QuestionQuestionToken,
            "MinusGreaterThanToken" to MinusGreaterThanToken,
            "ExclamationEqualsToken" to ExclamationEqualsToken,
            "EqualsEqualsToken" to EqualsEqualsToken,
            "EqualsGreaterThanToken" to EqualsGreaterThanToken,
            "LessThanEqualsToken" to LessThanEqualsToken,
            "LessThanLessThanToken" to LessThanLessThanToken,
            "LessThanLessThanEqualsToken" to LessThanLessThanEqualsToken,
            "GreaterThanEqualsToken" to GreaterThanEqualsToken,
            "GreaterThanGreaterThanToken" to GreaterThanGreaterThanToken,
            "GreaterThanGreaterThanEqualsToken" to GreaterThanGreaterThanEqualsToken,
            "SlashEqualsToken" to SlashEqualsToken,
            "AsteriskEqualsToken" to AsteriskEqualsToken,
            "BarEqualsToken" to BarEqualsToken,
            "AmpersandEqualsToken" to AmpersandEqualsToken,
            "PlusEqualsToken" to PlusEqualsToken,
            "MinusEqualsToken" to MinusEqualsToken,
            "CaretEqualsToken" to CaretEqualsToken,
            "PercentEqualsToken" to PercentEqualsToken,
            "QuestionQuestionEqualsToken" to QuestionQuestionEqualsToken,
            "GreaterThanGreaterThanGreaterThanToken" to GreaterThanGreaterThanGreaterThanToken,
            "GreaterThanGreaterThanGreaterThanEqualsToken" to GreaterThanGreaterThanGreaterThanEqualsToken,
            "BoolKeyword" to BoolKeyword,
            "ByteKeyword" to ByteKeyword,
            "SByteKeyword" to SByteKeyword,
            "ShortKeyword" to ShortKeyword,
            "UShortKeyword" to UShortKeyword,
            "IntKeyword" to IntKeyword,
            "UIntKeyword" to UIntKeyword,
            "LongKeyword" to LongKeyword,
            "ULongKeyword" to ULongKeyword,
            "DoubleKeyword" to DoubleKeyword,
            "FloatKeyword" to FloatKeyword,
            "DecimalKeyword" to DecimalKeyword,
            "StringKeyword" to StringKeyword,
            "CharKeyword" to CharKeyword,
            "VoidKeyword" to VoidKeyword,
            "ObjectKeyword" to ObjectKeyword,
            "TypeOfKeyword" to TypeOfKeyword,
            "SizeOfKeyword" to SizeOfKeyword,
            "NullKeyword" to NullKeyword,
            "TrueKeyword" to TrueKeyword,
            "FalseKeyword" to FalseKeyword,
            "IfKeyword" to IfKeyword,
            "ElseKeyword" to ElseKeyword,
            "WhileKeyword" to WhileKeyword,
            "ForKeyword" to ForKeyword,
            "ForEachKeyword" to ForEachKeyword,
            "DoKeyword" to DoKeyword,
            "SwitchKeyword" to SwitchKeyword,
            "CaseKeyword" to CaseKeyword,
            "DefaultKeyword" to DefaultKeyword,
            "TryKeyword" to TryKeyword,
            "CatchKeyword" to CatchKeyword,
            "FinallyKeyword" to FinallyKeyword,
            "LockKeyword" to LockKeyword,
            "GotoKeyword" to GotoKeyword,
            "BreakKeyword" to BreakKeyword,
            "ContinueKeyword" to ContinueKeyword,
            "ReturnKeyword" to ReturnKeyword,
            "ThrowKeyword" to ThrowKeyword,
            "PublicKeyword" to PublicKeyword,
            "PrivateKeyword" to PrivateKeyword,
            "InternalKeyword" to InternalKeyword,
            "ProtectedKeyword" to ProtectedKeyword,
            "StaticKeyword" to StaticKeyword,
            "ReadOnlyKeyword" to ReadOnlyKeyword,
            "SealedKeyword" to SealedKeyword,
            "ConstKeyword" to ConstKeyword,
            "FixedKeyword" to FixedKeyword,
            "StackAllocKeyword" to StackAllocKeyword,
            "VolatileKeyword" to VolatileKeyword,
            "NewKeyword" to NewKeyword,
            "OverrideKeyword" to OverrideKeyword,
            "AbstractKeyword" to AbstractKeyword,
            "VirtualKeyword" to VirtualKeyword,
            "EventKeyword" to EventKeyword,
            "ExternKeyword" to ExternKeyword,
            "RefKeyword" to RefKeyword,
            "OutKeyword" to OutKeyword,
            "InKeyword" to InKeyword,
            "IsKeyword" to IsKeyword,
            "AsKeyword" to AsKeyword,
            "ParamsKeyword" to ParamsKeyword,
            "ArgListKeyword" to ArgListKeyword,
            "MakeRefKeyword" to MakeRefKeyword,
            "RefTypeKeyword" to RefTypeKeyword,
            "RefValueKeyword" to RefValueKeyword,
            "ThisKeyword" to ThisKeyword,
            "BaseKeyword" to BaseKeyword,
            "NamespaceKeyword" to NamespaceKeyword,
            "UsingKeyword" to UsingKeyword,
            "ClassKeyword" to ClassKeyword,
            "StructKeyword" to StructKeyword,
            "InterfaceKeyword" to InterfaceKeyword,
            "EnumKeyword" to EnumKeyword,
            "DelegateKeyword" to DelegateKeyword,
            "CheckedKeyword" to CheckedKeyword,
            "UncheckedKeyword" to UncheckedKeyword,
            "UnsafeKeyword" to UnsafeKeyword,
            "OperatorKeyword" to OperatorKeyword,
            "ExplicitKeyword" to ExplicitKeyword,
            "ImplicitKeyword" to ImplicitKeyword,
            "YieldKeyword" to YieldKeyword,
            "PartialKeyword" to PartialKeyword,
            "AliasKeyword" to AliasKeyword,
            "GlobalKeyword" to GlobalKeyword,
            "AssemblyKeyword" to AssemblyKeyword,
            "ModuleKeyword" to ModuleKeyword,
            "TypeKeyword" to TypeKeyword,
            "FieldKeyword" to FieldKeyword,
            "MethodKeyword" to MethodKeyword,
            "ParamKeyword" to ParamKeyword,
            "PropertyKeyword" to PropertyKeyword,
            "TypeVarKeyword" to TypeVarKeyword,
            "GetKeyword" to GetKeyword,
            "SetKeyword" to SetKeyword,
            "AddKeyword" to AddKeyword,
            "RemoveKeyword" to RemoveKeyword,
            "WhereKeyword" to WhereKeyword,
            "FromKeyword" to FromKeyword,
            "GroupKeyword" to GroupKeyword,
            "JoinKeyword" to JoinKeyword,
            "IntoKeyword" to IntoKeyword,
            "LetKeyword" to LetKeyword,
            "ByKeyword" to ByKeyword,
            "SelectKeyword" to SelectKeyword,
            "OrderByKeyword" to OrderByKeyword,
            "OnKeyword" to OnKeyword,
            "EqualsKeyword" to EqualsKeyword,
            "AscendingKeyword" to AscendingKeyword,
            "DescendingKeyword" to DescendingKeyword,
            "NameOfKeyword" to NameOfKeyword,
            "AsyncKeyword" to AsyncKeyword,
            "AwaitKeyword" to AwaitKeyword,
            "WhenKeyword" to WhenKeyword,
            "OrKeyword" to OrKeyword,
            "AndKeyword" to AndKeyword,
            "NotKeyword" to NotKeyword,
            "WithKeyword" to WithKeyword,
            "InitKeyword" to InitKeyword,
            "RecordKeyword" to RecordKeyword,
            "ManagedKeyword" to ManagedKeyword,
            "UnmanagedKeyword" to UnmanagedKeyword,
            "RequiredKeyword" to RequiredKeyword,
            "ScopedKeyword" to ScopedKeyword,
            "FileKeyword" to FileKeyword,
            "AllowsKeyword" to AllowsKeyword,
            "ExtensionKeyword" to ExtensionKeyword,
            "UnionKeyword" to UnionKeyword,
            "ClosedKeyword" to ClosedKeyword,
            "SafeKeyword" to SafeKeyword,
            "ElifKeyword" to ElifKeyword,
            "EndIfKeyword" to EndIfKeyword,
            "RegionKeyword" to RegionKeyword,
            "EndRegionKeyword" to EndRegionKeyword,
            "DefineKeyword" to DefineKeyword,
            "UndefKeyword" to UndefKeyword,
            "WarningKeyword" to WarningKeyword,
            "ErrorKeyword" to ErrorKeyword,
            "LineKeyword" to LineKeyword,
            "PragmaKeyword" to PragmaKeyword,
            "HiddenKeyword" to HiddenKeyword,
            "ChecksumKeyword" to ChecksumKeyword,
            "DisableKeyword" to DisableKeyword,
            "RestoreKeyword" to RestoreKeyword,
            "ReferenceKeyword" to ReferenceKeyword,
            "InterpolatedStringStartToken" to InterpolatedStringStartToken,
            "InterpolatedStringEndToken" to InterpolatedStringEndToken,
            "InterpolatedVerbatimStringStartToken" to InterpolatedVerbatimStringStartToken,
            "LoadKeyword" to LoadKeyword,
            "NullableKeyword" to NullableKeyword,
            "EnableKeyword" to EnableKeyword,
            "WarningsKeyword" to WarningsKeyword,
            "AnnotationsKeyword" to AnnotationsKeyword,
            "VarKeyword" to VarKeyword,
            "UnderscoreToken" to UnderscoreToken,
            "OmittedTypeArgumentToken" to OmittedTypeArgumentToken,
            "OmittedArraySizeExpressionToken" to OmittedArraySizeExpressionToken,
            "EndOfDirectiveToken" to EndOfDirectiveToken,
            "EndOfDocumentationCommentToken" to EndOfDocumentationCommentToken,
            "EndOfFileToken" to EndOfFileToken,
            "BadToken" to BadToken,
            "IdentifierToken" to IdentifierToken,
            "NumericLiteralToken" to NumericLiteralToken,
            "CharacterLiteralToken" to CharacterLiteralToken,
            "StringLiteralToken" to StringLiteralToken,
            "XmlEntityLiteralToken" to XmlEntityLiteralToken,
            "XmlTextLiteralToken" to XmlTextLiteralToken,
            "XmlTextLiteralNewLineToken" to XmlTextLiteralNewLineToken,
            "InterpolatedStringToken" to InterpolatedStringToken,
            "InterpolatedStringTextToken" to InterpolatedStringTextToken,
            "SingleLineRawStringLiteralToken" to SingleLineRawStringLiteralToken,
            "MultiLineRawStringLiteralToken" to MultiLineRawStringLiteralToken,
            "Utf8StringLiteralToken" to Utf8StringLiteralToken,
            "Utf8SingleLineRawStringLiteralToken" to Utf8SingleLineRawStringLiteralToken,
            "Utf8MultiLineRawStringLiteralToken" to Utf8MultiLineRawStringLiteralToken,
            "RazorContentToken" to RazorContentToken,
            "EndOfLineTrivia" to EndOfLineTrivia,
            "WhitespaceTrivia" to WhitespaceTrivia,
            "SingleLineCommentTrivia" to SingleLineCommentTrivia,
            "MultiLineCommentTrivia" to MultiLineCommentTrivia,
            "DocumentationCommentExteriorTrivia" to DocumentationCommentExteriorTrivia,
            "SingleLineDocumentationCommentTrivia" to SingleLineDocumentationCommentTrivia,
            "MultiLineDocumentationCommentTrivia" to MultiLineDocumentationCommentTrivia,
            "DisabledTextTrivia" to DisabledTextTrivia,
            "PreprocessingMessageTrivia" to PreprocessingMessageTrivia,
            "IfDirectiveTrivia" to IfDirectiveTrivia,
            "ElifDirectiveTrivia" to ElifDirectiveTrivia,
            "ElseDirectiveTrivia" to ElseDirectiveTrivia,
            "EndIfDirectiveTrivia" to EndIfDirectiveTrivia,
            "RegionDirectiveTrivia" to RegionDirectiveTrivia,
            "EndRegionDirectiveTrivia" to EndRegionDirectiveTrivia,
            "DefineDirectiveTrivia" to DefineDirectiveTrivia,
            "UndefDirectiveTrivia" to UndefDirectiveTrivia,
            "ErrorDirectiveTrivia" to ErrorDirectiveTrivia,
            "WarningDirectiveTrivia" to WarningDirectiveTrivia,
            "LineDirectiveTrivia" to LineDirectiveTrivia,
            "PragmaWarningDirectiveTrivia" to PragmaWarningDirectiveTrivia,
            "PragmaChecksumDirectiveTrivia" to PragmaChecksumDirectiveTrivia,
            "ReferenceDirectiveTrivia" to ReferenceDirectiveTrivia,
            "BadDirectiveTrivia" to BadDirectiveTrivia,
            "SkippedTokensTrivia" to SkippedTokensTrivia,
            "ConflictMarkerTrivia" to ConflictMarkerTrivia,
            "XmlElement" to XmlElement,
            "XmlElementStartTag" to XmlElementStartTag,
            "XmlElementEndTag" to XmlElementEndTag,
            "XmlEmptyElement" to XmlEmptyElement,
            "XmlTextAttribute" to XmlTextAttribute,
            "XmlCrefAttribute" to XmlCrefAttribute,
            "XmlNameAttribute" to XmlNameAttribute,
            "XmlName" to XmlName,
            "XmlPrefix" to XmlPrefix,
            "XmlText" to XmlText,
            "XmlCDataSection" to XmlCDataSection,
            "XmlComment" to XmlComment,
            "XmlProcessingInstruction" to XmlProcessingInstruction,
            "TypeCref" to TypeCref,
            "QualifiedCref" to QualifiedCref,
            "NameMemberCref" to NameMemberCref,
            "IndexerMemberCref" to IndexerMemberCref,
            "OperatorMemberCref" to OperatorMemberCref,
            "ConversionOperatorMemberCref" to ConversionOperatorMemberCref,
            "CrefParameterList" to CrefParameterList,
            "CrefBracketedParameterList" to CrefBracketedParameterList,
            "CrefParameter" to CrefParameter,
            "ExtensionMemberCref" to ExtensionMemberCref,
            "IdentifierName" to IdentifierName,
            "QualifiedName" to QualifiedName,
            "GenericName" to GenericName,
            "TypeArgumentList" to TypeArgumentList,
            "AliasQualifiedName" to AliasQualifiedName,
            "PredefinedType" to PredefinedType,
            "ArrayType" to ArrayType,
            "ArrayRankSpecifier" to ArrayRankSpecifier,
            "PointerType" to PointerType,
            "NullableType" to NullableType,
            "OmittedTypeArgument" to OmittedTypeArgument,
            "ParenthesizedExpression" to ParenthesizedExpression,
            "ConditionalExpression" to ConditionalExpression,
            "InvocationExpression" to InvocationExpression,
            "ElementAccessExpression" to ElementAccessExpression,
            "ArgumentList" to ArgumentList,
            "BracketedArgumentList" to BracketedArgumentList,
            "Argument" to Argument,
            "NameColon" to NameColon,
            "CastExpression" to CastExpression,
            "AnonymousMethodExpression" to AnonymousMethodExpression,
            "SimpleLambdaExpression" to SimpleLambdaExpression,
            "ParenthesizedLambdaExpression" to ParenthesizedLambdaExpression,
            "ObjectInitializerExpression" to ObjectInitializerExpression,
            "CollectionInitializerExpression" to CollectionInitializerExpression,
            "ArrayInitializerExpression" to ArrayInitializerExpression,
            "AnonymousObjectMemberDeclarator" to AnonymousObjectMemberDeclarator,
            "ComplexElementInitializerExpression" to ComplexElementInitializerExpression,
            "ObjectCreationExpression" to ObjectCreationExpression,
            "AnonymousObjectCreationExpression" to AnonymousObjectCreationExpression,
            "ArrayCreationExpression" to ArrayCreationExpression,
            "ImplicitArrayCreationExpression" to ImplicitArrayCreationExpression,
            "StackAllocArrayCreationExpression" to StackAllocArrayCreationExpression,
            "OmittedArraySizeExpression" to OmittedArraySizeExpression,
            "InterpolatedStringExpression" to InterpolatedStringExpression,
            "ImplicitElementAccess" to ImplicitElementAccess,
            "IsPatternExpression" to IsPatternExpression,
            "RangeExpression" to RangeExpression,
            "ImplicitObjectCreationExpression" to ImplicitObjectCreationExpression,
            "AddExpression" to AddExpression,
            "SubtractExpression" to SubtractExpression,
            "MultiplyExpression" to MultiplyExpression,
            "DivideExpression" to DivideExpression,
            "ModuloExpression" to ModuloExpression,
            "LeftShiftExpression" to LeftShiftExpression,
            "RightShiftExpression" to RightShiftExpression,
            "LogicalOrExpression" to LogicalOrExpression,
            "LogicalAndExpression" to LogicalAndExpression,
            "BitwiseOrExpression" to BitwiseOrExpression,
            "BitwiseAndExpression" to BitwiseAndExpression,
            "ExclusiveOrExpression" to ExclusiveOrExpression,
            "EqualsExpression" to EqualsExpression,
            "NotEqualsExpression" to NotEqualsExpression,
            "LessThanExpression" to LessThanExpression,
            "LessThanOrEqualExpression" to LessThanOrEqualExpression,
            "GreaterThanExpression" to GreaterThanExpression,
            "GreaterThanOrEqualExpression" to GreaterThanOrEqualExpression,
            "IsExpression" to IsExpression,
            "AsExpression" to AsExpression,
            "CoalesceExpression" to CoalesceExpression,
            "SimpleMemberAccessExpression" to SimpleMemberAccessExpression,
            "PointerMemberAccessExpression" to PointerMemberAccessExpression,
            "ConditionalAccessExpression" to ConditionalAccessExpression,
            "UnsignedRightShiftExpression" to UnsignedRightShiftExpression,
            "MemberBindingExpression" to MemberBindingExpression,
            "ElementBindingExpression" to ElementBindingExpression,
            "SimpleAssignmentExpression" to SimpleAssignmentExpression,
            "AddAssignmentExpression" to AddAssignmentExpression,
            "SubtractAssignmentExpression" to SubtractAssignmentExpression,
            "MultiplyAssignmentExpression" to MultiplyAssignmentExpression,
            "DivideAssignmentExpression" to DivideAssignmentExpression,
            "ModuloAssignmentExpression" to ModuloAssignmentExpression,
            "AndAssignmentExpression" to AndAssignmentExpression,
            "ExclusiveOrAssignmentExpression" to ExclusiveOrAssignmentExpression,
            "OrAssignmentExpression" to OrAssignmentExpression,
            "LeftShiftAssignmentExpression" to LeftShiftAssignmentExpression,
            "RightShiftAssignmentExpression" to RightShiftAssignmentExpression,
            "CoalesceAssignmentExpression" to CoalesceAssignmentExpression,
            "UnsignedRightShiftAssignmentExpression" to UnsignedRightShiftAssignmentExpression,
            "UnaryPlusExpression" to UnaryPlusExpression,
            "UnaryMinusExpression" to UnaryMinusExpression,
            "BitwiseNotExpression" to BitwiseNotExpression,
            "LogicalNotExpression" to LogicalNotExpression,
            "PreIncrementExpression" to PreIncrementExpression,
            "PreDecrementExpression" to PreDecrementExpression,
            "PointerIndirectionExpression" to PointerIndirectionExpression,
            "AddressOfExpression" to AddressOfExpression,
            "PostIncrementExpression" to PostIncrementExpression,
            "PostDecrementExpression" to PostDecrementExpression,
            "AwaitExpression" to AwaitExpression,
            "IndexExpression" to IndexExpression,
            "ThisExpression" to ThisExpression,
            "BaseExpression" to BaseExpression,
            "ArgListExpression" to ArgListExpression,
            "NumericLiteralExpression" to NumericLiteralExpression,
            "StringLiteralExpression" to StringLiteralExpression,
            "CharacterLiteralExpression" to CharacterLiteralExpression,
            "TrueLiteralExpression" to TrueLiteralExpression,
            "FalseLiteralExpression" to FalseLiteralExpression,
            "NullLiteralExpression" to NullLiteralExpression,
            "DefaultLiteralExpression" to DefaultLiteralExpression,
            "Utf8StringLiteralExpression" to Utf8StringLiteralExpression,
            "FieldExpression" to FieldExpression,
            "TypeOfExpression" to TypeOfExpression,
            "SizeOfExpression" to SizeOfExpression,
            "CheckedExpression" to CheckedExpression,
            "UncheckedExpression" to UncheckedExpression,
            "DefaultExpression" to DefaultExpression,
            "MakeRefExpression" to MakeRefExpression,
            "RefValueExpression" to RefValueExpression,
            "RefTypeExpression" to RefTypeExpression,
            "UnsafeExpression" to UnsafeExpression,
            "QueryExpression" to QueryExpression,
            "QueryBody" to QueryBody,
            "FromClause" to FromClause,
            "LetClause" to LetClause,
            "JoinClause" to JoinClause,
            "JoinIntoClause" to JoinIntoClause,
            "WhereClause" to WhereClause,
            "OrderByClause" to OrderByClause,
            "AscendingOrdering" to AscendingOrdering,
            "DescendingOrdering" to DescendingOrdering,
            "SelectClause" to SelectClause,
            "GroupClause" to GroupClause,
            "QueryContinuation" to QueryContinuation,
            "Block" to Block,
            "LocalDeclarationStatement" to LocalDeclarationStatement,
            "VariableDeclaration" to VariableDeclaration,
            "VariableDeclarator" to VariableDeclarator,
            "EqualsValueClause" to EqualsValueClause,
            "ExpressionStatement" to ExpressionStatement,
            "EmptyStatement" to EmptyStatement,
            "LabeledStatement" to LabeledStatement,
            "GotoStatement" to GotoStatement,
            "GotoCaseStatement" to GotoCaseStatement,
            "GotoDefaultStatement" to GotoDefaultStatement,
            "BreakStatement" to BreakStatement,
            "ContinueStatement" to ContinueStatement,
            "ReturnStatement" to ReturnStatement,
            "YieldReturnStatement" to YieldReturnStatement,
            "YieldBreakStatement" to YieldBreakStatement,
            "ThrowStatement" to ThrowStatement,
            "WhileStatement" to WhileStatement,
            "DoStatement" to DoStatement,
            "ForStatement" to ForStatement,
            "ForEachStatement" to ForEachStatement,
            "UsingStatement" to UsingStatement,
            "FixedStatement" to FixedStatement,
            "CheckedStatement" to CheckedStatement,
            "UncheckedStatement" to UncheckedStatement,
            "UnsafeStatement" to UnsafeStatement,
            "LockStatement" to LockStatement,
            "IfStatement" to IfStatement,
            "ElseClause" to ElseClause,
            "SwitchStatement" to SwitchStatement,
            "SwitchSection" to SwitchSection,
            "CaseSwitchLabel" to CaseSwitchLabel,
            "DefaultSwitchLabel" to DefaultSwitchLabel,
            "TryStatement" to TryStatement,
            "CatchClause" to CatchClause,
            "CatchDeclaration" to CatchDeclaration,
            "CatchFilterClause" to CatchFilterClause,
            "FinallyClause" to FinallyClause,
            "LocalFunctionStatement" to LocalFunctionStatement,
            "CompilationUnit" to CompilationUnit,
            "GlobalStatement" to GlobalStatement,
            "NamespaceDeclaration" to NamespaceDeclaration,
            "UsingDirective" to UsingDirective,
            "ExternAliasDirective" to ExternAliasDirective,
            "FileScopedNamespaceDeclaration" to FileScopedNamespaceDeclaration,
            "AttributeList" to AttributeList,
            "AttributeTargetSpecifier" to AttributeTargetSpecifier,
            "Attribute" to Attribute,
            "AttributeArgumentList" to AttributeArgumentList,
            "AttributeArgument" to AttributeArgument,
            "NameEquals" to NameEquals,
            "ClassDeclaration" to ClassDeclaration,
            "StructDeclaration" to StructDeclaration,
            "InterfaceDeclaration" to InterfaceDeclaration,
            "EnumDeclaration" to EnumDeclaration,
            "DelegateDeclaration" to DelegateDeclaration,
            "BaseList" to BaseList,
            "SimpleBaseType" to SimpleBaseType,
            "TypeParameterConstraintClause" to TypeParameterConstraintClause,
            "ConstructorConstraint" to ConstructorConstraint,
            "ClassConstraint" to ClassConstraint,
            "StructConstraint" to StructConstraint,
            "TypeConstraint" to TypeConstraint,
            "ExplicitInterfaceSpecifier" to ExplicitInterfaceSpecifier,
            "EnumMemberDeclaration" to EnumMemberDeclaration,
            "FieldDeclaration" to FieldDeclaration,
            "EventFieldDeclaration" to EventFieldDeclaration,
            "MethodDeclaration" to MethodDeclaration,
            "OperatorDeclaration" to OperatorDeclaration,
            "ConversionOperatorDeclaration" to ConversionOperatorDeclaration,
            "ConstructorDeclaration" to ConstructorDeclaration,
            "AllowsConstraintClause" to AllowsConstraintClause,
            "RefStructConstraint" to RefStructConstraint,
            "BaseConstructorInitializer" to BaseConstructorInitializer,
            "ThisConstructorInitializer" to ThisConstructorInitializer,
            "DestructorDeclaration" to DestructorDeclaration,
            "PropertyDeclaration" to PropertyDeclaration,
            "EventDeclaration" to EventDeclaration,
            "IndexerDeclaration" to IndexerDeclaration,
            "AccessorList" to AccessorList,
            "GetAccessorDeclaration" to GetAccessorDeclaration,
            "SetAccessorDeclaration" to SetAccessorDeclaration,
            "AddAccessorDeclaration" to AddAccessorDeclaration,
            "RemoveAccessorDeclaration" to RemoveAccessorDeclaration,
            "UnknownAccessorDeclaration" to UnknownAccessorDeclaration,
            "ParameterList" to ParameterList,
            "BracketedParameterList" to BracketedParameterList,
            "Parameter" to Parameter,
            "TypeParameterList" to TypeParameterList,
            "TypeParameter" to TypeParameter,
            "IncompleteMember" to IncompleteMember,
            "ArrowExpressionClause" to ArrowExpressionClause,
            "Interpolation" to Interpolation,
            "InterpolatedStringText" to InterpolatedStringText,
            "InterpolationAlignmentClause" to InterpolationAlignmentClause,
            "InterpolationFormatClause" to InterpolationFormatClause,
            "ShebangDirectiveTrivia" to ShebangDirectiveTrivia,
            "LoadDirectiveTrivia" to LoadDirectiveTrivia,
            "TupleType" to TupleType,
            "TupleElement" to TupleElement,
            "TupleExpression" to TupleExpression,
            "SingleVariableDesignation" to SingleVariableDesignation,
            "ParenthesizedVariableDesignation" to ParenthesizedVariableDesignation,
            "ForEachVariableStatement" to ForEachVariableStatement,
            "DeclarationPattern" to DeclarationPattern,
            "ConstantPattern" to ConstantPattern,
            "CasePatternSwitchLabel" to CasePatternSwitchLabel,
            "WhenClause" to WhenClause,
            "DiscardDesignation" to DiscardDesignation,
            "RecursivePattern" to RecursivePattern,
            "PropertyPatternClause" to PropertyPatternClause,
            "Subpattern" to Subpattern,
            "PositionalPatternClause" to PositionalPatternClause,
            "DiscardPattern" to DiscardPattern,
            "SwitchExpression" to SwitchExpression,
            "SwitchExpressionArm" to SwitchExpressionArm,
            "VarPattern" to VarPattern,
            "ParenthesizedPattern" to ParenthesizedPattern,
            "RelationalPattern" to RelationalPattern,
            "TypePattern" to TypePattern,
            "OrPattern" to OrPattern,
            "AndPattern" to AndPattern,
            "NotPattern" to NotPattern,
            "SlicePattern" to SlicePattern,
            "ListPattern" to ListPattern,
            "DeclarationExpression" to DeclarationExpression,
            "RefExpression" to RefExpression,
            "RefType" to RefType,
            "ThrowExpression" to ThrowExpression,
            "ImplicitStackAllocArrayCreationExpression" to ImplicitStackAllocArrayCreationExpression,
            "SuppressNullableWarningExpression" to SuppressNullableWarningExpression,
            "NullableDirectiveTrivia" to NullableDirectiveTrivia,
            "FunctionPointerType" to FunctionPointerType,
            "FunctionPointerParameter" to FunctionPointerParameter,
            "FunctionPointerParameterList" to FunctionPointerParameterList,
            "FunctionPointerCallingConvention" to FunctionPointerCallingConvention,
            "InitAccessorDeclaration" to InitAccessorDeclaration,
            "WithExpression" to WithExpression,
            "WithInitializerExpression" to WithInitializerExpression,
            "RecordDeclaration" to RecordDeclaration,
            "DefaultConstraint" to DefaultConstraint,
            "PrimaryConstructorBaseType" to PrimaryConstructorBaseType,
            "FunctionPointerUnmanagedCallingConventionList" to FunctionPointerUnmanagedCallingConventionList,
            "FunctionPointerUnmanagedCallingConvention" to FunctionPointerUnmanagedCallingConvention,
            "RecordStructDeclaration" to RecordStructDeclaration,
            "ExpressionColon" to ExpressionColon,
            "LineDirectivePosition" to LineDirectivePosition,
            "LineSpanDirectiveTrivia" to LineSpanDirectiveTrivia,
            "InterpolatedSingleLineRawStringStartToken" to InterpolatedSingleLineRawStringStartToken,
            "InterpolatedMultiLineRawStringStartToken" to InterpolatedMultiLineRawStringStartToken,
            "InterpolatedRawStringEndToken" to InterpolatedRawStringEndToken,
            "ScopedType" to ScopedType,
            "CollectionExpression" to CollectionExpression,
            "ExpressionElement" to ExpressionElement,
            "SpreadElement" to SpreadElement,
            "ExtensionBlockDeclaration" to ExtensionBlockDeclaration,
            "IgnoredDirectiveTrivia" to IgnoredDirectiveTrivia,
            "WithElement" to WithElement,
            "UnionDeclaration" to UnionDeclaration,
        )
    }
}
