// gen-kinds: SyntaxKind.kt, SyntaxFacts.kt and doc/XmlCharType.kt of csharp-psi-core, by reflection over the pinned
// Roslyn package.
using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace RoslynDump;

static class GenKinds
{
    const string Package = "io.github.dotnetsupport.csharp.lang";

    // Pseudo kinds with no syntax behind them: None is "no kind" (the Kotlin side uses null), List is the kind of
    // Roslyn's internal SyntaxList node, which never appears in a tree.
    static readonly HashSet<string> Skipped = ["None", "List"];

    // Doc comment trivia: one token of our lexer each, parsed lazily into Roslyn's structure (docs/csharp-psi/GRAMMAR.md, "Doc
    // comments"): the hand-written CSharpDocCommentElementType, a lazy-parseable token type.
    static readonly HashSet<string> DocComments = ["SingleLineDocumentationCommentTrivia", "MultiLineDocumentationCommentTrivia"];

    public static int Run(string outDir)
    {
        Directory.CreateDirectory(outDir);
        var roslynCommit = FindRoslynCommit();
        var version = typeof(SyntaxKind).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion ?? "?";
        // InformationalVersion is "5.9.0-1.26357.3+<commit>": the NuGet version, the build number and the source commit.
        var packageVersion = version.Split('+')[0].Split('-')[0];
        var builtFrom = version.Contains('+') ? version.Split('+')[1] : "";
        if (!roslynCommit.StartsWith(builtFrom, StringComparison.OrdinalIgnoreCase) || builtFrom.Length == 0)
            Console.Error.WriteLine($"gen-kinds: warning: the package was built from '{builtFrom}', gradle.properties pins {roslynCommit}");
        var header = $"""
            // Generated by `roslyndump gen-kinds` (tools/csharp-psi/roslyndump/GenKinds.cs) from Microsoft.CodeAnalysis.CSharp {packageVersion},
            // roslynCommit {roslynCommit}: Roslyn's SyntaxKind (src/Compilers/CSharp/Portable/Syntax/SyntaxKind.cs) and
            // SyntaxFacts (src/Compilers/CSharp/Portable/Syntax/SyntaxKindFacts.cs). Do not edit: rerun gen-kinds.
            // Roslyn: Copyright (c) .NET Foundation and Contributors, MIT License (NOTICE.md).
            """;

        // All enum names in value order; an alias (a second name for one value) refers to the first name.
        var fields = typeof(SyntaxKind).GetFields(BindingFlags.Public | BindingFlags.Static)
            .Select(f => (Name: f.Name, Kind: (SyntaxKind)f.GetValue(null)!, Obsolete: f.GetCustomAttribute<ObsoleteAttribute>() != null))
            .OrderBy(f => (int)f.Kind).ThenBy(f => f.Name, StringComparer.Ordinal)
            .ToList();
        var primary = new Dictionary<SyntaxKind, string>();
        var kinds = new List<(string Name, SyntaxKind Kind, string? AliasOf, bool Token)>();
        foreach (var (name, kind, obsolete) in fields)
        {
            if (Skipped.Contains(name)) continue;
            if (obsolete) Console.Error.WriteLine($"gen-kinds: obsolete kind {name} kept");
            if (primary.TryGetValue(kind, out var first))
            {
                kinds.Add((name, kind, first, false));
                continue;
            }
            primary[kind] = name;
            // Trivia are tokens of our lexer (docs/csharp-psi/GRAMMAR.md), including the two kinds IsTrivia leaves out:
            // SkippedTokensTrivia and PreprocessingMessageTrivia.
            var token = SyntaxFacts.IsAnyToken(kind) || SyntaxFacts.IsTrivia(kind) || name.EndsWith("Trivia");
            if (token != (name.EndsWith("Token") || name.EndsWith("Keyword") || name.EndsWith("Trivia")))
                Console.Error.WriteLine($"gen-kinds: note: {name} classified as {(token ? "token" : "node")}");
            kinds.Add((name, kind, null, token));
        }
        string? Name(SyntaxKind k) => primary.GetValueOrDefault(k);

        WriteSyntaxKind(Path.Combine(outDir, "SyntaxKind.kt"), header, kinds);
        WriteSyntaxFacts(Path.Combine(outDir, "SyntaxFacts.kt"), header, primary, Name);
        WriteXmlCharType(Path.Combine(outDir, "doc", "XmlCharType.kt"), packageVersion, roslynCommit);
        Console.Error.WriteLine($"gen-kinds: {kinds.Count(k => k.AliasOf == null)} kinds ({kinds.Count(k => k.AliasOf == null && k.Token)} token types, " +
                                $"{kinds.Count(k => k.AliasOf == null && !k.Token)} element types), {kinds.Count(k => k.AliasOf != null)} aliases, skipped: {string.Join(", ", Skipped)}");
        ReportVisibility();
        return 0;
    }

    static void WriteSyntaxKind(string path, string header, List<(string Name, SyntaxKind Kind, string? AliasOf, bool Token)> kinds)
    {
        var sb = new StringBuilder();
        sb.Append(header).Append('\n');
        sb.Append($$"""
            package {{Package}}

            import com.intellij.psi.tree.IElementType

            /**
             * Roslyn's `SyntaxKind`, one element type per kind, named exactly as in Roslyn so that ported parser code reads as
             * Roslyn's (`SyntaxKind.PlusToken`). Tokens and trivia are [CSharpTokenType], nodes [CSharpElementType]; the two
             * doc comment trivia kinds are [CSharpDocCommentElementType] (lazily parsed tokens).
             * Skipped pseudo kinds: `None` (null on this side) and `List` (Roslyn's internal list node).
             */
            @Suppress("unused")
            object SyntaxKind {

            """);
        foreach (var (name, kind, aliasOf, token) in kinds)
        {
            if (aliasOf != null) sb.Append($"    /** Alias of [{aliasOf}] (same value in Roslyn). */\n    @JvmField val {name}: IElementType = {aliasOf}\n");
            else sb.Append($"    /** {(int)kind} */ @JvmField val {name}: IElementType = {(DocComments.Contains(name) ? "CSharpDocCommentElementType" : token ? "CSharpTokenType" : "CSharpElementType")}(\"{name}\")\n");
        }
        sb.Append("""

                /** Every kind by its Roslyn name (aliases included). */
                val byName: Map<String, IElementType> by lazy {
                    hashMapOf(

            """);
        foreach (var (name, _, _, _) in kinds) sb.Append($"            \"{name}\" to {name},\n");
        sb.Append("        )\n    }\n}\n");
        File.WriteAllText(path, sb.ToString());
    }

    static void WriteSyntaxFacts(string path, string header, Dictionary<SyntaxKind, string> primary, Func<SyntaxKind, string?> name)
    {
        var all = primary.Keys.OrderBy(k => (int)k).ToList();
        var sb = new StringBuilder();
        sb.Append(header).Append('\n');
        sb.Append($$"""
            package {{Package}}

            import com.intellij.psi.tree.IElementType
            import com.intellij.psi.tree.TokenSet
            import {{Package}}.SyntaxKind as K

            /**
             * Tables of Roslyn's public `SyntaxFacts`, evaluated over every kind: keyword texts, fixed token texts, every public
             * `bool IsX(SyntaxKind)` as a [TokenSet] plus `isX`, every public `SyntaxKind GetX(SyntaxKind)` as `getX` returning
             * null for Roslyn's `SyntaxKind.None`. Internal helpers of Roslyn's parser are ported by hand, not generated.
             */
            @Suppress("unused", "FunctionName", "PropertyName")
            object CSharpSyntaxFacts {

            """);

        // Keyword texts. GetKeywordKind/GetContextualKeywordKind/GetPreprocessorKeywordKind are checked to map back.
        void TextMap(string prop, string doc, IEnumerable<SyntaxKind> source, Func<string, SyntaxKind> back)
        {
            var entries = source.Distinct().OrderBy(k => (int)k)
                .Select(k => (Text: SyntaxFacts.GetText(k), Kind: k))
                .Where(e => e.Text.Length > 0 && back(e.Text) == e.Kind && name(e.Kind) != null)
                .ToList();
            sb.Append($"    /** {doc} */\n    @JvmField val {prop}: Map<String, IElementType> = {prop}()\n");
            sb.Append($"    private fun {prop}(): Map<String, IElementType> = hashMapOf(\n");
            foreach (var (text, kind) in entries) sb.Append($"        {Kt(text)} to K.{name(kind)},\n");
            sb.Append("    )\n\n");
        }
        TextMap("reservedKeywords", "Reserved keyword text to kind (`SyntaxFacts.GetKeywordKind`).",
            SyntaxFacts.GetReservedKeywordKinds(), SyntaxFacts.GetKeywordKind);
        // All kinds, not GetContextualKeywordKinds(): that one walks YieldKeyword..SafeKeyword only and misses `var` and
        // `_`, which GetContextualKeywordKind (what Roslyn's lexer calls) does return.
        TextMap("contextualKeywords", "Contextual keyword text to kind (`SyntaxFacts.GetContextualKeywordKind`).",
            Enum.GetValues<SyntaxKind>(), SyntaxFacts.GetContextualKeywordKind);
        TextMap("preprocessorKeywords", "Preprocessor keyword text to kind (`SyntaxFacts.GetPreprocessorKeywordKind`).",
            SyntaxFacts.GetPreprocessorKeywordKinds(), SyntaxFacts.GetPreprocessorKeywordKind);
        sb.Append("""
                fun getKeywordKind(text: String): IElementType? = reservedKeywords[text]
                fun getContextualKeywordKind(text: String): IElementType? = contextualKeywords[text]
                fun getPreprocessorKeywordKind(text: String): IElementType? = preprocessorKeywords[text]


            """);

        // Fixed texts.
        sb.Append("    /** Kind to its fixed text (`SyntaxFacts.GetText`), for tokens and keywords that have one. */\n");
        sb.Append("    @JvmField val fixedText: Map<IElementType, String> = fixedText()\n");
        sb.Append("    private fun fixedText(): Map<IElementType, String> = hashMapOf(\n");
        foreach (var k in all)
            if (SyntaxFacts.GetText(k) is { Length: > 0 } text) sb.Append($"        K.{name(k)} to {Kt(text)},\n");
        sb.Append("    )\n\n    fun getText(kind: IElementType): String = fixedText[kind] ?: \"\"\n\n");

        // Kind lists Roslyn exposes as enumerations.
        void EnumSet(string prop, string method, IEnumerable<SyntaxKind> source)
        {
            sb.Append($"    /** `SyntaxFacts.{method}()` */\n    @JvmField val {prop}: TokenSet = TokenSet.create(\n");
            foreach (var k in source.Distinct().OrderBy(k => (int)k)) if (name(k) is { } n) sb.Append($"        K.{n},\n");
            sb.Append("    )\n\n");
        }
        EnumSet("KeywordKinds", "GetKeywordKinds", SyntaxFacts.GetKeywordKinds());
        EnumSet("ReservedKeywordKinds", "GetReservedKeywordKinds", SyntaxFacts.GetReservedKeywordKinds());
        EnumSet("ContextualKeywordKinds", "GetContextualKeywordKinds", SyntaxFacts.GetContextualKeywordKinds());
        EnumSet("PreprocessorKeywordKinds", "GetPreprocessorKeywordKinds", SyntaxFacts.GetPreprocessorKeywordKinds());
        EnumSet("PunctuationKinds", "GetPunctuationKinds", SyntaxFacts.GetPunctuationKinds());

        // Every public bool IsX(SyntaxKind) and SyntaxKind GetX(SyntaxKind).
        var methods = typeof(SyntaxFacts).GetMethods(BindingFlags.Public | BindingFlags.Static)
            .Where(m => m.GetParameters() is [{ ParameterType: var p }] && p == typeof(SyntaxKind))
            .OrderBy(m => m.Name, StringComparer.Ordinal)
            .ToList();
        foreach (var m in methods.Where(m => m.ReturnType == typeof(bool)))
        {
            var members = all.Where(k => Invoke(m, k) is true).ToList();
            var prop = m.Name;
            sb.Append($"    /** Kinds for which `SyntaxFacts.{m.Name}` is true. */\n");
            sb.Append($"    @JvmField val {prop}: TokenSet = {prop}()\n");
            sb.Append($"    private fun {prop}(): TokenSet = TokenSet.create(\n");
            foreach (var k in members) sb.Append($"        K.{name(k)},\n");
            sb.Append("    )\n");
            sb.Append($"    fun {Lower(m.Name)}(kind: IElementType?): Boolean = {prop}.contains(kind)\n\n");
        }
        foreach (var m in methods.Where(m => m.ReturnType == typeof(SyntaxKind)))
        {
            var pairs = all.Select(k => (From: k, To: Invoke(m, k) is SyntaxKind to ? name(to) : null))
                .Where(p => p.To != null).ToList();
            var prop = Lower(m.Name) + "Map";
            sb.Append($"    /** `SyntaxFacts.{m.Name}` over every kind; null for `SyntaxKind.None`. */\n");
            sb.Append($"    fun {Lower(m.Name)}(kind: IElementType?): IElementType? = {prop}[kind]\n");
            sb.Append($"    private val {prop}: Map<IElementType, IElementType> = {prop}()\n");
            sb.Append($"    private fun {prop}(): Map<IElementType, IElementType> = hashMapOf(\n");
            foreach (var (from, to) in pairs) sb.Append($"        K.{name(from)} to K.{to},\n");
            sb.Append("    )\n\n");
        }
        sb.Length -= 1; // the last blank line
        sb.Append("}\n");
        File.WriteAllText(path, sb.ToString());
        Console.Error.WriteLine($"gen-kinds: SyntaxFacts methods tabulated: {string.Join(", ", methods.Select(m => m.Name))}");
    }

    // Roslyn's XmlCharType (src/Compilers/Core/Portable/InternalUtilities/XmlCharType.cs, internal): the two predicates
    // the XML doc comment lexer uses (Lexer.IsXmlNameStartChar / IsXmlNameChar), tabulated over every UTF-16 unit.
    static void WriteXmlCharType(string path, string packageVersion, string roslynCommit)
    {
        var type = new[] { typeof(SyntaxKind).Assembly, typeof(Microsoft.CodeAnalysis.SyntaxNode).Assembly }
            .Select(a => a.GetType("Roslyn.Utilities.XmlCharType") ?? a.GetType("Microsoft.CodeAnalysis.XmlCharType"))
            .FirstOrDefault(t => t != null)
            ?? throw new InvalidOperationException("XmlCharType not found in the Roslyn assemblies");
        string Ranges(string method)
        {
            var m = type.GetMethod(method, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static, [typeof(char)])
                ?? throw new InvalidOperationException($"XmlCharType.{method}(char) not found");
            var sb = new StringBuilder();
            var count = 0;
            for (var c = 0; c <= 0xFFFF; c++)
            {
                if (m.Invoke(null, [(char)c]) is not true) continue;
                var start = c;
                while (c + 1 <= 0xFFFF && m.Invoke(null, [(char)(c + 1)]) is true) c++;
                if (count % 6 == 0) sb.Append("\n        ");
                else sb.Append(' ');
                sb.Append($"0x{start:X4}, 0x{c:X4},");
                count++;
            }
            return sb.ToString();
        }
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        var text = $$"""
            // Generated by `roslyndump gen-kinds` (tools/csharp-psi/roslyndump/GenKinds.cs) from Microsoft.CodeAnalysis {{packageVersion}},
            // roslynCommit {{roslynCommit}}: Roslyn's XmlCharType (src/Compilers/Core/Portable/InternalUtilities/XmlCharType.cs).
            // Do not edit: rerun gen-kinds.
            // Roslyn: Copyright (c) .NET Foundation and Contributors, MIT License (NOTICE.md).
            package {{Package}}.doc

            import java.util.BitSet

            /**
             * Roslyn's `XmlCharType.IsStartNCNameCharXml4e` and `IsNCNameCharXml4e` (XML 1.0 4th edition names without `:`),
             * the classes `Lexer.IsXmlNameStartChar` / `IsXmlNameChar` use, as inclusive ranges of UTF-16 units.
             */
            object XmlCharType {
                private val startNCNameRanges = intArrayOf({{Ranges("IsStartNCNameCharXml4e")}}
                )

                private val ncNameRanges = intArrayOf({{Ranges("IsNCNameCharXml4e")}}
                )

                private val startNCName: BitSet = bits(startNCNameRanges)
                private val ncName: BitSet = bits(ncNameRanges)

                private fun bits(ranges: IntArray): BitSet = BitSet(0x10000).also { b ->
                    for (i in ranges.indices step 2) b.set(ranges[i], ranges[i + 1] + 1)
                }

                @JvmStatic fun isStartNCNameCharXml4e(ch: Char): Boolean = startNCName[ch.code]
                @JvmStatic fun isNCNameCharXml4e(ch: Char): Boolean = ncName[ch.code]
            }

            """;
        File.WriteAllText(path, text);
    }

    static object? Invoke(MethodInfo m, SyntaxKind k)
    {
        try { return m.Invoke(null, [k]); }
        catch (TargetInvocationException) { return null; }
    }

    // Functions Roslyn's parser relies on: which of them the package exposes (the rest is ported by hand).
    static void ReportVisibility()
    {
        string[] wanted =
        [
            "GetBinaryExpression", "GetPrefixUnaryExpression", "GetPostfixUnaryExpression", "GetAssignmentExpression",
            "GetPrimaryFunction", "IsPredefinedType", "GetLiteralExpression", "GetCheckStatement", "GetInstanceExpression",
            "GetAccessorDeclarationKind", "GetTypeDeclarationKind", "IsBinaryExpressionOperatorToken",
            "IsPrefixUnaryExpressionOperatorToken", "IsPostfixUnaryExpressionToken", "IsAssignmentExpressionOperatorToken",
            "GetKeywordKind", "GetContextualKeywordKind", "GetText", "IsReservedKeyword", "IsContextualKeyword", "IsPunctuation",
        ];
        foreach (var w in wanted)
        {
            var pub = typeof(SyntaxFacts).GetMethods(BindingFlags.Public | BindingFlags.Static).Any(m => m.Name == w);
            if (!pub) Console.Error.WriteLine($"gen-kinds: {w} is not public");
        }
        var internals = typeof(SyntaxFacts).GetMethods(BindingFlags.NonPublic | BindingFlags.Static)
            .Where(m => m.GetParameters().Any(p => p.ParameterType == typeof(SyntaxKind)))
            .Select(m => m.Name).Distinct().Order(StringComparer.Ordinal);
        Console.Error.WriteLine($"gen-kinds: internal SyntaxFacts methods taking a SyntaxKind (not generated): {string.Join(", ", internals)}");
    }

    static string Lower(string s) => char.ToLowerInvariant(s[0]) + s[1..];

    // A Kotlin string literal.
    static string Kt(string s)
    {
        var sb = new StringBuilder("\"");
        foreach (var c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '$': sb.Append("\\$"); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < ' ' || c > '~') sb.Append($"\\u{(int)c:x4}");
                    else sb.Append(c);
                    break;
            }
        }
        return sb.Append('"').ToString();
    }

    static string FindRoslynCommit()
    {
        foreach (var start in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
        {
            for (var dir = new DirectoryInfo(start); dir != null; dir = dir.Parent)
            {
                var props = Path.Combine(dir.FullName, "gradle.properties");
                if (!File.Exists(props)) continue;
                var line = File.ReadLines(props).FirstOrDefault(l => l.StartsWith("roslynCommit="));
                if (line != null) return line["roslynCommit=".Length..].Trim();
            }
        }
        throw new InvalidOperationException("roslynCommit not found in a gradle.properties above the current directory");
    }
}
