using System.Windows;

namespace LegacyWpf
{
    public partial class MainWindow : Window
    {
        private int clicks;

        public MainWindow()
        {
            InitializeComponent();
            // Greeting is a field the XAML compiler generates: with the .NET SDK there is none and the build fails
            Greeting.Text = "Built by MSBuild of Visual Studio";
            // TYPE:wpf-generated (0.1.82) — open NetFramework.sln, Build (MSBuild of Visual Studio), then type `Greeting.Txet = "";`.
            // EXPECT: a red «CS1061: 'TextBlock' does not contain a definition for 'Txet'…» on `Txet`; `InitializeComponent` and `Greeting`
            // are not red, Ctrl+B on `Greeting` opens obj/Debug/MainWindow.g.cs with the banner «Generated by the build (XAML from
            // MainWindow.xaml) for LegacyWpf…». Solution view: LegacyWpf → Dependencies → Analyzers → Generated by build →
            // XAML (MarkupCompilePass1) → App.g.cs, MainWindow.g.cs. Before the first build: no semantic errors at all (nothing is known
            // of the XAML); after an edit of MainWindow.xaml is saved the banner says «Out of date» until the next build
        }

        private void OnClick(object sender, RoutedEventArgs e)
        {
            clicks++;
            Greeting.Text = "Clicks: " + clicks; // BP:legacy-wpf-click — Debug (or Attach to Process), click the button: stops here; EXPECT: clicks is the number of clicks
        }
    }
}
