// Generated by `roslyndump gen-psi` (tools/csharp-psi/roslyndump/GenPsi.cs) from Roslyn's src/Compilers/CSharp/Portable/Syntax/Syntax.xml,
// roslynCommit 35d9211b841e7613c1d2f8f5af6d628ace696c4c. Do not edit: rerun gen-psi (tools/csharp-psi/roslyndump/README.md).
// Roslyn: Copyright (c) .NET Foundation and Contributors, MIT License (NOTICE.md).
package io.github.dotnetsupport.csharp.lang.psi.impl

import com.intellij.psi.tree.TokenSet
import io.github.dotnetsupport.csharp.lang.SyntaxKind as K

/**
 * The node kinds of every Roslyn class used as a field type: the kinds of all concrete classes derived from it.
 * A body block ([io.github.dotnetsupport.csharp.lang.parser.CSharpBodyBlockType]) is matched as `Block`.
 */
@Suppress("unused")
object CSharpSyntaxKindSets {
    /** `AccessorDeclarationSyntax` */
    @JvmField val ACCESSOR_DECLARATION: TokenSet = setAccessorDeclaration()
    private fun setAccessorDeclaration(): TokenSet = TokenSet.create(
        K.AddAccessorDeclaration,
        K.GetAccessorDeclaration,
        K.InitAccessorDeclaration,
        K.RemoveAccessorDeclaration,
        K.SetAccessorDeclaration,
        K.UnknownAccessorDeclaration,
    )

    /** `AccessorListSyntax` */
    @JvmField val ACCESSOR_LIST: TokenSet = setAccessorList()
    private fun setAccessorList(): TokenSet = TokenSet.create(
        K.AccessorList,
    )

    /** `AllowsConstraintSyntax` */
    @JvmField val ALLOWS_CONSTRAINT: TokenSet = setAllowsConstraint()
    private fun setAllowsConstraint(): TokenSet = TokenSet.create(
        K.RefStructConstraint,
    )

    /** `AnonymousObjectMemberDeclaratorSyntax` */
    @JvmField val ANONYMOUS_OBJECT_MEMBER_DECLARATOR: TokenSet = setAnonymousObjectMemberDeclarator()
    private fun setAnonymousObjectMemberDeclarator(): TokenSet = TokenSet.create(
        K.AnonymousObjectMemberDeclarator,
    )

    /** `ArgumentListSyntax` */
    @JvmField val ARGUMENT_LIST: TokenSet = setArgumentList()
    private fun setArgumentList(): TokenSet = TokenSet.create(
        K.ArgumentList,
    )

    /** `ArgumentSyntax` */
    @JvmField val ARGUMENT: TokenSet = setArgument()
    private fun setArgument(): TokenSet = TokenSet.create(
        K.Argument,
    )

    /** `ArrayRankSpecifierSyntax` */
    @JvmField val ARRAY_RANK_SPECIFIER: TokenSet = setArrayRankSpecifier()
    private fun setArrayRankSpecifier(): TokenSet = TokenSet.create(
        K.ArrayRankSpecifier,
    )

    /** `ArrayTypeSyntax` */
    @JvmField val ARRAY_TYPE: TokenSet = setArrayType()
    private fun setArrayType(): TokenSet = TokenSet.create(
        K.ArrayType,
    )

    /** `ArrowExpressionClauseSyntax` */
    @JvmField val ARROW_EXPRESSION_CLAUSE: TokenSet = setArrowExpressionClause()
    private fun setArrowExpressionClause(): TokenSet = TokenSet.create(
        K.ArrowExpressionClause,
    )

    /** `AttributeArgumentListSyntax` */
    @JvmField val ATTRIBUTE_ARGUMENT_LIST: TokenSet = setAttributeArgumentList()
    private fun setAttributeArgumentList(): TokenSet = TokenSet.create(
        K.AttributeArgumentList,
    )

    /** `AttributeArgumentSyntax` */
    @JvmField val ATTRIBUTE_ARGUMENT: TokenSet = setAttributeArgument()
    private fun setAttributeArgument(): TokenSet = TokenSet.create(
        K.AttributeArgument,
    )

    /** `AttributeListSyntax` */
    @JvmField val ATTRIBUTE_LIST: TokenSet = setAttributeList()
    private fun setAttributeList(): TokenSet = TokenSet.create(
        K.AttributeList,
    )

    /** `AttributeSyntax` */
    @JvmField val ATTRIBUTE: TokenSet = setAttribute()
    private fun setAttribute(): TokenSet = TokenSet.create(
        K.Attribute,
    )

    /** `AttributeTargetSpecifierSyntax` */
    @JvmField val ATTRIBUTE_TARGET_SPECIFIER: TokenSet = setAttributeTargetSpecifier()
    private fun setAttributeTargetSpecifier(): TokenSet = TokenSet.create(
        K.AttributeTargetSpecifier,
    )

    /** `BaseExpressionColonSyntax` */
    @JvmField val BASE_EXPRESSION_COLON: TokenSet = setBaseExpressionColon()
    private fun setBaseExpressionColon(): TokenSet = TokenSet.create(
        K.ExpressionColon,
        K.NameColon,
    )

    /** `BaseListSyntax` */
    @JvmField val BASE_LIST: TokenSet = setBaseList()
    private fun setBaseList(): TokenSet = TokenSet.create(
        K.BaseList,
    )

    /** `BaseTypeSyntax` */
    @JvmField val BASE_TYPE: TokenSet = setBaseType()
    private fun setBaseType(): TokenSet = TokenSet.create(
        K.PrimaryConstructorBaseType,
        K.SimpleBaseType,
    )

    /** `BlockSyntax` */
    @JvmField val BLOCK: TokenSet = setBlock()
    private fun setBlock(): TokenSet = TokenSet.create(
        K.Block,
    )

    /** `BracketedArgumentListSyntax` */
    @JvmField val BRACKETED_ARGUMENT_LIST: TokenSet = setBracketedArgumentList()
    private fun setBracketedArgumentList(): TokenSet = TokenSet.create(
        K.BracketedArgumentList,
    )

    /** `BracketedParameterListSyntax` */
    @JvmField val BRACKETED_PARAMETER_LIST: TokenSet = setBracketedParameterList()
    private fun setBracketedParameterList(): TokenSet = TokenSet.create(
        K.BracketedParameterList,
    )

    /** `CatchClauseSyntax` */
    @JvmField val CATCH_CLAUSE: TokenSet = setCatchClause()
    private fun setCatchClause(): TokenSet = TokenSet.create(
        K.CatchClause,
    )

    /** `CatchDeclarationSyntax` */
    @JvmField val CATCH_DECLARATION: TokenSet = setCatchDeclaration()
    private fun setCatchDeclaration(): TokenSet = TokenSet.create(
        K.CatchDeclaration,
    )

    /** `CatchFilterClauseSyntax` */
    @JvmField val CATCH_FILTER_CLAUSE: TokenSet = setCatchFilterClause()
    private fun setCatchFilterClause(): TokenSet = TokenSet.create(
        K.CatchFilterClause,
    )

    /** `CollectionElementSyntax` */
    @JvmField val COLLECTION_ELEMENT: TokenSet = setCollectionElement()
    private fun setCollectionElement(): TokenSet = TokenSet.create(
        K.ExpressionElement,
        K.SpreadElement,
        K.WithElement,
    )

    /** `ConstructorInitializerSyntax` */
    @JvmField val CONSTRUCTOR_INITIALIZER: TokenSet = setConstructorInitializer()
    private fun setConstructorInitializer(): TokenSet = TokenSet.create(
        K.BaseConstructorInitializer,
        K.ThisConstructorInitializer,
    )

    /** `CrefBracketedParameterListSyntax` */
    @JvmField val CREF_BRACKETED_PARAMETER_LIST: TokenSet = setCrefBracketedParameterList()
    private fun setCrefBracketedParameterList(): TokenSet = TokenSet.create(
        K.CrefBracketedParameterList,
    )

    /** `CrefParameterListSyntax` */
    @JvmField val CREF_PARAMETER_LIST: TokenSet = setCrefParameterList()
    private fun setCrefParameterList(): TokenSet = TokenSet.create(
        K.CrefParameterList,
    )

    /** `CrefParameterSyntax` */
    @JvmField val CREF_PARAMETER: TokenSet = setCrefParameter()
    private fun setCrefParameter(): TokenSet = TokenSet.create(
        K.CrefParameter,
    )

    /** `CrefSyntax` */
    @JvmField val CREF: TokenSet = setCref()
    private fun setCref(): TokenSet = TokenSet.create(
        K.ConversionOperatorMemberCref,
        K.ExtensionMemberCref,
        K.IndexerMemberCref,
        K.NameMemberCref,
        K.OperatorMemberCref,
        K.QualifiedCref,
        K.TypeCref,
    )

    /** `ElseClauseSyntax` */
    @JvmField val ELSE_CLAUSE: TokenSet = setElseClause()
    private fun setElseClause(): TokenSet = TokenSet.create(
        K.ElseClause,
    )

    /** `EnumMemberDeclarationSyntax` */
    @JvmField val ENUM_MEMBER_DECLARATION: TokenSet = setEnumMemberDeclaration()
    private fun setEnumMemberDeclaration(): TokenSet = TokenSet.create(
        K.EnumMemberDeclaration,
    )

    /** `EqualsValueClauseSyntax` */
    @JvmField val EQUALS_VALUE_CLAUSE: TokenSet = setEqualsValueClause()
    private fun setEqualsValueClause(): TokenSet = TokenSet.create(
        K.EqualsValueClause,
    )

    /** `ExplicitInterfaceSpecifierSyntax` */
    @JvmField val EXPLICIT_INTERFACE_SPECIFIER: TokenSet = setExplicitInterfaceSpecifier()
    private fun setExplicitInterfaceSpecifier(): TokenSet = TokenSet.create(
        K.ExplicitInterfaceSpecifier,
    )

    /** `ExpressionSyntax` */
    @JvmField val EXPRESSION: TokenSet = setExpression()
    private fun setExpression(): TokenSet = TokenSet.create(
        K.AddAssignmentExpression,
        K.AddExpression,
        K.AddressOfExpression,
        K.AliasQualifiedName,
        K.AndAssignmentExpression,
        K.AnonymousMethodExpression,
        K.AnonymousObjectCreationExpression,
        K.ArgListExpression,
        K.ArrayCreationExpression,
        K.ArrayInitializerExpression,
        K.ArrayType,
        K.AsExpression,
        K.AwaitExpression,
        K.BaseExpression,
        K.BitwiseAndExpression,
        K.BitwiseNotExpression,
        K.BitwiseOrExpression,
        K.CastExpression,
        K.CharacterLiteralExpression,
        K.CheckedExpression,
        K.CoalesceAssignmentExpression,
        K.CoalesceExpression,
        K.CollectionExpression,
        K.CollectionInitializerExpression,
        K.ComplexElementInitializerExpression,
        K.ConditionalAccessExpression,
        K.ConditionalExpression,
        K.DeclarationExpression,
        K.DefaultExpression,
        K.DefaultLiteralExpression,
        K.DivideAssignmentExpression,
        K.DivideExpression,
        K.ElementAccessExpression,
        K.ElementBindingExpression,
        K.EqualsExpression,
        K.ExclusiveOrAssignmentExpression,
        K.ExclusiveOrExpression,
        K.FalseLiteralExpression,
        K.FieldExpression,
        K.FunctionPointerType,
        K.GenericName,
        K.GreaterThanExpression,
        K.GreaterThanOrEqualExpression,
        K.IdentifierName,
        K.ImplicitArrayCreationExpression,
        K.ImplicitElementAccess,
        K.ImplicitObjectCreationExpression,
        K.ImplicitStackAllocArrayCreationExpression,
        K.IndexExpression,
        K.InterpolatedStringExpression,
        K.InvocationExpression,
        K.IsExpression,
        K.IsPatternExpression,
        K.LeftShiftAssignmentExpression,
        K.LeftShiftExpression,
        K.LessThanExpression,
        K.LessThanOrEqualExpression,
        K.LogicalAndExpression,
        K.LogicalNotExpression,
        K.LogicalOrExpression,
        K.MakeRefExpression,
        K.MemberBindingExpression,
        K.ModuloAssignmentExpression,
        K.ModuloExpression,
        K.MultiplyAssignmentExpression,
        K.MultiplyExpression,
        K.NotEqualsExpression,
        K.NullLiteralExpression,
        K.NullableType,
        K.NumericLiteralExpression,
        K.ObjectCreationExpression,
        K.ObjectInitializerExpression,
        K.OmittedArraySizeExpression,
        K.OmittedTypeArgument,
        K.OrAssignmentExpression,
        K.ParenthesizedExpression,
        K.ParenthesizedLambdaExpression,
        K.PointerIndirectionExpression,
        K.PointerMemberAccessExpression,
        K.PointerType,
        K.PostDecrementExpression,
        K.PostIncrementExpression,
        K.PreDecrementExpression,
        K.PreIncrementExpression,
        K.PredefinedType,
        K.QualifiedName,
        K.QueryExpression,
        K.RangeExpression,
        K.RefExpression,
        K.RefType,
        K.RefTypeExpression,
        K.RefValueExpression,
        K.RightShiftAssignmentExpression,
        K.RightShiftExpression,
        K.ScopedType,
        K.SimpleAssignmentExpression,
        K.SimpleLambdaExpression,
        K.SimpleMemberAccessExpression,
        K.SizeOfExpression,
        K.StackAllocArrayCreationExpression,
        K.StringLiteralExpression,
        K.SubtractAssignmentExpression,
        K.SubtractExpression,
        K.SuppressNullableWarningExpression,
        K.SwitchExpression,
        K.ThisExpression,
        K.ThrowExpression,
        K.TrueLiteralExpression,
        K.TupleExpression,
        K.TupleType,
        K.TypeOfExpression,
        K.UnaryMinusExpression,
        K.UnaryPlusExpression,
        K.UncheckedExpression,
        K.UnsafeExpression,
        K.UnsignedRightShiftAssignmentExpression,
        K.UnsignedRightShiftExpression,
        K.Utf8StringLiteralExpression,
        K.WithExpression,
        K.WithInitializerExpression,
    )

    /** `ExternAliasDirectiveSyntax` */
    @JvmField val EXTERN_ALIAS_DIRECTIVE: TokenSet = setExternAliasDirective()
    private fun setExternAliasDirective(): TokenSet = TokenSet.create(
        K.ExternAliasDirective,
    )

    /** `FinallyClauseSyntax` */
    @JvmField val FINALLY_CLAUSE: TokenSet = setFinallyClause()
    private fun setFinallyClause(): TokenSet = TokenSet.create(
        K.FinallyClause,
    )

    /** `FromClauseSyntax` */
    @JvmField val FROM_CLAUSE: TokenSet = setFromClause()
    private fun setFromClause(): TokenSet = TokenSet.create(
        K.FromClause,
    )

    /** `FunctionPointerCallingConventionSyntax` */
    @JvmField val FUNCTION_POINTER_CALLING_CONVENTION: TokenSet = setFunctionPointerCallingConvention()
    private fun setFunctionPointerCallingConvention(): TokenSet = TokenSet.create(
        K.FunctionPointerCallingConvention,
    )

    /** `FunctionPointerParameterListSyntax` */
    @JvmField val FUNCTION_POINTER_PARAMETER_LIST: TokenSet = setFunctionPointerParameterList()
    private fun setFunctionPointerParameterList(): TokenSet = TokenSet.create(
        K.FunctionPointerParameterList,
    )

    /** `FunctionPointerParameterSyntax` */
    @JvmField val FUNCTION_POINTER_PARAMETER: TokenSet = setFunctionPointerParameter()
    private fun setFunctionPointerParameter(): TokenSet = TokenSet.create(
        K.FunctionPointerParameter,
    )

    /** `FunctionPointerUnmanagedCallingConventionListSyntax` */
    @JvmField val FUNCTION_POINTER_UNMANAGED_CALLING_CONVENTION_LIST: TokenSet = setFunctionPointerUnmanagedCallingConventionList()
    private fun setFunctionPointerUnmanagedCallingConventionList(): TokenSet = TokenSet.create(
        K.FunctionPointerUnmanagedCallingConventionList,
    )

    /** `FunctionPointerUnmanagedCallingConventionSyntax` */
    @JvmField val FUNCTION_POINTER_UNMANAGED_CALLING_CONVENTION: TokenSet = setFunctionPointerUnmanagedCallingConvention()
    private fun setFunctionPointerUnmanagedCallingConvention(): TokenSet = TokenSet.create(
        K.FunctionPointerUnmanagedCallingConvention,
    )

    /** `IdentifierNameSyntax` */
    @JvmField val IDENTIFIER_NAME: TokenSet = setIdentifierName()
    private fun setIdentifierName(): TokenSet = TokenSet.create(
        K.IdentifierName,
    )

    /** `InitializerExpressionSyntax` */
    @JvmField val INITIALIZER_EXPRESSION: TokenSet = setInitializerExpression()
    private fun setInitializerExpression(): TokenSet = TokenSet.create(
        K.ArrayInitializerExpression,
        K.CollectionInitializerExpression,
        K.ComplexElementInitializerExpression,
        K.ObjectInitializerExpression,
        K.WithInitializerExpression,
    )

    /** `InterpolatedStringContentSyntax` */
    @JvmField val INTERPOLATED_STRING_CONTENT: TokenSet = setInterpolatedStringContent()
    private fun setInterpolatedStringContent(): TokenSet = TokenSet.create(
        K.InterpolatedStringText,
        K.Interpolation,
    )

    /** `InterpolationAlignmentClauseSyntax` */
    @JvmField val INTERPOLATION_ALIGNMENT_CLAUSE: TokenSet = setInterpolationAlignmentClause()
    private fun setInterpolationAlignmentClause(): TokenSet = TokenSet.create(
        K.InterpolationAlignmentClause,
    )

    /** `InterpolationFormatClauseSyntax` */
    @JvmField val INTERPOLATION_FORMAT_CLAUSE: TokenSet = setInterpolationFormatClause()
    private fun setInterpolationFormatClause(): TokenSet = TokenSet.create(
        K.InterpolationFormatClause,
    )

    /** `JoinIntoClauseSyntax` */
    @JvmField val JOIN_INTO_CLAUSE: TokenSet = setJoinIntoClause()
    private fun setJoinIntoClause(): TokenSet = TokenSet.create(
        K.JoinIntoClause,
    )

    /** `LineDirectivePositionSyntax` */
    @JvmField val LINE_DIRECTIVE_POSITION: TokenSet = setLineDirectivePosition()
    private fun setLineDirectivePosition(): TokenSet = TokenSet.create(
        K.LineDirectivePosition,
    )

    /** `MemberCrefSyntax` */
    @JvmField val MEMBER_CREF: TokenSet = setMemberCref()
    private fun setMemberCref(): TokenSet = TokenSet.create(
        K.ConversionOperatorMemberCref,
        K.ExtensionMemberCref,
        K.IndexerMemberCref,
        K.NameMemberCref,
        K.OperatorMemberCref,
    )

    /** `MemberDeclarationSyntax` */
    @JvmField val MEMBER_DECLARATION: TokenSet = setMemberDeclaration()
    private fun setMemberDeclaration(): TokenSet = TokenSet.create(
        K.ClassDeclaration,
        K.ConstructorDeclaration,
        K.ConversionOperatorDeclaration,
        K.DelegateDeclaration,
        K.DestructorDeclaration,
        K.EnumDeclaration,
        K.EnumMemberDeclaration,
        K.EventDeclaration,
        K.EventFieldDeclaration,
        K.ExtensionBlockDeclaration,
        K.FieldDeclaration,
        K.FileScopedNamespaceDeclaration,
        K.GlobalStatement,
        K.IncompleteMember,
        K.IndexerDeclaration,
        K.InterfaceDeclaration,
        K.MethodDeclaration,
        K.NamespaceDeclaration,
        K.OperatorDeclaration,
        K.PropertyDeclaration,
        K.RecordDeclaration,
        K.RecordStructDeclaration,
        K.StructDeclaration,
        K.UnionDeclaration,
    )

    /** `NameColonSyntax` */
    @JvmField val NAME_COLON: TokenSet = setNameColon()
    private fun setNameColon(): TokenSet = TokenSet.create(
        K.NameColon,
    )

    /** `NameEqualsSyntax` */
    @JvmField val NAME_EQUALS: TokenSet = setNameEquals()
    private fun setNameEquals(): TokenSet = TokenSet.create(
        K.NameEquals,
    )

    /** `NameSyntax` */
    @JvmField val NAME: TokenSet = setName()
    private fun setName(): TokenSet = TokenSet.create(
        K.AliasQualifiedName,
        K.GenericName,
        K.IdentifierName,
        K.QualifiedName,
    )

    /** `OrderingSyntax` */
    @JvmField val ORDERING: TokenSet = setOrdering()
    private fun setOrdering(): TokenSet = TokenSet.create(
        K.AscendingOrdering,
        K.DescendingOrdering,
    )

    /** `ParameterListSyntax` */
    @JvmField val PARAMETER_LIST: TokenSet = setParameterList()
    private fun setParameterList(): TokenSet = TokenSet.create(
        K.ParameterList,
    )

    /** `ParameterSyntax` */
    @JvmField val PARAMETER: TokenSet = setParameter()
    private fun setParameter(): TokenSet = TokenSet.create(
        K.Parameter,
    )

    /** `PatternSyntax` */
    @JvmField val PATTERN: TokenSet = setPattern()
    private fun setPattern(): TokenSet = TokenSet.create(
        K.AndPattern,
        K.ConstantPattern,
        K.DeclarationPattern,
        K.DiscardPattern,
        K.ListPattern,
        K.NotPattern,
        K.OrPattern,
        K.ParenthesizedPattern,
        K.RecursivePattern,
        K.RelationalPattern,
        K.SlicePattern,
        K.TypePattern,
        K.VarPattern,
    )

    /** `PositionalPatternClauseSyntax` */
    @JvmField val POSITIONAL_PATTERN_CLAUSE: TokenSet = setPositionalPatternClause()
    private fun setPositionalPatternClause(): TokenSet = TokenSet.create(
        K.PositionalPatternClause,
    )

    /** `PropertyPatternClauseSyntax` */
    @JvmField val PROPERTY_PATTERN_CLAUSE: TokenSet = setPropertyPatternClause()
    private fun setPropertyPatternClause(): TokenSet = TokenSet.create(
        K.PropertyPatternClause,
    )

    /** `QueryBodySyntax` */
    @JvmField val QUERY_BODY: TokenSet = setQueryBody()
    private fun setQueryBody(): TokenSet = TokenSet.create(
        K.QueryBody,
    )

    /** `QueryClauseSyntax` */
    @JvmField val QUERY_CLAUSE: TokenSet = setQueryClause()
    private fun setQueryClause(): TokenSet = TokenSet.create(
        K.FromClause,
        K.JoinClause,
        K.LetClause,
        K.OrderByClause,
        K.WhereClause,
    )

    /** `QueryContinuationSyntax` */
    @JvmField val QUERY_CONTINUATION: TokenSet = setQueryContinuation()
    private fun setQueryContinuation(): TokenSet = TokenSet.create(
        K.QueryContinuation,
    )

    /** `SelectOrGroupClauseSyntax` */
    @JvmField val SELECT_OR_GROUP_CLAUSE: TokenSet = setSelectOrGroupClause()
    private fun setSelectOrGroupClause(): TokenSet = TokenSet.create(
        K.GroupClause,
        K.SelectClause,
    )

    /** `SimpleNameSyntax` */
    @JvmField val SIMPLE_NAME: TokenSet = setSimpleName()
    private fun setSimpleName(): TokenSet = TokenSet.create(
        K.GenericName,
        K.IdentifierName,
    )

    /** `StatementSyntax` */
    @JvmField val STATEMENT: TokenSet = setStatement()
    private fun setStatement(): TokenSet = TokenSet.create(
        K.Block,
        K.BreakStatement,
        K.CheckedStatement,
        K.ContinueStatement,
        K.DoStatement,
        K.EmptyStatement,
        K.ExpressionStatement,
        K.FixedStatement,
        K.ForEachStatement,
        K.ForEachVariableStatement,
        K.ForStatement,
        K.GotoCaseStatement,
        K.GotoDefaultStatement,
        K.GotoStatement,
        K.IfStatement,
        K.LabeledStatement,
        K.LocalDeclarationStatement,
        K.LocalFunctionStatement,
        K.LockStatement,
        K.ReturnStatement,
        K.SwitchStatement,
        K.ThrowStatement,
        K.TryStatement,
        K.UncheckedStatement,
        K.UnsafeStatement,
        K.UsingStatement,
        K.WhileStatement,
        K.YieldBreakStatement,
        K.YieldReturnStatement,
    )

    /** `SubpatternSyntax` */
    @JvmField val SUBPATTERN: TokenSet = setSubpattern()
    private fun setSubpattern(): TokenSet = TokenSet.create(
        K.Subpattern,
    )

    /** `SwitchExpressionArmSyntax` */
    @JvmField val SWITCH_EXPRESSION_ARM: TokenSet = setSwitchExpressionArm()
    private fun setSwitchExpressionArm(): TokenSet = TokenSet.create(
        K.SwitchExpressionArm,
    )

    /** `SwitchLabelSyntax` */
    @JvmField val SWITCH_LABEL: TokenSet = setSwitchLabel()
    private fun setSwitchLabel(): TokenSet = TokenSet.create(
        K.CasePatternSwitchLabel,
        K.CaseSwitchLabel,
        K.DefaultSwitchLabel,
    )

    /** `SwitchSectionSyntax` */
    @JvmField val SWITCH_SECTION: TokenSet = setSwitchSection()
    private fun setSwitchSection(): TokenSet = TokenSet.create(
        K.SwitchSection,
    )

    /** `TupleElementSyntax` */
    @JvmField val TUPLE_ELEMENT: TokenSet = setTupleElement()
    private fun setTupleElement(): TokenSet = TokenSet.create(
        K.TupleElement,
    )

    /** `TypeArgumentListSyntax` */
    @JvmField val TYPE_ARGUMENT_LIST: TokenSet = setTypeArgumentList()
    private fun setTypeArgumentList(): TokenSet = TokenSet.create(
        K.TypeArgumentList,
    )

    /** `TypeParameterConstraintClauseSyntax` */
    @JvmField val TYPE_PARAMETER_CONSTRAINT_CLAUSE: TokenSet = setTypeParameterConstraintClause()
    private fun setTypeParameterConstraintClause(): TokenSet = TokenSet.create(
        K.TypeParameterConstraintClause,
    )

    /** `TypeParameterConstraintSyntax` */
    @JvmField val TYPE_PARAMETER_CONSTRAINT: TokenSet = setTypeParameterConstraint()
    private fun setTypeParameterConstraint(): TokenSet = TokenSet.create(
        K.AllowsConstraintClause,
        K.ClassConstraint,
        K.ConstructorConstraint,
        K.DefaultConstraint,
        K.StructConstraint,
        K.TypeConstraint,
    )

    /** `TypeParameterListSyntax` */
    @JvmField val TYPE_PARAMETER_LIST: TokenSet = setTypeParameterList()
    private fun setTypeParameterList(): TokenSet = TokenSet.create(
        K.TypeParameterList,
    )

    /** `TypeParameterSyntax` */
    @JvmField val TYPE_PARAMETER: TokenSet = setTypeParameter()
    private fun setTypeParameter(): TokenSet = TokenSet.create(
        K.TypeParameter,
    )

    /** `TypeSyntax` */
    @JvmField val TYPE: TokenSet = setType()
    private fun setType(): TokenSet = TokenSet.create(
        K.AliasQualifiedName,
        K.ArrayType,
        K.FunctionPointerType,
        K.GenericName,
        K.IdentifierName,
        K.NullableType,
        K.OmittedTypeArgument,
        K.PointerType,
        K.PredefinedType,
        K.QualifiedName,
        K.RefType,
        K.ScopedType,
        K.TupleType,
    )

    /** `UsingDirectiveSyntax` */
    @JvmField val USING_DIRECTIVE: TokenSet = setUsingDirective()
    private fun setUsingDirective(): TokenSet = TokenSet.create(
        K.UsingDirective,
    )

    /** `VariableDeclarationSyntax` */
    @JvmField val VARIABLE_DECLARATION: TokenSet = setVariableDeclaration()
    private fun setVariableDeclaration(): TokenSet = TokenSet.create(
        K.VariableDeclaration,
    )

    /** `VariableDeclaratorSyntax` */
    @JvmField val VARIABLE_DECLARATOR: TokenSet = setVariableDeclarator()
    private fun setVariableDeclarator(): TokenSet = TokenSet.create(
        K.VariableDeclarator,
    )

    /** `VariableDesignationSyntax` */
    @JvmField val VARIABLE_DESIGNATION: TokenSet = setVariableDesignation()
    private fun setVariableDesignation(): TokenSet = TokenSet.create(
        K.DiscardDesignation,
        K.ParenthesizedVariableDesignation,
        K.SingleVariableDesignation,
    )

    /** `WhenClauseSyntax` */
    @JvmField val WHEN_CLAUSE: TokenSet = setWhenClause()
    private fun setWhenClause(): TokenSet = TokenSet.create(
        K.WhenClause,
    )

    /** `XmlAttributeSyntax` */
    @JvmField val XML_ATTRIBUTE: TokenSet = setXmlAttribute()
    private fun setXmlAttribute(): TokenSet = TokenSet.create(
        K.XmlCrefAttribute,
        K.XmlNameAttribute,
        K.XmlTextAttribute,
    )

    /** `XmlElementEndTagSyntax` */
    @JvmField val XML_ELEMENT_END_TAG: TokenSet = setXmlElementEndTag()
    private fun setXmlElementEndTag(): TokenSet = TokenSet.create(
        K.XmlElementEndTag,
    )

    /** `XmlElementStartTagSyntax` */
    @JvmField val XML_ELEMENT_START_TAG: TokenSet = setXmlElementStartTag()
    private fun setXmlElementStartTag(): TokenSet = TokenSet.create(
        K.XmlElementStartTag,
    )

    /** `XmlNameSyntax` */
    @JvmField val XML_NAME: TokenSet = setXmlName()
    private fun setXmlName(): TokenSet = TokenSet.create(
        K.XmlName,
    )

    /** `XmlNodeSyntax` */
    @JvmField val XML_NODE: TokenSet = setXmlNode()
    private fun setXmlNode(): TokenSet = TokenSet.create(
        K.XmlCDataSection,
        K.XmlComment,
        K.XmlElement,
        K.XmlEmptyElement,
        K.XmlProcessingInstruction,
        K.XmlText,
    )

    /** `XmlPrefixSyntax` */
    @JvmField val XML_PREFIX: TokenSet = setXmlPrefix()
    private fun setXmlPrefix(): TokenSet = TokenSet.create(
        K.XmlPrefix,
    )
}
