package io.github.dotnetsupport.ml

import com.intellij.codeInsight.CodeInsightSettings
import com.intellij.openapi.util.io.FileUtil
import com.intellij.testFramework.fixtures.BasePlatformTestCase
import io.github.completionml.core.rank.ExampleShards
import io.github.completionml.core.rank.FeatureExtractor
import io.github.completionml.core.rank.FeatureSchema
import io.github.completionml.core.spi.ContextKind
import io.github.completionml.core.vocab.Vocabulary
import io.github.dotnetsupport.lang.CSharpFeature
import io.github.dotnetsupport.lang.CSharpFeatureSource
import io.github.dotnetsupport.lang.CSharpSyntaxTrees
import io.github.dotnetsupport.lang.NativeCSharpMlInfo
import io.github.dotnetsupport.lsp.RoslynLanguageServerSettings
import java.io.File

/**
 * The offline export of completion lists for the ML ranker (ML_RANKER_EXPORT_TASK.md): on a fixture repository the exporter writes a shard
 * of the schema with the answer in every list and features in range, skipping tests and generated files; the language block of
 * [CSharpMlFeatures] on hand-built candidates; the candidate info the native completion attaches to its items ([NativeCSharpMlInfo]).
 */
class CSharpMlDatasetExportTest : BasePlatformTestCase() {
    private var autocomplete = true

    override fun setUp() {
        super.setUp()
        CSharpSyntaxTrees.forceNativeTreeForTests(true)
        RoslynLanguageServerSettings.getInstance().setSource(CSharpFeature.COMPLETION, CSharpFeatureSource.NATIVE)
        autocomplete = CodeInsightSettings.getInstance().AUTOCOMPLETE_ON_CODE_COMPLETION
        CodeInsightSettings.getInstance().AUTOCOMPLETE_ON_CODE_COMPLETION = false
    }

    override fun tearDown() {
        try {
            CodeInsightSettings.getInstance().AUTOCOMPLETE_ON_CODE_COMPLETION = autocomplete
            RoslynLanguageServerSettings.getInstance().state.features = mutableMapOf()
            CSharpSyntaxTrees.forceNativeTreeForTests(null)
        } catch (e: Throwable) {
            addSuppressedException(e)
        } finally {
            super.tearDown()
        }
    }

    // ---- the export on a fixture repository

    private val order = """
        namespace Shop.Models
        {
            public class Order
            {
                private int count;
                public int Total { get; set; }
                public string Name { get; set; }
                public int Count() { return count; }
                public void Reset(int value) { count = value; Total = value; }
            }
        }
    """.trimIndent()

    private val program = """
        using Shop.Models;
        namespace Shop.App
        {
            public class Program
            {
                private static int limit = 3;
                public static void Run(Order order, int amount)
                {
                    int total = order.Total;
                    int count = order.Count();
                    order.Reset(amount);
                    if (total > limit) { order.Total = amount + count; }
                    Run(order, total);
                }
            }
        }
    """.trimIndent()

    private fun repository(): File {
        val repo = FileUtil.createTempDirectory("csml-fixture-", null, true)
        File(repo, "Shop/Models/Order.cs").apply { parentFile.mkdirs(); writeText(order) }
        File(repo, "Shop/App/Program.cs").apply { parentFile.mkdirs(); writeText(program) }
        File(repo, "Shop/Shop.csproj").writeText("<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>")
        File(repo, "Shop.Tests/OrderTests.cs").apply { parentFile.mkdirs(); writeText(program.replace("Program", "OrderTests")) }
        File(repo, "Shop/Generated.cs").writeText("// <auto-generated/>\n" + order.replace("Order", "GeneratedOrder"))
        File(repo, "bin/Skipped.cs").apply { parentFile.mkdirs(); writeText(order) }
        return repo
    }

    fun testExportWritesAShardWithTheAnswerInEveryList() {
        val repo = repository()
        val vocab = Vocabulary.Builder().apply { listOf(order, program).forEach { addFile(CSharpMlLanguage.tokenizer.tokens(it)) } }.build(1000, minDocFreq = 1)
        val extractor = FeatureExtractor(CSharpMlFeatures.schema, vocab, null, 0.0)
        val options = CSharpMlExporter.Options(perFile = 1000, maxFiles = 0, cacheLambda = 0.0)
        val exporter = CSharpMlExporter(myFixture, project, myFixture.module, testRootDisposable, vocab, extractor, options)
        val shard = File(repo.parentFile, repo.name + ExampleShards.EXTENSION)
        val stats = CSharpMlExporter.Stats()
        try {
            ExampleShards.Writer(shard, CSharpMlLanguage.id, "test", CSharpMlFeatures.schema, withNames = true).use { exporter.exportRepository(repo, it, stats) }
            assertEquals("tests, generated and bin/ files are skipped: ${stats.summary()}", 2, stats.files)
            assertTrue(stats.summary(), stats.positions > 10)
            assertTrue("some lists have the answer: ${stats.summary()}", stats.lists > 0)
            val (header, examples) = ExampleShards.readAll(shard)
            assertEquals("csharp", header.language)
            assertEquals(CSharpMlFeatures.schema.hash, header.schema.hash)
            assertEquals(stats.lists, examples.size)
            val afterDot = CSharpMlFeatures.schema.baseIndex("after_dot")
            val kinds = (0 until 10).map { CSharpMlFeatures.schema.baseIndex(CSharpMlFeatures.NAMES[it]) }
            for (ex in examples) {
                assertTrue(ex.chosen in 0 until ex.size)
                assertTrue(ex.size >= 2)
                val names = ex.candidateNames!!
                assertTrue("the answer is the identifier of the source: ${names[ex.chosen]}", names[ex.chosen] in setOf(
                    "Order", "order", "Total", "Count", "Reset", "amount", "total", "count", "limit", "Run", "Shop", "Models", "App", "Program", "Name", "value", "int", "string",
                ))
                for (c in 0 until ex.size) {
                    val f = ex.base[c]
                    assertEquals(CSharpMlFeatures.schema.baseSize, f.size)
                    for ((i, x) in f.withIndex()) {
                        assertTrue("${CSharpMlFeatures.schema.baseNames[i]} of ${names[c]} = $x", x.isFinite())
                        if (i >= FeatureSchema.BASE.size) assertTrue("${CSharpMlFeatures.schema.baseNames[i]} of ${names[c]} = $x", x in 0f..12f)
                    }
                    assertTrue("one kind at most: ${names[c]}", kinds.sumOf { f[it].toDouble() } <= 1.0)
                }
            }
            val dots = examples.filter { it.base[0][afterDot] == 1f }
            val statements = examples.filter { it.base[0][afterDot] == 0f }
            assertTrue("member lists after a dot: ${examples.size}", dots.isNotEmpty())
            assertTrue("lists at a statement: ${examples.size}", statements.isNotEmpty())
            assertTrue(dots.all { it.kind == ContextKind.AFTER_DOT })
            // `order.Total` — the members of Order come from the other file of the repository
            val total = dots.firstOrNull { it.candidateNames!![it.chosen] == "Total" }
            assertNotNull("order.Total is completed from Order.cs: ${dots.map { it.candidateNames!![it.chosen] }}", total)
        } finally {
            shard.delete()
            FileUtil.delete(repo)
        }
    }

    fun testSourceSelection() {
        val f = File(FileUtil.createTempDirectory("csml-", null, true), "a.cs").apply { writeText("x".repeat(300)) }
        assertTrue(CSharpMlExporter.isSource("src/Lib/Order.cs", f))
        assertFalse(CSharpMlExporter.isSource("src/Lib/Order.Designer.cs", f))
        assertFalse(CSharpMlExporter.isSource("src/Lib/Order.g.cs", f))
        assertFalse(CSharpMlExporter.isSource("src/Lib/AssemblyInfo.cs", f))
        assertFalse(CSharpMlExporter.isSource("src/Lib/OrderTests.cs", f))
        assertFalse(CSharpMlExporter.isSource("tests/Lib/Order.cs", f))
        assertFalse(CSharpMlExporter.isSource("src/Lib.Tests/Order.cs", f))
        assertFalse(CSharpMlExporter.isSource("src/Lib/Order.cs", File(f.parentFile, "small.cs").apply { writeText("x") }))
        assertTrue(CSharpMlExporter.isGenerated("// <auto-generated />\nclass A {}"))
        assertFalse(CSharpMlExporter.isGenerated("// hand written\nclass A {}"))
    }

    // ---- the language block

    private fun candidate(name: String, kind: CSharpMlCandidateKind, priority: Double, scope: Int = CSharpMlScope.IMPORTED, expected: Int = 0, decl: Int? = null, static: Boolean = false, using: Boolean = false) =
        CSharpMlCandidate(name, kind, static, scope, using, expected, decl, priority)

    fun testLanguageBlock() {
        val candidates = listOf(
            candidate("count", CSharpMlCandidateKind.LOCAL, 48.0, CSharpMlScope.LOCAL, decl = 100),
            candidate("Total", CSharpMlCandidateKind.PROPERTY, 65.0, CSharpMlScope.MEMBER, expected = 2, decl = 20),
            candidate("Console", CSharpMlCandidateKind.TYPE, 20.0, CSharpMlScope.UNIMPORTED, static = true, using = true),
            candidate("if", CSharpMlCandidateKind.KEYWORD, 0.0, CSharpMlScope.LOCAL),
            candidate("Run", CSharpMlCandidateKind.METHOD, 48.0, CSharpMlScope.MEMBER, static = true),
        )
        val block = CSharpMlFeatures.languageBlock(caretOffset = 120, afterDot = false, candidates = candidates)
        val i = CSharpMlFeatures::index
        assertEquals(CSharpMlFeatures.NAMES.size, block[0].size)
        // one-hot kinds
        assertEquals(1f, block[0][i("kind_local")]); assertEquals(1f, block[1][i("kind_property")]); assertEquals(1f, block[2][i("kind_type")])
        assertEquals(1f, block[3][i("kind_keyword")]); assertEquals(1f, block[4][i("kind_method")])
        assertEquals(0f, block[0][i("kind_property")])
        // flags and levels
        assertEquals(1f, block[2][i("is_static")]); assertEquals(0f, block[0][i("is_static")])
        assertEquals(5f, block[2][i("scope_level")]); assertEquals(0f, block[0][i("scope_level")]); assertEquals(1f, block[1][i("scope_level")])
        assertEquals(1f, block[2][i("needs_using")]); assertEquals(0f, block[1][i("needs_using")])
        assertEquals(2f, block[1][i("expected_type_match")]); assertEquals(0f, block[0][i("expected_type_match")])
        assertTrue(block.all { it[i("list_has_expected")] == 1f })
        assertEquals(1f, block[0][i("declared_in_file")]); assertEquals(0f, block[2][i("declared_in_file")])
        assertEquals((Math.log(1.0 + 20) / 10).toFloat(), block[0][i("decl_distance_log")]); assertEquals(0f, block[2][i("decl_distance_log")])
        // rule rank: Total (65) → 0, then Run (48, "R" < "c") → 1, count (48) → 2, Console (20) → 3, if (0) → 4
        val rank = i("rule_rank_log")
        assertEquals(0f, block[1][rank])
        assertEquals(Math.log(2.0).toFloat(), block[4][rank]); assertEquals(Math.log(3.0).toFloat(), block[0][rank])
        assertEquals(Math.log(4.0).toFloat(), block[2][rank]); assertEquals(Math.log(5.0).toFloat(), block[3][rank])
        assertTrue(block.all { it[i("after_dot")] == 0f })
        assertTrue(CSharpMlFeatures.languageBlock(0, true, candidates).all { it[i("after_dot")] == 1f })
        // without an expected type the list flag is 0
        val none = CSharpMlFeatures.languageBlock(0, false, candidates.filter { it.expectedTypeMatch == 0 })
        assertTrue(none.all { it[i("list_has_expected")] == 0f })
    }

    fun testContextKindAndDot() {
        val tokens = CSharpMlLanguage.tokenizer.tokens("class A { void M(int x) { x = y.z; M(a, b); } }")
        val z = tokens.indexOfFirst { it.text == "z" }
        val y = tokens.indexOfFirst { it.text == "y" }
        val b = tokens.indexOfFirst { it.text == "b" }
        assertTrue(CSharpMlFeatures.isAfterDot(tokens, z)); assertFalse(CSharpMlFeatures.isAfterDot(tokens, y))
        assertEquals(ContextKind.AFTER_DOT, CSharpMlFeatures.contextKind(tokens, z))
        assertEquals(ContextKind.ASSIGN_RHS, CSharpMlFeatures.contextKind(tokens, y))
        assertEquals(ContextKind.ARGUMENT, CSharpMlFeatures.contextKind(tokens, b))
        assertEquals(ContextKind.OTHER, CSharpMlFeatures.contextKind(tokens, 0))
    }

    // ---- the info the native completion attaches

    private fun infos(text: String, name: String): Map<String, CSharpMlCandidate?> {
        myFixture.configureByText(name, text.trimIndent())
        myFixture.completeBasic()
        return myFixture.lookupElements.orEmpty().associate { it.lookupString to NativeCSharpMlInfo.infoOf(it) }
    }

    fun testNativeItemsCarryTheirInfo() {
        val text = """
            class Sample
            {
                private int count;
                public static int Limit { get; set; }
                public void Run(int amount)
                {
                    int total = amount;
                    <caret>
                }
            }
        """
        val infos = infos(text, "MlInfo1.cs")
        val total = infos["total"] ?: error("no info on total: ${infos.keys}")
        assertEquals(CSharpMlCandidateKind.LOCAL, total.kind)
        assertEquals(CSharpMlScope.LOCAL, total.scopeLevel)
        assertNotNull("a local is declared in the file", total.declarationOffset)
        assertEquals(text.trimIndent().replace("<caret>", "").indexOf("total = amount"), total.declarationOffset)
        assertTrue(total.rulePriority >= 48.0)
        val amount = infos["amount"]!!
        assertEquals(CSharpMlCandidateKind.PARAMETER, amount.kind)
        val count = infos["count"]!!
        assertEquals(CSharpMlCandidateKind.FIELD, count.kind); assertEquals(CSharpMlScope.MEMBER, count.scopeLevel); assertFalse(count.isStatic)
        assertNotNull(count.declarationOffset)
        val limit = infos["Limit"]!!
        assertEquals(CSharpMlCandidateKind.PROPERTY, limit.kind); assertTrue(limit.isStatic)
        val run = infos["Run"]!!
        assertEquals(CSharpMlCandidateKind.METHOD, run.kind)
        val keyword = infos["if"]!!
        assertEquals(CSharpMlCandidateKind.KEYWORD, keyword.kind); assertEquals(0.0, keyword.rulePriority)
        val sample = infos["Sample"]!!
        assertEquals(CSharpMlCandidateKind.TYPE, sample.kind)
        val predefined = infos["int"]!!
        assertEquals(CSharpMlCandidateKind.TYPE, predefined.kind)
        // the fallback of an item nobody described
        assertEquals(CSharpMlCandidateKind.OTHER, NativeCSharpMlInfo.fallback(myFixture.lookupElements!!.first()).kind)
    }

    fun testMembersAfterADotAreOfTheReceiver() {
        val infos = infos("""
            class Order
            {
                public int Total { get; set; }
                public static Order Empty;
                public int Count() { return 0; }
            }
            class Sample
            {
                void Run(Order order) { order.<caret> }
            }
        """, "MlInfo2.cs")
        val total = infos["Total"] ?: error("no Total: ${infos.keys}")
        assertEquals(CSharpMlCandidateKind.PROPERTY, total.kind)
        assertEquals(CSharpMlScope.RECEIVER, total.scopeLevel)
        assertNotNull("declared in this file", total.declarationOffset)
        val count = infos["Count"] ?: error("no Count: ${infos.keys}")
        assertEquals(CSharpMlCandidateKind.METHOD, count.kind)
        assertFalse(count.isStatic)
    }

    fun testExpectedTypeRowsAreMarked() {
        val infos = infos("""
            class Sample
            {
                private int count;
                private string name;
                void Run()
                {
                    int total = <caret>
                }
            }
        """, "MlInfo3.cs")
        val count = infos["count"] ?: error("no count: ${infos.keys}")
        assertEquals("an int field fits an int initializer", 2, count.expectedTypeMatch)
        val name = infos["name"] ?: error("no name: ${infos.keys}")
        assertEquals(0, name.expectedTypeMatch)
    }
}
