import os, subprocess, time
from dap import APP_DLL, Session, short

def target():
    p = subprocess.Popen(["dotnet", APP_DLL, "sleeper"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(2)
    return p

# 1. attach, hit a breakpoint, detach: must the process survive?
t = target()
s = Session("v-attach-detach")
s.initialize()
seq = s.send("attach", {"processId": t.pid})
s.wait_event("initialized", 20)
s.set_breakpoints(["sleeper"], show=False)
s.request("configurationDone", show=False)
print("   attach response:", short(s.wait_response(seq, 20)))
stop = s.stop(timeout=10)
print("   stopped:", short(stop))
s.close(terminate=False)
time.sleep(1.5)
print("   RESULT target after attach + disconnect(terminateDebuggee=false): %s" % ("ALIVE" if t.poll() is None else "DEAD exit=%s" % t.poll()))
t.kill()

# 2. detach while running (no breakpoint hit)
t = target()
s = Session("v-attach-detach-running")
s.initialize()
seq = s.send("attach", {"processId": t.pid})
s.wait_event("initialized", 20)
s.request("configurationDone", show=False)
s.wait_response(seq, 20)
s.drain(1)
s.close(terminate=False)
time.sleep(1.5)
print("   RESULT target after attach + detach while running: %s" % ("ALIVE" if t.poll() is None else "DEAD exit=%s" % t.poll()))
t.kill()

# 3. disconnect with no arguments after attach (the DAP default for attach is to leave the process alone)
t = target()
s = Session("v-attach-default-disconnect")
s.initialize()
seq = s.send("attach", {"processId": t.pid})
s.wait_event("initialized", 20)
s.request("configurationDone", show=False)
s.wait_response(seq, 20)
s.request("disconnect", {}, show=False)
time.sleep(1.5)
print("   RESULT target after attach + disconnect{}: %s" % ("ALIVE" if t.poll() is None else "DEAD exit=%s" % t.poll()))
t.kill()

# 4. a second debugger on a process that is already being debugged
t = target()
s = Session("v-attach-first")
s.initialize()
seq = s.send("attach", {"processId": t.pid})
s.wait_event("initialized", 20)
s.request("configurationDone", show=False)
s.wait_response(seq, 20)
s2 = Session("v-attach-second")
s2.initialize()
seq2 = s2.send("attach", {"processId": t.pid})
print("   second attach response:", short(s2.wait_response(seq2, 20), 300))
time.sleep(1)
print("   RESULT target while two debuggers tried: %s" % ("ALIVE" if t.poll() is None else "DEAD exit=%s" % t.poll()))
s2.close(terminate=False)
time.sleep(1)
print("   RESULT target after the second adapter left: %s" % ("ALIVE" if t.poll() is None else "DEAD exit=%s" % t.poll()))
s.close(terminate=False)
t.kill()

for name, args in (("v-attach-nonexistent", {"processId": 999999}), ("v-attach-native", {"processId": os.getpid()}), ("v-attach-string", {"processId": "abc"})):
    s = Session(name)
    s.initialize()
    print("   response:", short(s.wait_response(s.send("attach", args), 20), 300))
    s.close(terminate=False)
