package io.github.dotnetsupport.codeanalysis

/**
 * A C# file a target of the build made in `obj/` for the compiler (0.1.82): `MainWindow.g.cs` of WPF's `MarkupCompilePass1` (`.g.i.cs` of
 * the design-time build of Visual Studio), `Greet.cs` / `GreetGrpc.cs` of Grpc.Tools' `Protobuf_Compile`, a strongly typed resource class.
 * [kind]: who made it (the name of the node in the Dependencies tree), [source]: the file it was made of, when known.
 */
data class BuildGeneratedFile(val path: String, val kind: String, val source: String?)

/**
 * What the build makes of the XAML and protobuf files of a project, and whether it is there and newer than they are ([fresh]): then the
 * semantics of the plugin knows every type and member they declare (the files are content of the IDE project, so they are indexed), and a
 * name it cannot find in a WPF or gRPC project is an error again. [stale]: the outputs that are older than their sources.
 */
class BuildGenerated(val files: List<BuildGeneratedFile>, val missing: List<String>, val stale: List<BuildGeneratedFile>) {
    val fresh: Boolean get() = missing.isEmpty() && stale.isEmpty()

    companion object {
        val NONE = BuildGenerated(emptyList(), emptyList(), emptyList())
    }
}

/**
 * Where the build puts what it generates and what of it a project needs: pure, on paths (`/`), so it is tested without a build. The files
 * come from the design-time build of CodeAnalysisHelper (`buildFiles` of `generate`: the command line of the compiler after the targets
 * ran) or, when it has none (a project of the old format: `dotnet msbuild` does not run the XAML targets of .NET Framework), from `obj/`
 * after the last build ([scan]).
 */
object BuildGeneratedSources {
    /** The node under Dependencies → Analyzers, as the generator assembly of the files ([GeneratedFile.generatorAssembly]). */
    const val NODE = "Generated by build"
    const val XAML = "XAML (MarkupCompilePass1)"
    const val PROTOBUF = "Protobuf (Grpc.Tools)"
    const val RESOURCES = "Resources (GenerateResource)"
    const val MSBUILD = "MSBuild targets"

    /** The extensions of the inputs whose change makes the outputs stale; `.resx` only when the build generates from it. */
    val INPUT_EXTENSIONS = setOf("xaml", "proto", "resx")

    /**
     * Who made [path] and of which of [inputs] (paths of the `.xaml` / `.proto` / `.resx` files of the project): XAML by `<name>.g.cs` /
     * `<name>.g.i.cs` (a `.xaml` of that name, in the same folder under `obj/<configuration>/[<framework>/]`); protobuf by the name protoc
     * gives the C# of `hello_world.proto` (`HelloWorld.cs`, `HelloWorldGrpc.cs`); resources by `<name>.Designer.cs`.
     */
    fun classify(path: String, inputs: Collection<String>): BuildGeneratedFile {
        val name = path.substringAfterLast('/')
        val lower = name.lowercase()
        if (lower.endsWith(".g.cs") || lower.endsWith(".g.i.cs")) {
            val base = name.substring(0, name.length - (if (lower.endsWith(".g.i.cs")) ".g.i.cs" else ".g.cs").length)
            val candidates = inputs.filter { it.endsWith(".xaml", ignoreCase = true) && it.substringAfterLast('/').substringBeforeLast('.').equals(base, ignoreCase = true) }
            val source = candidates.firstOrNull { sameFolder(it, path) } ?: candidates.singleOrNull()
            return BuildGeneratedFile(path, XAML, source)
        }
        if (lower.endsWith(".cs")) {
            val base = name.substringBeforeLast('.')
            inputs.firstOrNull { it.endsWith(".proto", ignoreCase = true) && protocName(it).let { c -> c == base || c + "Grpc" == base } }?.let { return BuildGeneratedFile(path, PROTOBUF, it) }
            if (lower.endsWith(".designer.cs")) {
                val resource = name.substring(0, name.length - ".designer.cs".length)
                return BuildGeneratedFile(path, RESOURCES, inputs.firstOrNull { it.endsWith(".resx", ignoreCase = true) && it.substringAfterLast('/').substringBeforeLast('.').equals(resource, ignoreCase = true) })
            }
        }
        return BuildGeneratedFile(path, MSBUILD, null)
    }

    /** The name of the C# file protoc makes of a `.proto`: the file name without extension, `_` / `-` / `.` dropped and the next letter upper case. */
    fun protocName(proto: String): String {
        val base = proto.substringAfterLast('/').substringBeforeLast('.')
        val out = StringBuilder()
        var upper = true
        for (c in base) {
            if (c == '_' || c == '-' || c == '.') { upper = true; continue }
            out.append(if (upper) c.uppercaseChar() else c)
            upper = c.isDigit()
        }
        return out.toString()
    }

    /**
     * The outputs of [inputs] among the files of `obj/` ([objFiles], paths relative to the project folder or absolute — under `obj/`) for
     * [configuration] and [framework]: what the last build made. Only files that come from an input count (assembly info and the like are
     * the project's own); a `.g.cs` wins over the `.g.i.cs` of the same XAML (the design-time one of Visual Studio).
     */
    fun scan(projectDirectory: String, objFiles: Collection<String>, inputs: Collection<String>, configuration: String, framework: String?): List<BuildGeneratedFile> {
        val obj = projectDirectory.trimEnd('/') + "/obj/"
        val found = objFiles.filter { path ->
            if (!path.startsWith(obj, ignoreCase = true) || !path.endsWith(".cs", ignoreCase = true)) return@filter false
            val segments = path.substring(obj.length).split('/')
            if (segments.size < 2 || !segments[0].equals(configuration, ignoreCase = true)) return@filter false
            // obj/Debug/net9.0/… of an SDK project: another framework's outputs are not of this compilation
            val second = segments[1]
            framework == null || segments.size == 2 || !TFM.matches(second) || second.equals(framework, ignoreCase = true)
        }.map { classify(it, inputs) }.filter { it.source != null }
        val withoutDesignTime = found.filter { file ->
            !file.path.endsWith(".g.i.cs", ignoreCase = true) || found.none { it.path.equals(file.path.dropLast(".g.i.cs".length) + ".g.cs", ignoreCase = true) }
        }
        return withoutDesignTime.sortedBy { it.path.lowercase() }
    }

    /**
     * The state of [files] against [inputs]: the inputs that need an output and have none ([needsOutput]: a XAML with `x:Class`, every
     * `.proto`), the outputs older than their source ([stamp]: the time of a file, 0 when it is not there).
     */
    fun check(files: List<BuildGeneratedFile>, inputs: Collection<String>, needsOutput: (String) -> Boolean, stamp: (String) -> Long): BuildGenerated {
        val made = files.mapNotNullTo(HashSet()) { it.source?.lowercase() }
        val missing = inputs.filter { (it.endsWith(".xaml", ignoreCase = true) || it.endsWith(".proto", ignoreCase = true)) && it.lowercase() !in made && needsOutput(it) }
        val stale = files.filter { file -> file.source != null && stamp(file.source) > stamp(file.path) }
        return BuildGenerated(files, missing, stale)
    }

    /** The banner of a file the build made, as Rider says of generated files: who made it of what, that edits are lost, that it is out of date. */
    fun banner(kind: String, source: String?, project: String, stale: Boolean): String =
        "Generated by the build (${kind.substringBefore(" (")}${source?.let { " from $it" } ?: ""}) for $project: changes are lost at the next build" +
            if (stale) ". Out of date: ${source ?: "its source"} has changed since — build the project" else ""

    private fun sameFolder(input: String, output: String): Boolean {
        // MainWindow.xaml → obj/Debug/[net9.0-windows/]MainWindow.g.cs; Views/Main.xaml → obj/Debug/…/Views/Main.g.cs
        val inputFolder = input.substringBeforeLast('/', "").substringAfterLast('/').lowercase()
        val outputFolder = output.substringBeforeLast('/', "").substringAfterLast('/').lowercase()
        return inputFolder == outputFolder || !output.contains("/obj/", ignoreCase = true)
    }

    private val TFM = Regex("(?i)net\\d.*|netstandard.*|netcoreapp.*|net4\\d+")
}
