package io.github.dotnetsupport.codeanalysis

import com.intellij.icons.AllIcons
import com.intellij.navigation.ItemPresentation
import com.intellij.openapi.fileEditor.FileEditor
import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.AdditionalLibraryRootsProvider
import com.intellij.openapi.roots.SyntheticLibrary
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.search.GlobalSearchScope
import com.intellij.ui.EditorNotificationPanel
import com.intellij.ui.EditorNotificationProvider
import java.util.function.Function
import javax.swing.Icon
import javax.swing.JComponent

/**
 * The files the source generators of the solution made ([CodeAnalysisService.generate]) as a library of the IDE: indexed (stubs), so the
 * resolver of the plugin finds what they declare, and listed under External Libraries → Generated Sources. Not in the project scope: Find
 * in Files and the tree of the project leave them out, as Rider does.
 */
class GeneratedSourcesLibrary(private val roots: List<VirtualFile>) : SyntheticLibrary("dotnet:generated", null), ItemPresentation {
    override fun getSourceRoots(): Collection<VirtualFile> = roots
    override fun getBinaryRoots(): Collection<VirtualFile> = emptyList()
    override fun getPresentableText(): String = GeneratedSourcesRootsProvider.LIBRARY_NAME
    override fun getIcon(unused: Boolean): Icon = AllIcons.Actions.Lightning
    override fun equals(other: Any?): Boolean = other is GeneratedSourcesLibrary && other.roots == roots
    override fun hashCode(): Int = roots.hashCode()
}

class GeneratedSourcesRootsProvider : AdditionalLibraryRootsProvider() {
    override fun getAdditionalProjectLibraries(project: Project): Collection<SyntheticLibrary> {
        if (project.isDisposed) return emptyList()
        val roots = project.getServiceIfCreated(CodeAnalysisService::class.java)?.generatedRoots().orEmpty()
        return if (roots.isEmpty()) emptyList() else listOf(GeneratedSourcesLibrary(roots))
    }

    override fun getRootsToWatch(project: Project): Collection<VirtualFile> =
        project.getServiceIfCreated(CodeAnalysisService::class.java)?.generatedRoots().orEmpty()

    companion object {
        const val LIBRARY_NAME = "Generated Sources"
    }
}

/**
 * Where the C# semantics of the plugin looks for the declarations of the solution: the project scope and the generated files of its
 * projects. A hook for the lookups that took `GlobalSearchScope.projectScope` (types and namespaces by name, extension methods, global usings).
 */
object CSharpSourceScope {
    fun of(project: Project): GlobalSearchScope {
        val projectScope = GlobalSearchScope.projectScope(project)
        val service = project.getServiceIfCreated(CodeAnalysisService::class.java) ?: return projectScope
        val roots = service.generatedRoots()
        if (roots.isEmpty()) return projectScope
        return projectScope.uniteWith(GeneratedScope(project, service))
    }

    private class GeneratedScope(project: Project, private val service: CodeAnalysisService) : GlobalSearchScope(project) {
        override fun contains(file: VirtualFile): Boolean = service.isGenerated(file)
        override fun isSearchInModuleContent(aModule: com.intellij.openapi.module.Module): Boolean = false
        override fun isSearchInLibraries(): Boolean = true
        override fun equals(other: Any?): Boolean = other is GeneratedScope && other.service === service
        override fun hashCode(): Int = service.hashCode()
    }
}

/** The banner of a generated file, as Rider's: who made it and that edits do not last. */
class GeneratedFileNotificationProvider : EditorNotificationProvider {
    override fun collectNotificationData(project: Project, file: VirtualFile): Function<in FileEditor, out JComponent?>? {
        val service = project.getServiceIfCreated(CodeAnalysisService::class.java) ?: return null
        val projectFile = service.projectOfGenerated(file) ?: return null
        val state = service.generatedState(projectFile) ?: return null
        val generated = state.run.files.firstOrNull { it.path.equals(file.path, ignoreCase = true) } ?: return null
        return Function {
            EditorNotificationPanel(it, EditorNotificationPanel.Status.Info).apply {
                text = "Generated by ${generated.generatorType.substringAfterLast('.')} (${generated.generatorAssembly}) for ${projectFile.nameWithoutExtension}: read-only, made again on save and build"
            }
        }
    }
}
