using Grpc.Core;

namespace Playground.Grpc;

/// <summary>
/// Live check of the C# the build makes of protos (0.1.82): HelloRequest, HelloReply and Greeter.GreeterBase are declared only in
/// obj/Debug/net9.0/Protos/*.cs, which Grpc.Tools writes. The server off; open this file and wait a few seconds (the helper of the plugin
/// runs the design-time build that makes them; no build needed). Type on the empty line under a marker, check EXPECT, Ctrl+Z.
/// </summary>
public sealed class GreeterService : Greeter.GreeterBase
{
    // TYPE:grpc-resolve — Ctrl+B on `HelloRequest` below. EXPECT: obj/Debug/net9.0/Protos/Greet.cs opens at the class, with the banner
    // «Generated by the build (Protobuf from greet.proto) for Grpc: changes are lost at the next build»; `request.Name` and
    // `Greeter.GreeterBase` are not red. In the Solution view: Grpc → Dependencies → .NET 9.0 → Analyzers → Generated by build →
    // Protobuf (Grpc.Tools) → Greet.cs, GreetGrpc.cs
    public override Task<HelloReply> SayHello(HelloRequest request, ServerCallContext context) =>
        Task.FromResult(new HelloReply { Message = "Hello, " + request.Name });

    // TYPE:grpc-errors — type `var wrong = new HelloRequest().Nmae;`.
    // EXPECT: a red «CS1061: 'HelloRequest' does not contain a definition for 'Nmae'…» on `Nmae` (before 0.1.82 a gRPC project had no
    // semantic errors at all). NOT: an error on `HelloRequest`
}
