"""Makes the aspnetcore target of baseline.py: the sources of Microsoft.AspNetCore.Mvc.Core (dotnet/aspnetcore) as a plain SDK project.

    python tools/ui-robot/make-aspnetcore-sample.py [--aspnetcore DIR]

The repository of aspnetcore does not open as it is: its projects need the Arcade SDK (eng/, the SDK pinned in global.json, restore
from the feeds of dotnet), and the corpus of csharp-psi (`tools/fetch-corpus.sh` there) is a sparse checkout of src/ only. So the
project is rebuilt: src/Mvc/Mvc.Core/src with the shared sources its .csproj links, a .csproj on the shared framework
(FrameworkReference Microsoft.AspNetCore.App: restores offline), the `Resources` class Arcade would generate from Resources.resx,
a .slnx, and Measurements.cs with the anchors of the measurement. It builds with 4 errors (SDK 10.0.401: two internals of other
assemblies of aspnetcore, InternalsVisibleTo in the real build, and two overrides of members newer than the shared framework): the
same input for the server now and for the native PSI later. Mind `ImplicitUsings`: aspnetcore relies on it.
Out: build/baseline/aspnetcore-mvc-core.
"""
import argparse
import glob
import os
import re
import shutil
import xml.etree.ElementTree as ElementTree

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT = os.path.join(ROOT, "build", "baseline", "aspnetcore-mvc-core")
PROJECT = "src/Mvc/Mvc.Core/src/Microsoft.AspNetCore.Mvc.Core.csproj"

CSPROJ = """<Project Sdk="Microsoft.NET.Sdk">
  <!-- Made by tools/ui-robot/make-aspnetcore-sample.py from %s of dotnet/aspnetcore (MIT). -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Microsoft.AspNetCore.Mvc.Core</RootNamespace>
    <AssemblyName>Microsoft.AspNetCore.Mvc.Core.Sample</AssemblyName>
    <!-- the sources redefine types of the shared framework they are compiled against -->
    <NoWarn>$(NoWarn);CS0436;CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
"""

MEASUREMENTS = """using System;
using Microsoft.AspNetCore.Mvc;

namespace Microsoft.AspNetCore.Mvc.Sample;

/// <summary>Anchors of tools/ui-robot/baseline.py (the same markers as debug-playground/Console/Editor/Measurements.cs).</summary>
public static class MeasurementsScenario
{
    public static int Members(ActionContext context)
    {
        // TYPE:measure-member — type `context.` on the empty line below.
        // EXPECT: the completion popup opens by itself with HttpContext, RouteData, ...

        // TYPE:measure-prefix — type `ControllerBas` on the empty line below.
        // EXPECT: the completion popup opens by itself with ControllerBase in it.

        // TYPE:measure-edit — the script types statements here for a while.

        return context.ModelState.Count;
    }
}
"""


def resources_class(resx, namespace):
    """What Arcade's GenerateResxSource makes of a .resx: a property per string, and FormatX(p0, ...) for a string with placeholders."""
    lines = ["// <auto-generated/> by tools/ui-robot/make-aspnetcore-sample.py, as Arcade's GenerateResxSource does",
             "#nullable enable", "namespace %s" % namespace, "{", "    internal static partial class Resources", "    {",
             "        private static global::System.Resources.ResourceManager? s_resourceManager;",
             "        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ??= new global::System.Resources.ResourceManager(typeof(Resources));",
             "        internal static string GetResourceString(string name) => ResourceManager.GetString(name)!;"]
    for data in ElementTree.parse(resx).getroot().iter("data"):
        name = data.get("name")
        value = data.findtext("value") or ""
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name or ""):
            continue
        lines.append("        internal static string @%s => GetResourceString(\"%s\");" % (name, name))
        indexes = [int(i) for i in re.findall(r"\{(\d+)[^}]*\}", value)]
        if indexes:
            count = max(indexes) + 1
            parameters = ", ".join("object? p%d" % i for i in range(count))
            arguments = ", ".join("p%d" % i for i in range(count))
            lines.append("        internal static string Format%s(%s) => string.Format(global::System.Globalization.CultureInfo.CurrentCulture, GetResourceString(\"%s\"), %s);" % (name, parameters, name, arguments))
    lines += ["    }", "}", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    default = next((d for d in (os.path.join(ROOT, "..", "csharp-psi", ".corpus", "aspnetcore"), os.path.join(ROOT, "..", "..", "csharp-psi", ".corpus", "aspnetcore")) if os.path.isdir(d)), None)
    parser.add_argument("--aspnetcore", default=default, help="a checkout of dotnet/aspnetcore (src/ is enough)")
    args = parser.parse_args()
    if not args.aspnetcore or not os.path.isfile(os.path.join(args.aspnetcore, PROJECT)):
        raise SystemExit("no %s under --aspnetcore %s (csharp-psi: tools/fetch-corpus.sh)" % (PROJECT, args.aspnetcore))
    source = os.path.abspath(args.aspnetcore)
    project_dir = os.path.dirname(os.path.join(source, PROJECT))
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    shutil.copytree(project_dir, os.path.join(OUT, "src"), ignore=lambda d, names: [n for n in names if not os.path.isdir(os.path.join(d, n)) and not n.endswith(".cs")])
    shared = os.path.join(source, "src", "Shared")
    linked = 0
    for include in re.findall(r'<Compile Include="([^"]+)"', open(os.path.join(source, PROJECT), encoding="utf-8").read()):
        pattern = include.replace("$(SharedSourceRoot)", shared + os.sep).replace("\\", "/")
        base = shared if "$(SharedSourceRoot)" in include else project_dir
        if not os.path.isabs(pattern):
            pattern = os.path.join(project_dir, pattern)
        for path in glob.glob(pattern, recursive=True):
            relative = os.path.relpath(path, base)
            destination = os.path.join(OUT, "Shared" if base == shared else "Linked", relative.replace("..", "_"))
            os.makedirs(os.path.dirname(destination), exist_ok=True)
            shutil.copyfile(path, destination)
            linked += 1
    with open(os.path.join(OUT, "Resources.Designer.cs"), "w", encoding="utf-8", newline="\n") as out:
        out.write(resources_class(os.path.join(project_dir, "Resources.resx"), "Microsoft.AspNetCore.Mvc.Core"))
    with open(os.path.join(OUT, "MvcCoreSample.csproj"), "w", encoding="utf-8", newline="\n") as out:
        out.write(CSPROJ % PROJECT)
    with open(os.path.join(OUT, "MvcCoreSample.slnx"), "w", encoding="utf-8", newline="\n") as out:
        out.write('<Solution>\n  <Project Path="MvcCoreSample.csproj" />\n</Solution>\n')
    with open(os.path.join(OUT, "Measurements.cs"), "w", encoding="utf-8", newline="\n") as out:
        out.write(MEASUREMENTS)
    files = sum(len([f for f in names if f.endswith(".cs")]) for _, _, names in os.walk(OUT))
    print("%s: %d .cs files (%d linked shared sources); check: dotnet build %s" % (OUT, files, linked, os.path.join(OUT, "MvcCoreSample.slnx")))


if __name__ == "__main__":
    main()
