"""Builds src/main/resources/platformProbe/expected.json: what the LSP / DAP modules of IntelliJ IDEA 2026.1.4 contain, for the probe to compare another IDE with."""
import io, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'src', 'main', 'resources', 'platformProbe', 'expected.json')
d = json.load(io.open(os.path.join(HERE, 'api.json'), encoding='utf-8'))


def strip_generics(text):
    out, depth = [], 0
    for ch in text:
        if ch == '<':
            depth += 1
        elif ch == '>':
            depth -= 1
        elif depth == 0:
            out.append(ch)
    return ''.join(out)


def member_key(decl, class_name):
    text = strip_generics(decl).strip()
    text = re.sub(r'\s+throws\s.*$', '', text)
    if '(' not in text:
        return text.split(' ')[-1]  # a field
    head, params = text.split('(', 1)
    params = params.rsplit(')', 1)[0].strip()
    name = head.strip().split(' ')[-1]
    if name == class_name or name == class_name.replace('$', '.'):
        name = '<init>'
    return '%s/%d' % (name, len(params.split(',')) if params else 0)


def classes(items):
    result = {}
    for c in sorted(items, key=lambda c: c['name']):
        if c['name'] == '?':
            continue
        keys = sorted({member_key(m['decl'], c['name']) for m in c['members']})
        result[c['name']] = {'kind': c['kind'], 'marks': c['marks'], 'members': keys}
    return result


def attributes(xml, tag):
    return [dict(re.findall(r'([\w.]+)="([^"]*)"', m.group(1))) for m in re.finditer(r'<%s\b([^>]*?)/?>' % tag, xml, re.S)]


def points(xml):
    return [{'name': a.get('qualifiedName') or 'com.intellij.' + a['name'], 'interface': a.get('interface') or a.get('beanClass', '')} for a in attributes(xml, 'extensionPoint')]


def keys(xml):
    return [a['key'] for a in attributes(xml, 'registryKey') if 'key' in a]


lsp_xml = d['xml']['lsp.impl/intellij.platform.lsp.impl.xml'] + d['xml']['lsp/intellij.platform.lsp.xml']
dap_xml = d['xml']['dap/intellij.platform.dap.xml']
data = {
    'about': 'Public API of the platform LSP and DAP modules as javap shows it. A member is "name/parameterCount", a field is its name, a constructor is "<init>/n". '
             'Generated by gen_expected.py from the jars of the IDE named in "source"; not edited by hand.',
    'source': 'IU-261.26222.65',
    'areas': {
        'lsp': {'modules': ['intellij.platform.lsp', 'intellij.platform.lsp.impl'], 'extensionPoints': points(lsp_xml), 'registryKeys': keys(lsp_xml),
                'projectServices': ['com.intellij.platform.lsp.api.LspClientManager'], 'libraryClasses': ['org.eclipse.lsp4j.InitializeParams', 'org.eclipse.lsp4j.services.LanguageServer'],
                'classes': classes(d['lsp'])},
        'dap': {'modules': ['intellij.platform.dap'], 'extensionPoints': points(dap_xml), 'registryKeys': keys(dap_xml),
                'projectServices': [], 'programRunners': ['DebugAdapterRunner'],
                'libraryClasses': ['org.eclipse.lsp4j.debug.Capabilities', 'org.eclipse.lsp4j.debug.services.IDebugProtocolServer'], 'classes': classes(d['dap'])},
    },
}
os.makedirs(os.path.dirname(OUT), exist_ok=True)
json.dump(data, io.open(OUT, 'w', encoding='utf-8', newline='\n'), ensure_ascii=False, indent=1)
for name, area in data['areas'].items():
    print(name, [p['name'] for p in area['extensionPoints']], area['registryKeys'], len(area['classes']), 'classes', sum(len(c['members']) for c in area['classes'].values()), 'members')
print(re.findall(r'<programRunner[^>]*>', dap_xml), re.findall(r'<(?:project|application)Service[^>]*>', lsp_xml + dap_xml)[:8])
print(os.path.getsize(OUT))
