// Generated by `roslyndump gen-psi` (tools/csharp-psi/roslyndump/GenPsi.cs) from Roslyn's src/Compilers/CSharp/Portable/Syntax/Syntax.xml,
// roslynCommit 35d9211b841e7613c1d2f8f5af6d628ace696c4c. Do not edit: rerun gen-psi (tools/csharp-psi/roslyndump/README.md).
// Roslyn: Copyright (c) .NET Foundation and Contributors, MIT License (NOTICE.md).
package io.github.dotnetsupport.csharp.lang.psi

import com.intellij.psi.PsiElementVisitor

/**
 * Visitor over the generated PSI: one method per class of Syntax.xml; each delegates to the method of its Roslyn
 * base class, up to [visitCSharpElement] and [visitElement]. `accept` of every implementation calls its own method.
 */
@Suppress("unused")
open class CSharpVisitor : PsiElementVisitor() {
    open fun visitCSharpElement(o: CSharpElement) {
        visitElement(o)
    }

    open fun visitStructuredTrivia(o: CSharpStructuredTrivia) {
        visitCSharpElement(o)
    }

    open fun visitName(o: CSharpName) {
        visitType(o)
    }

    open fun visitSimpleName(o: CSharpSimpleName) {
        visitName(o)
    }

    open fun visitIdentifierName(o: CSharpIdentifierName) {
        visitSimpleName(o)
    }

    open fun visitQualifiedName(o: CSharpQualifiedName) {
        visitName(o)
    }

    open fun visitGenericName(o: CSharpGenericName) {
        visitSimpleName(o)
    }

    open fun visitTypeArgumentList(o: CSharpTypeArgumentList) {
        visitCSharpElement(o)
    }

    open fun visitAliasQualifiedName(o: CSharpAliasQualifiedName) {
        visitName(o)
    }

    open fun visitType(o: CSharpType) {
        visitExpression(o)
    }

    open fun visitPredefinedType(o: CSharpPredefinedType) {
        visitType(o)
    }

    open fun visitArrayType(o: CSharpArrayType) {
        visitType(o)
    }

    open fun visitArrayRankSpecifier(o: CSharpArrayRankSpecifier) {
        visitCSharpElement(o)
    }

    open fun visitPointerType(o: CSharpPointerType) {
        visitType(o)
    }

    open fun visitFunctionPointerType(o: CSharpFunctionPointerType) {
        visitType(o)
    }

    open fun visitFunctionPointerParameterList(o: CSharpFunctionPointerParameterList) {
        visitCSharpElement(o)
    }

    open fun visitFunctionPointerCallingConvention(o: CSharpFunctionPointerCallingConvention) {
        visitCSharpElement(o)
    }

    open fun visitFunctionPointerUnmanagedCallingConventionList(o: CSharpFunctionPointerUnmanagedCallingConventionList) {
        visitCSharpElement(o)
    }

    open fun visitFunctionPointerUnmanagedCallingConvention(o: CSharpFunctionPointerUnmanagedCallingConvention) {
        visitCSharpElement(o)
    }

    open fun visitNullableType(o: CSharpNullableType) {
        visitType(o)
    }

    open fun visitTupleType(o: CSharpTupleType) {
        visitType(o)
    }

    open fun visitTupleElement(o: CSharpTupleElement) {
        visitCSharpElement(o)
    }

    open fun visitOmittedTypeArgument(o: CSharpOmittedTypeArgument) {
        visitType(o)
    }

    open fun visitRefType(o: CSharpRefType) {
        visitType(o)
    }

    open fun visitScopedType(o: CSharpScopedType) {
        visitType(o)
    }

    open fun visitExpressionOrPattern(o: CSharpExpressionOrPattern) {
        visitCSharpElement(o)
    }

    open fun visitExpression(o: CSharpExpression) {
        visitExpressionOrPattern(o)
    }

    open fun visitParenthesizedExpression(o: CSharpParenthesizedExpression) {
        visitExpression(o)
    }

    open fun visitTupleExpression(o: CSharpTupleExpression) {
        visitExpression(o)
    }

    open fun visitPrefixUnaryExpression(o: CSharpPrefixUnaryExpression) {
        visitExpression(o)
    }

    open fun visitAwaitExpression(o: CSharpAwaitExpression) {
        visitExpression(o)
    }

    open fun visitPostfixUnaryExpression(o: CSharpPostfixUnaryExpression) {
        visitExpression(o)
    }

    open fun visitMemberAccessExpression(o: CSharpMemberAccessExpression) {
        visitExpression(o)
    }

    open fun visitConditionalAccessExpression(o: CSharpConditionalAccessExpression) {
        visitExpression(o)
    }

    open fun visitMemberBindingExpression(o: CSharpMemberBindingExpression) {
        visitExpression(o)
    }

    open fun visitElementBindingExpression(o: CSharpElementBindingExpression) {
        visitExpression(o)
    }

    open fun visitRangeExpression(o: CSharpRangeExpression) {
        visitExpression(o)
    }

    open fun visitImplicitElementAccess(o: CSharpImplicitElementAccess) {
        visitExpression(o)
    }

    open fun visitBinaryExpression(o: CSharpBinaryExpression) {
        visitExpression(o)
    }

    open fun visitAssignmentExpression(o: CSharpAssignmentExpression) {
        visitExpression(o)
    }

    open fun visitConditionalExpression(o: CSharpConditionalExpression) {
        visitExpression(o)
    }

    open fun visitInstanceExpression(o: CSharpInstanceExpression) {
        visitExpression(o)
    }

    open fun visitThisExpression(o: CSharpThisExpression) {
        visitInstanceExpression(o)
    }

    open fun visitBaseExpression(o: CSharpBaseExpression) {
        visitInstanceExpression(o)
    }

    open fun visitLiteralExpression(o: CSharpLiteralExpression) {
        visitExpression(o)
    }

    open fun visitFieldExpression(o: CSharpFieldExpression) {
        visitExpression(o)
    }

    open fun visitMakeRefExpression(o: CSharpMakeRefExpression) {
        visitExpression(o)
    }

    open fun visitRefTypeExpression(o: CSharpRefTypeExpression) {
        visitExpression(o)
    }

    open fun visitRefValueExpression(o: CSharpRefValueExpression) {
        visitExpression(o)
    }

    open fun visitCheckedExpression(o: CSharpCheckedExpression) {
        visitExpression(o)
    }

    open fun visitUnsafeExpression(o: CSharpUnsafeExpression) {
        visitExpression(o)
    }

    open fun visitDefaultExpression(o: CSharpDefaultExpression) {
        visitExpression(o)
    }

    open fun visitTypeOfExpression(o: CSharpTypeOfExpression) {
        visitExpression(o)
    }

    open fun visitSizeOfExpression(o: CSharpSizeOfExpression) {
        visitExpression(o)
    }

    open fun visitInvocationExpression(o: CSharpInvocationExpression) {
        visitExpression(o)
    }

    open fun visitElementAccessExpression(o: CSharpElementAccessExpression) {
        visitExpression(o)
    }

    open fun visitBaseArgumentList(o: CSharpBaseArgumentList) {
        visitCSharpElement(o)
    }

    open fun visitArgumentList(o: CSharpArgumentList) {
        visitBaseArgumentList(o)
    }

    open fun visitBracketedArgumentList(o: CSharpBracketedArgumentList) {
        visitBaseArgumentList(o)
    }

    open fun visitArgument(o: CSharpArgument) {
        visitCSharpElement(o)
    }

    open fun visitBaseExpressionColon(o: CSharpBaseExpressionColon) {
        visitCSharpElement(o)
    }

    open fun visitExpressionColon(o: CSharpExpressionColon) {
        visitBaseExpressionColon(o)
    }

    open fun visitNameColon(o: CSharpNameColon) {
        visitBaseExpressionColon(o)
    }

    open fun visitDeclarationExpression(o: CSharpDeclarationExpression) {
        visitExpression(o)
    }

    open fun visitCastExpression(o: CSharpCastExpression) {
        visitExpression(o)
    }

    open fun visitAnonymousFunctionExpression(o: CSharpAnonymousFunctionExpression) {
        visitExpression(o)
    }

    open fun visitAnonymousMethodExpression(o: CSharpAnonymousMethodExpression) {
        visitAnonymousFunctionExpression(o)
    }

    open fun visitLambdaExpression(o: CSharpLambdaExpression) {
        visitAnonymousFunctionExpression(o)
    }

    open fun visitSimpleLambdaExpression(o: CSharpSimpleLambdaExpression) {
        visitLambdaExpression(o)
    }

    open fun visitRefExpression(o: CSharpRefExpression) {
        visitExpression(o)
    }

    open fun visitParenthesizedLambdaExpression(o: CSharpParenthesizedLambdaExpression) {
        visitLambdaExpression(o)
    }

    open fun visitInitializerExpression(o: CSharpInitializerExpression) {
        visitExpression(o)
    }

    open fun visitBaseObjectCreationExpression(o: CSharpBaseObjectCreationExpression) {
        visitExpression(o)
    }

    open fun visitImplicitObjectCreationExpression(o: CSharpImplicitObjectCreationExpression) {
        visitBaseObjectCreationExpression(o)
    }

    open fun visitObjectCreationExpression(o: CSharpObjectCreationExpression) {
        visitBaseObjectCreationExpression(o)
    }

    open fun visitWithExpression(o: CSharpWithExpression) {
        visitExpression(o)
    }

    open fun visitAnonymousObjectMemberDeclarator(o: CSharpAnonymousObjectMemberDeclarator) {
        visitCSharpElement(o)
    }

    open fun visitAnonymousObjectCreationExpression(o: CSharpAnonymousObjectCreationExpression) {
        visitExpression(o)
    }

    open fun visitArrayCreationExpression(o: CSharpArrayCreationExpression) {
        visitExpression(o)
    }

    open fun visitImplicitArrayCreationExpression(o: CSharpImplicitArrayCreationExpression) {
        visitExpression(o)
    }

    open fun visitStackAllocArrayCreationExpression(o: CSharpStackAllocArrayCreationExpression) {
        visitExpression(o)
    }

    open fun visitImplicitStackAllocArrayCreationExpression(o: CSharpImplicitStackAllocArrayCreationExpression) {
        visitExpression(o)
    }

    open fun visitCollectionExpression(o: CSharpCollectionExpression) {
        visitExpression(o)
    }

    open fun visitCollectionElement(o: CSharpCollectionElement) {
        visitCSharpElement(o)
    }

    open fun visitExpressionElement(o: CSharpExpressionElement) {
        visitCollectionElement(o)
    }

    open fun visitSpreadElement(o: CSharpSpreadElement) {
        visitCollectionElement(o)
    }

    open fun visitWithElement(o: CSharpWithElement) {
        visitCollectionElement(o)
    }

    open fun visitQueryClause(o: CSharpQueryClause) {
        visitCSharpElement(o)
    }

    open fun visitSelectOrGroupClause(o: CSharpSelectOrGroupClause) {
        visitCSharpElement(o)
    }

    open fun visitQueryExpression(o: CSharpQueryExpression) {
        visitExpression(o)
    }

    open fun visitQueryBody(o: CSharpQueryBody) {
        visitCSharpElement(o)
    }

    open fun visitFromClause(o: CSharpFromClause) {
        visitQueryClause(o)
    }

    open fun visitLetClause(o: CSharpLetClause) {
        visitQueryClause(o)
    }

    open fun visitJoinClause(o: CSharpJoinClause) {
        visitQueryClause(o)
    }

    open fun visitJoinIntoClause(o: CSharpJoinIntoClause) {
        visitCSharpElement(o)
    }

    open fun visitWhereClause(o: CSharpWhereClause) {
        visitQueryClause(o)
    }

    open fun visitOrderByClause(o: CSharpOrderByClause) {
        visitQueryClause(o)
    }

    open fun visitOrdering(o: CSharpOrdering) {
        visitCSharpElement(o)
    }

    open fun visitSelectClause(o: CSharpSelectClause) {
        visitSelectOrGroupClause(o)
    }

    open fun visitGroupClause(o: CSharpGroupClause) {
        visitSelectOrGroupClause(o)
    }

    open fun visitQueryContinuation(o: CSharpQueryContinuation) {
        visitCSharpElement(o)
    }

    open fun visitOmittedArraySizeExpression(o: CSharpOmittedArraySizeExpression) {
        visitExpression(o)
    }

    open fun visitInterpolatedStringExpression(o: CSharpInterpolatedStringExpression) {
        visitExpression(o)
    }

    open fun visitIsPatternExpression(o: CSharpIsPatternExpression) {
        visitExpression(o)
    }

    open fun visitThrowExpression(o: CSharpThrowExpression) {
        visitExpression(o)
    }

    open fun visitWhenClause(o: CSharpWhenClause) {
        visitCSharpElement(o)
    }

    open fun visitPattern(o: CSharpPattern) {
        visitExpressionOrPattern(o)
    }

    open fun visitDiscardPattern(o: CSharpDiscardPattern) {
        visitPattern(o)
    }

    open fun visitDeclarationPattern(o: CSharpDeclarationPattern) {
        visitPattern(o)
    }

    open fun visitVarPattern(o: CSharpVarPattern) {
        visitPattern(o)
    }

    open fun visitRecursivePattern(o: CSharpRecursivePattern) {
        visitPattern(o)
    }

    open fun visitPositionalPatternClause(o: CSharpPositionalPatternClause) {
        visitCSharpElement(o)
    }

    open fun visitPropertyPatternClause(o: CSharpPropertyPatternClause) {
        visitCSharpElement(o)
    }

    open fun visitSubpattern(o: CSharpSubpattern) {
        visitCSharpElement(o)
    }

    open fun visitConstantPattern(o: CSharpConstantPattern) {
        visitPattern(o)
    }

    open fun visitParenthesizedPattern(o: CSharpParenthesizedPattern) {
        visitPattern(o)
    }

    open fun visitRelationalPattern(o: CSharpRelationalPattern) {
        visitPattern(o)
    }

    open fun visitTypePattern(o: CSharpTypePattern) {
        visitPattern(o)
    }

    open fun visitBinaryPattern(o: CSharpBinaryPattern) {
        visitPattern(o)
    }

    open fun visitUnaryPattern(o: CSharpUnaryPattern) {
        visitPattern(o)
    }

    open fun visitListPattern(o: CSharpListPattern) {
        visitPattern(o)
    }

    open fun visitSlicePattern(o: CSharpSlicePattern) {
        visitPattern(o)
    }

    open fun visitInterpolatedStringContent(o: CSharpInterpolatedStringContent) {
        visitCSharpElement(o)
    }

    open fun visitInterpolatedStringText(o: CSharpInterpolatedStringText) {
        visitInterpolatedStringContent(o)
    }

    open fun visitInterpolation(o: CSharpInterpolation) {
        visitInterpolatedStringContent(o)
    }

    open fun visitInterpolationAlignmentClause(o: CSharpInterpolationAlignmentClause) {
        visitCSharpElement(o)
    }

    open fun visitInterpolationFormatClause(o: CSharpInterpolationFormatClause) {
        visitCSharpElement(o)
    }

    open fun visitGlobalStatement(o: CSharpGlobalStatement) {
        visitMemberDeclaration(o)
    }

    open fun visitStatement(o: CSharpStatement) {
        visitCSharpElement(o)
    }

    open fun visitBlock(o: CSharpBlock) {
        visitStatement(o)
    }

    open fun visitLocalFunctionStatement(o: CSharpLocalFunctionStatement) {
        visitStatement(o)
    }

    open fun visitLocalDeclarationStatement(o: CSharpLocalDeclarationStatement) {
        visitStatement(o)
    }

    open fun visitVariableDeclaration(o: CSharpVariableDeclaration) {
        visitCSharpElement(o)
    }

    open fun visitVariableDeclarator(o: CSharpVariableDeclarator) {
        visitCSharpElement(o)
    }

    open fun visitEqualsValueClause(o: CSharpEqualsValueClause) {
        visitCSharpElement(o)
    }

    open fun visitVariableDesignation(o: CSharpVariableDesignation) {
        visitCSharpElement(o)
    }

    open fun visitSingleVariableDesignation(o: CSharpSingleVariableDesignation) {
        visitVariableDesignation(o)
    }

    open fun visitDiscardDesignation(o: CSharpDiscardDesignation) {
        visitVariableDesignation(o)
    }

    open fun visitParenthesizedVariableDesignation(o: CSharpParenthesizedVariableDesignation) {
        visitVariableDesignation(o)
    }

    open fun visitExpressionStatement(o: CSharpExpressionStatement) {
        visitStatement(o)
    }

    open fun visitEmptyStatement(o: CSharpEmptyStatement) {
        visitStatement(o)
    }

    open fun visitLabeledStatement(o: CSharpLabeledStatement) {
        visitStatement(o)
    }

    open fun visitGotoStatement(o: CSharpGotoStatement) {
        visitStatement(o)
    }

    open fun visitBreakStatement(o: CSharpBreakStatement) {
        visitStatement(o)
    }

    open fun visitContinueStatement(o: CSharpContinueStatement) {
        visitStatement(o)
    }

    open fun visitReturnStatement(o: CSharpReturnStatement) {
        visitStatement(o)
    }

    open fun visitThrowStatement(o: CSharpThrowStatement) {
        visitStatement(o)
    }

    open fun visitYieldStatement(o: CSharpYieldStatement) {
        visitStatement(o)
    }

    open fun visitWhileStatement(o: CSharpWhileStatement) {
        visitStatement(o)
    }

    open fun visitDoStatement(o: CSharpDoStatement) {
        visitStatement(o)
    }

    open fun visitForStatement(o: CSharpForStatement) {
        visitStatement(o)
    }

    open fun visitCommonForEachStatement(o: CSharpCommonForEachStatement) {
        visitStatement(o)
    }

    open fun visitForEachStatement(o: CSharpForEachStatement) {
        visitCommonForEachStatement(o)
    }

    open fun visitForEachVariableStatement(o: CSharpForEachVariableStatement) {
        visitCommonForEachStatement(o)
    }

    open fun visitUsingStatement(o: CSharpUsingStatement) {
        visitStatement(o)
    }

    open fun visitFixedStatement(o: CSharpFixedStatement) {
        visitStatement(o)
    }

    open fun visitCheckedStatement(o: CSharpCheckedStatement) {
        visitStatement(o)
    }

    open fun visitUnsafeStatement(o: CSharpUnsafeStatement) {
        visitStatement(o)
    }

    open fun visitLockStatement(o: CSharpLockStatement) {
        visitStatement(o)
    }

    open fun visitIfStatement(o: CSharpIfStatement) {
        visitStatement(o)
    }

    open fun visitElseClause(o: CSharpElseClause) {
        visitCSharpElement(o)
    }

    open fun visitSwitchStatement(o: CSharpSwitchStatement) {
        visitStatement(o)
    }

    open fun visitSwitchSection(o: CSharpSwitchSection) {
        visitCSharpElement(o)
    }

    open fun visitSwitchLabel(o: CSharpSwitchLabel) {
        visitCSharpElement(o)
    }

    open fun visitCasePatternSwitchLabel(o: CSharpCasePatternSwitchLabel) {
        visitSwitchLabel(o)
    }

    open fun visitCaseSwitchLabel(o: CSharpCaseSwitchLabel) {
        visitSwitchLabel(o)
    }

    open fun visitDefaultSwitchLabel(o: CSharpDefaultSwitchLabel) {
        visitSwitchLabel(o)
    }

    open fun visitSwitchExpression(o: CSharpSwitchExpression) {
        visitExpression(o)
    }

    open fun visitSwitchExpressionArm(o: CSharpSwitchExpressionArm) {
        visitCSharpElement(o)
    }

    open fun visitTryStatement(o: CSharpTryStatement) {
        visitStatement(o)
    }

    open fun visitCatchClause(o: CSharpCatchClause) {
        visitCSharpElement(o)
    }

    open fun visitCatchDeclaration(o: CSharpCatchDeclaration) {
        visitCSharpElement(o)
    }

    open fun visitCatchFilterClause(o: CSharpCatchFilterClause) {
        visitCSharpElement(o)
    }

    open fun visitFinallyClause(o: CSharpFinallyClause) {
        visitCSharpElement(o)
    }

    open fun visitCompilationUnit(o: CSharpCompilationUnit) {
        visitCSharpElement(o)
    }

    open fun visitExternAliasDirective(o: CSharpExternAliasDirective) {
        visitCSharpElement(o)
    }

    open fun visitUsingDirective(o: CSharpUsingDirective) {
        visitCSharpElement(o)
    }

    open fun visitMemberDeclaration(o: CSharpMemberDeclaration) {
        visitCSharpElement(o)
    }

    open fun visitBaseNamespaceDeclaration(o: CSharpBaseNamespaceDeclaration) {
        visitMemberDeclaration(o)
    }

    open fun visitNamespaceDeclaration(o: CSharpNamespaceDeclaration) {
        visitBaseNamespaceDeclaration(o)
    }

    open fun visitFileScopedNamespaceDeclaration(o: CSharpFileScopedNamespaceDeclaration) {
        visitBaseNamespaceDeclaration(o)
    }

    open fun visitAttributeList(o: CSharpAttributeList) {
        visitCSharpElement(o)
    }

    open fun visitAttributeTargetSpecifier(o: CSharpAttributeTargetSpecifier) {
        visitCSharpElement(o)
    }

    open fun visitAttribute(o: CSharpAttribute) {
        visitCSharpElement(o)
    }

    open fun visitAttributeArgumentList(o: CSharpAttributeArgumentList) {
        visitCSharpElement(o)
    }

    open fun visitAttributeArgument(o: CSharpAttributeArgument) {
        visitCSharpElement(o)
    }

    open fun visitNameEquals(o: CSharpNameEquals) {
        visitCSharpElement(o)
    }

    open fun visitTypeParameterList(o: CSharpTypeParameterList) {
        visitCSharpElement(o)
    }

    open fun visitTypeParameter(o: CSharpTypeParameter) {
        visitCSharpElement(o)
    }

    open fun visitBaseTypeDeclaration(o: CSharpBaseTypeDeclaration) {
        visitMemberDeclaration(o)
    }

    open fun visitTypeDeclaration(o: CSharpTypeDeclaration) {
        visitBaseTypeDeclaration(o)
    }

    open fun visitClassDeclaration(o: CSharpClassDeclaration) {
        visitTypeDeclaration(o)
    }

    open fun visitStructDeclaration(o: CSharpStructDeclaration) {
        visitTypeDeclaration(o)
    }

    open fun visitUnionDeclaration(o: CSharpUnionDeclaration) {
        visitTypeDeclaration(o)
    }

    open fun visitInterfaceDeclaration(o: CSharpInterfaceDeclaration) {
        visitTypeDeclaration(o)
    }

    open fun visitRecordDeclaration(o: CSharpRecordDeclaration) {
        visitTypeDeclaration(o)
    }

    open fun visitEnumDeclaration(o: CSharpEnumDeclaration) {
        visitBaseTypeDeclaration(o)
    }

    open fun visitDelegateDeclaration(o: CSharpDelegateDeclaration) {
        visitMemberDeclaration(o)
    }

    open fun visitEnumMemberDeclaration(o: CSharpEnumMemberDeclaration) {
        visitMemberDeclaration(o)
    }

    open fun visitExtensionBlockDeclaration(o: CSharpExtensionBlockDeclaration) {
        visitTypeDeclaration(o)
    }

    open fun visitBaseList(o: CSharpBaseList) {
        visitCSharpElement(o)
    }

    open fun visitBaseType(o: CSharpBaseType) {
        visitCSharpElement(o)
    }

    open fun visitSimpleBaseType(o: CSharpSimpleBaseType) {
        visitBaseType(o)
    }

    open fun visitPrimaryConstructorBaseType(o: CSharpPrimaryConstructorBaseType) {
        visitBaseType(o)
    }

    open fun visitTypeParameterConstraintClause(o: CSharpTypeParameterConstraintClause) {
        visitCSharpElement(o)
    }

    open fun visitTypeParameterConstraint(o: CSharpTypeParameterConstraint) {
        visitCSharpElement(o)
    }

    open fun visitConstructorConstraint(o: CSharpConstructorConstraint) {
        visitTypeParameterConstraint(o)
    }

    open fun visitClassOrStructConstraint(o: CSharpClassOrStructConstraint) {
        visitTypeParameterConstraint(o)
    }

    open fun visitTypeConstraint(o: CSharpTypeConstraint) {
        visitTypeParameterConstraint(o)
    }

    open fun visitDefaultConstraint(o: CSharpDefaultConstraint) {
        visitTypeParameterConstraint(o)
    }

    open fun visitAllowsConstraintClause(o: CSharpAllowsConstraintClause) {
        visitTypeParameterConstraint(o)
    }

    open fun visitAllowsConstraint(o: CSharpAllowsConstraint) {
        visitCSharpElement(o)
    }

    open fun visitRefStructConstraint(o: CSharpRefStructConstraint) {
        visitAllowsConstraint(o)
    }

    open fun visitBaseFieldDeclaration(o: CSharpBaseFieldDeclaration) {
        visitMemberDeclaration(o)
    }

    open fun visitFieldDeclaration(o: CSharpFieldDeclaration) {
        visitBaseFieldDeclaration(o)
    }

    open fun visitEventFieldDeclaration(o: CSharpEventFieldDeclaration) {
        visitBaseFieldDeclaration(o)
    }

    open fun visitExplicitInterfaceSpecifier(o: CSharpExplicitInterfaceSpecifier) {
        visitCSharpElement(o)
    }

    open fun visitBaseMethodDeclaration(o: CSharpBaseMethodDeclaration) {
        visitMemberDeclaration(o)
    }

    open fun visitMethodDeclaration(o: CSharpMethodDeclaration) {
        visitBaseMethodDeclaration(o)
    }

    open fun visitOperatorDeclaration(o: CSharpOperatorDeclaration) {
        visitBaseMethodDeclaration(o)
    }

    open fun visitConversionOperatorDeclaration(o: CSharpConversionOperatorDeclaration) {
        visitBaseMethodDeclaration(o)
    }

    open fun visitConstructorDeclaration(o: CSharpConstructorDeclaration) {
        visitBaseMethodDeclaration(o)
    }

    open fun visitConstructorInitializer(o: CSharpConstructorInitializer) {
        visitCSharpElement(o)
    }

    open fun visitDestructorDeclaration(o: CSharpDestructorDeclaration) {
        visitBaseMethodDeclaration(o)
    }

    open fun visitBasePropertyDeclaration(o: CSharpBasePropertyDeclaration) {
        visitMemberDeclaration(o)
    }

    open fun visitPropertyDeclaration(o: CSharpPropertyDeclaration) {
        visitBasePropertyDeclaration(o)
    }

    open fun visitArrowExpressionClause(o: CSharpArrowExpressionClause) {
        visitCSharpElement(o)
    }

    open fun visitEventDeclaration(o: CSharpEventDeclaration) {
        visitBasePropertyDeclaration(o)
    }

    open fun visitIndexerDeclaration(o: CSharpIndexerDeclaration) {
        visitBasePropertyDeclaration(o)
    }

    open fun visitAccessorList(o: CSharpAccessorList) {
        visitCSharpElement(o)
    }

    open fun visitAccessorDeclaration(o: CSharpAccessorDeclaration) {
        visitCSharpElement(o)
    }

    open fun visitBaseParameterList(o: CSharpBaseParameterList) {
        visitCSharpElement(o)
    }

    open fun visitParameterList(o: CSharpParameterList) {
        visitBaseParameterList(o)
    }

    open fun visitBracketedParameterList(o: CSharpBracketedParameterList) {
        visitBaseParameterList(o)
    }

    open fun visitBaseParameter(o: CSharpBaseParameter) {
        visitCSharpElement(o)
    }

    open fun visitParameter(o: CSharpParameter) {
        visitBaseParameter(o)
    }

    open fun visitFunctionPointerParameter(o: CSharpFunctionPointerParameter) {
        visitBaseParameter(o)
    }

    open fun visitIncompleteMember(o: CSharpIncompleteMember) {
        visitMemberDeclaration(o)
    }

    open fun visitSkippedTokensTrivia(o: CSharpSkippedTokensTrivia) {
        visitStructuredTrivia(o)
    }

    open fun visitDocumentationCommentTrivia(o: CSharpDocumentationCommentTrivia) {
        visitStructuredTrivia(o)
    }

    open fun visitCref(o: CSharpCref) {
        visitCSharpElement(o)
    }

    open fun visitTypeCref(o: CSharpTypeCref) {
        visitCref(o)
    }

    open fun visitQualifiedCref(o: CSharpQualifiedCref) {
        visitCref(o)
    }

    open fun visitMemberCref(o: CSharpMemberCref) {
        visitCref(o)
    }

    open fun visitNameMemberCref(o: CSharpNameMemberCref) {
        visitMemberCref(o)
    }

    open fun visitExtensionMemberCref(o: CSharpExtensionMemberCref) {
        visitMemberCref(o)
    }

    open fun visitIndexerMemberCref(o: CSharpIndexerMemberCref) {
        visitMemberCref(o)
    }

    open fun visitOperatorMemberCref(o: CSharpOperatorMemberCref) {
        visitMemberCref(o)
    }

    open fun visitConversionOperatorMemberCref(o: CSharpConversionOperatorMemberCref) {
        visitMemberCref(o)
    }

    open fun visitBaseCrefParameterList(o: CSharpBaseCrefParameterList) {
        visitCSharpElement(o)
    }

    open fun visitCrefParameterList(o: CSharpCrefParameterList) {
        visitBaseCrefParameterList(o)
    }

    open fun visitCrefBracketedParameterList(o: CSharpCrefBracketedParameterList) {
        visitBaseCrefParameterList(o)
    }

    open fun visitCrefParameter(o: CSharpCrefParameter) {
        visitCSharpElement(o)
    }

    open fun visitXmlNode(o: CSharpXmlNode) {
        visitCSharpElement(o)
    }

    open fun visitXmlElement(o: CSharpXmlElement) {
        visitXmlNode(o)
    }

    open fun visitXmlElementStartTag(o: CSharpXmlElementStartTag) {
        visitCSharpElement(o)
    }

    open fun visitXmlElementEndTag(o: CSharpXmlElementEndTag) {
        visitCSharpElement(o)
    }

    open fun visitXmlEmptyElement(o: CSharpXmlEmptyElement) {
        visitXmlNode(o)
    }

    open fun visitXmlName(o: CSharpXmlName) {
        visitCSharpElement(o)
    }

    open fun visitXmlPrefix(o: CSharpXmlPrefix) {
        visitCSharpElement(o)
    }

    open fun visitXmlAttribute(o: CSharpXmlAttribute) {
        visitCSharpElement(o)
    }

    open fun visitXmlTextAttribute(o: CSharpXmlTextAttribute) {
        visitXmlAttribute(o)
    }

    open fun visitXmlCrefAttribute(o: CSharpXmlCrefAttribute) {
        visitXmlAttribute(o)
    }

    open fun visitXmlNameAttribute(o: CSharpXmlNameAttribute) {
        visitXmlAttribute(o)
    }

    open fun visitXmlText(o: CSharpXmlText) {
        visitXmlNode(o)
    }

    open fun visitXmlCDataSection(o: CSharpXmlCDataSection) {
        visitXmlNode(o)
    }

    open fun visitXmlProcessingInstruction(o: CSharpXmlProcessingInstruction) {
        visitXmlNode(o)
    }

    open fun visitXmlComment(o: CSharpXmlComment) {
        visitXmlNode(o)
    }

    open fun visitDirectiveTrivia(o: CSharpDirectiveTrivia) {
        visitStructuredTrivia(o)
    }

    open fun visitBranchingDirectiveTrivia(o: CSharpBranchingDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitConditionalDirectiveTrivia(o: CSharpConditionalDirectiveTrivia) {
        visitBranchingDirectiveTrivia(o)
    }

    open fun visitIfDirectiveTrivia(o: CSharpIfDirectiveTrivia) {
        visitConditionalDirectiveTrivia(o)
    }

    open fun visitElifDirectiveTrivia(o: CSharpElifDirectiveTrivia) {
        visitConditionalDirectiveTrivia(o)
    }

    open fun visitElseDirectiveTrivia(o: CSharpElseDirectiveTrivia) {
        visitBranchingDirectiveTrivia(o)
    }

    open fun visitEndIfDirectiveTrivia(o: CSharpEndIfDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitRegionDirectiveTrivia(o: CSharpRegionDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitEndRegionDirectiveTrivia(o: CSharpEndRegionDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitErrorDirectiveTrivia(o: CSharpErrorDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitWarningDirectiveTrivia(o: CSharpWarningDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitBadDirectiveTrivia(o: CSharpBadDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitDefineDirectiveTrivia(o: CSharpDefineDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitUndefDirectiveTrivia(o: CSharpUndefDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitLineOrSpanDirectiveTrivia(o: CSharpLineOrSpanDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitLineDirectiveTrivia(o: CSharpLineDirectiveTrivia) {
        visitLineOrSpanDirectiveTrivia(o)
    }

    open fun visitLineDirectivePosition(o: CSharpLineDirectivePosition) {
        visitCSharpElement(o)
    }

    open fun visitLineSpanDirectiveTrivia(o: CSharpLineSpanDirectiveTrivia) {
        visitLineOrSpanDirectiveTrivia(o)
    }

    open fun visitPragmaWarningDirectiveTrivia(o: CSharpPragmaWarningDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitPragmaChecksumDirectiveTrivia(o: CSharpPragmaChecksumDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitReferenceDirectiveTrivia(o: CSharpReferenceDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitLoadDirectiveTrivia(o: CSharpLoadDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitShebangDirectiveTrivia(o: CSharpShebangDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitIgnoredDirectiveTrivia(o: CSharpIgnoredDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }

    open fun visitNullableDirectiveTrivia(o: CSharpNullableDirectiveTrivia) {
        visitDirectiveTrivia(o)
    }
}
